(function(ns){
  'use strict';
  class TDGame{
    constructor(canvas,ui){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.ui=ui;this.art=new ns.systems.ArtSystem();this.profession=new ns.systems.ProfessionSystem();this.path=new ns.systems.PathSystem();this.waves=new ns.systems.WaveSystem();this.build=new ns.systems.BuildSystem();this.monsters=[];this.projectiles=[];this.effects=[];this.hero=new ns.entities.Hero(350,305);this.economy={gold:ns.config.startGold,lumber:ns.config.startLumber,merit:0};this.baseHealth=ns.config.baseHealth;this.status='playing';this.dragHero=false;this.lastTime=0;this.attachInput();this.attachUi();this.updateUi();requestAnimationFrame(this.loop.bind(this));}
    canvasPoint(event){const rect=this.canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*this.canvas.width/rect.width,y:(event.clientY-rect.top)*this.canvas.height/rect.height};}
    attachInput(){const self=this;this.canvas.addEventListener('pointerdown',function(event){if(self.status!=='playing'||!self.profession.selected)return;const p=self.canvasPoint(event);if(self.build.selectAt(p.x,p.y)){self.dragHero=false;self.updateUi();return;}if(self.build.pendingType){self.build.updatePointer(p.x,p.y);if(self.build.placeQueued(p.x,p.y,self.economy))self.flash('守備單位部署完成','#e8c46b');else self.flash('此處無法建造或資源不足','#ff765c');self.updateUi();return;}self.build.selected=null;self.dragHero=true;self.hero.setTarget(p.x,p.y);self.updateUi();self.canvas.setPointerCapture(event.pointerId);});this.canvas.addEventListener('pointermove',function(event){const p=self.canvasPoint(event);if(self.build.pendingType)self.build.updatePointer(p.x,p.y);else if(self.dragHero&&self.status==='playing')self.hero.setTarget(p.x,p.y);});this.canvas.addEventListener('pointerup',function(){self.dragHero=false;});}
    attachUi(){const self=this;this.ui.wave.onclick=function(){self.startWave();};this.ui.skill.onclick=function(){self.castNova();};this.ui.restart.onclick=function(){self.reset();};this.ui.professionButtons.forEach(function(button){button.onclick=function(){self.chooseProfession(button.dataset.profession);};});this.ui.buildButtons.forEach(function(button){button.onclick=function(){self.queueTower(button.dataset.tower);};});this.ui.cancelBuild.onclick=function(){self.build.cancel();self.updateUi();};this.ui.upgrade.onclick=function(){if(self.build.upgrade(self.economy))self.flash('主力晉升！','#ffd36a');else self.flash('金幣或功勳不足','#ff765c');self.updateUi();};this.ui.sell.onclick=function(){if(self.build.sell(self.economy))self.flash('遣散並回收 70% 金幣','#d7f7e5');self.updateUi();};}
    chooseProfession(type){if(!this.profession.choose(type))return;this.ui.professionScreen.hidden=true;this.ui.buildButtons.forEach(function(button){button.hidden=button.dataset.tower!==type;});this.flash(this.profession.current().name+'進駐戰場',this.profession.current().color);this.updateUi();}
    reset(){this.waves.reset();this.build.reset();this.profession.reset();this.monsters=[];this.projectiles=[];this.effects=[];this.hero=new ns.entities.Hero(350,305);this.economy={gold:ns.config.startGold,lumber:ns.config.startLumber,merit:0};this.baseHealth=ns.config.baseHealth;this.status='playing';this.ui.overlay.hidden=true;this.ui.professionScreen.hidden=false;this.ui.buildButtons.forEach(function(button){button.hidden=true;});this.updateUi();}
    startWave(){if(this.status!=='playing'||!this.profession.selected)return;if(this.waves.start()){this.economy.gold+=12+this.waves.wave*3;this.economy.lumber+=this.waves.wave%5===0?2:1;this.flash('第 '+this.waves.wave+' 波來襲',this.waves.wave%5===0?'#ff416d':'#ffd36a');this.updateUi();}}
    queueTower(type){if(type!==this.profession.selected)return;if(this.build.queue(type)){const cfg=ns.config.towers[type];this.flash('選擇草地部署 '+cfg.name,cfg.color);this.updateUi();}}
    castNova(){if(this.status!=='playing'||!this.profession.selected)return;const self=this;if(this.hero.castNova(this.monsters,function(monster){self.onKill(monster); })){this.effects.push({type:'nova',x:this.hero.x,y:this.hero.y,time:.55,max:.55,color:'#70e7ff'});this.flash('霜環震擊！','#70e7ff');}this.updateUi();}
    onKill(monster,projectile){const bonus=projectile&&projectile.bountyBonus?projectile.bountyBonus:0;this.economy.gold+=Math.round(monster.reward*(1+bonus));if(monster.type==='boss'){this.economy.merit+=1;this.flash('擊破戰將 · 功勳 +1','#ffd36a');}this.effects.push({type:'burst',x:monster.x,y:monster.y,time:.35,max:.35,color:monster.color});}
    update(dt){if(this.status!=='playing'||!this.profession.selected)return;this.waves.update(dt,this.monsters);this.hero.update(dt,this.monsters,this.projectiles);this.build.towers().forEach(function(tower){tower.update(dt,this.monsters,this.projectiles);},this);const self=this;this.monsters.forEach(function(monster){monster.update(dt,self.hero);if(monster.leaked&&!monster.leakHandled){monster.leakHandled=true;self.baseHealth=Math.max(0,self.baseHealth-monster.baseDamage);self.flash('城門受損 -'+monster.baseDamage,'#ff416d');}});this.projectiles.forEach(function(projectile){projectile.update(dt,self.monsters,function(monster,source){self.onKill(monster,source);});});this.effects.forEach(function(effect){effect.time-=dt;});this.monsters=this.monsters.filter(function(m){return m.active;});this.projectiles=this.projectiles.filter(function(p){return p.active;});this.effects=this.effects.filter(function(e){return e.time>0;});if(this.baseHealth<=0)this.end(false);else if(this.waves.complete)this.end(true);this.updateUi();}
    end(victory){this.status=victory?'victory':'gameover';this.ui.overlay.hidden=false;this.ui.overlayTitle.textContent=victory?'邊境守住了！':'王城失守';this.ui.overlayMessage.textContent=victory?'你完成 15 波職業試煉。':'敵軍突破城門，抵達第 '+Math.max(1,this.waves.wave)+' 波。';}
    flash(text,color){this.effects.push({type:'text',text:text,x:ns.config.width/2,y:82,time:1.15,max:1.15,color:color});}
    updateUi(){const profession=this.profession.current(),tower=this.build.selected,cooldown=this.hero.novaCooldown;this.ui.gold.textContent=this.economy.gold;this.ui.lumber.textContent=this.economy.lumber;this.ui.merit.textContent=this.economy.merit;this.ui.health.textContent=this.baseHealth+' / '+ns.config.baseHealth;this.ui.waveStatus.textContent=this.waves.label();this.ui.wave.disabled=!profession||this.waves.active||this.waves.complete||this.status!=='playing';this.ui.wave.textContent=this.waves.active?'戰鬥中':(this.waves.wave?'開始第 '+(this.waves.wave+1)+' 波':'開始第一波');this.ui.skill.disabled=!profession||cooldown>0||this.status!=='playing';this.ui.skill.querySelector('span').textContent=cooldown>0?'霜環 '+cooldown.toFixed(1)+'s':'霜環震擊';if(!profession){this.ui.selectionType.textContent='等待指令';this.ui.selection.textContent='先選擇守備職業';this.ui.selectionStats.textContent='每局只能發展一條職業科技';this.ui.portrait.textContent='?';}else if(this.build.pendingType){const cfg=ns.config.towers[this.build.pendingType];this.ui.selectionType.textContent='部署模式';this.ui.selection.textContent='點擊草地放置 '+cfg.name;this.ui.selectionStats.textContent=cfg.cost+' 金幣 · '+cfg.wood+' 木材｜右側可取消';this.ui.portrait.textContent=cfg.icon;}else if(tower){const cfg=tower.config();this.ui.selectionType.textContent=profession.name;this.ui.selection.textContent=cfg.name+'　Lv.'+tower.level;this.ui.selectionStats.textContent='攻擊 '+Math.round(cfg.damage)+'｜射程 '+Math.round(cfg.range)+'｜'+cfg.attackType.toUpperCase();this.ui.portrait.textContent=cfg.icon;}else{this.ui.selectionType.textContent=profession.title;this.ui.selection.textContent=profession.name;this.ui.selectionStats.textContent=profession.description;this.ui.portrait.textContent=ns.config.towers[this.profession.selected].icon;}const upgrade=tower&&tower.upgradeCost();this.ui.upgrade.disabled=!upgrade||this.status!=='playing';this.ui.upgrade.querySelector('span').textContent=!tower?'升級':(!upgrade?'已滿級':'升級 '+upgrade.gold+'G'+(upgrade.merit?' +'+upgrade.merit+'功勳':''));this.ui.sell.disabled=!tower||this.status!=='playing';this.ui.sell.querySelector('span').textContent=tower?'遣散 +'+tower.sellValue()+'G':'遣散';this.ui.cancelBuild.disabled=!this.build.pendingType;this.ui.buildButtons.forEach(function(button){const type=button.dataset.tower,cfg=ns.config.towers[type];button.disabled=!profession||type!==this.profession.selected||this.status!=='playing';button.querySelector('span').textContent='部署 '+cfg.cost+'G/'+cfg.wood+'木';},this);}
    drawTerrain(){const ctx=this.ctx;const hasArt=this.art.drawBackground(ctx);if(!hasArt){const gradient=ctx.createLinearGradient(0,0,0,ns.config.height);gradient.addColorStop(0,'#45543a');gradient.addColorStop(1,'#222d20');ctx.fillStyle=gradient;ctx.fillRect(0,0,ns.config.width,ns.config.height);this.path.draw(ctx);}if(this.build.pendingType){ctx.save();ctx.globalAlpha=.12;ctx.strokeStyle='#d9d0a1';ctx.lineWidth=1;for(let x=30;x<720;x+=30){ctx.beginPath();ctx.moveTo(x,46);ctx.lineTo(x,720);ctx.stroke();}for(let y=60;y<720;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(720,y);ctx.stroke();}ctx.restore();}const vignette=ctx.createRadialGradient(360,350,260,360,350,570);vignette.addColorStop(.65,'transparent');vignette.addColorStop(1,'rgba(5,7,4,.34)');ctx.fillStyle=vignette;ctx.fillRect(0,0,720,720);ctx.fillStyle='rgba(15,16,12,.88)';ctx.fillRect(0,0,720,46);ctx.fillStyle='#e9ddb6';ctx.shadowColor='#000';ctx.shadowBlur=5;ctx.font='700 15px Georgia';ctx.fillText('銀葉邊境 · 人族防線',18,28);ctx.shadowBlur=0;}
    drawEffects(){const ctx=this.ctx;this.effects.forEach(function(effect){const ratio=effect.time/effect.max;ctx.save();if(effect.type==='text'){ctx.globalAlpha=Math.min(1,ratio*2);ctx.fillStyle=effect.color;ctx.shadowColor='#000';ctx.shadowBlur=8;ctx.textAlign='center';ctx.font='800 23px Segoe UI';ctx.fillText(effect.text,effect.x,effect.y-(1-ratio)*24);}else{ctx.globalAlpha=ratio;ctx.strokeStyle=effect.color;ctx.lineWidth=4;ctx.shadowColor=effect.color;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(effect.x,effect.y,(effect.type==='nova'?ns.config.hero.novaRange:32)*(1-ratio*.55),0,Math.PI*2);ctx.stroke();}ctx.restore();});}
    draw(){this.drawTerrain();this.build.draw(this.ctx,this.art);this.monsters.forEach(function(m){m.draw(this.ctx,this.art);},this);this.projectiles.forEach(function(p){p.draw(this.ctx);},this);this.hero.draw(this.ctx,this.art);this.drawEffects();}
    loop(timestamp){const dt=Math.min((timestamp-this.lastTime)/1000||0,.033);this.lastTime=timestamp;this.update(dt);this.draw();requestAnimationFrame(this.loop.bind(this));}
  }
  ns.TDGame=TDGame;
})(globalThis.TowerFrontier);
