(function(ns){
  'use strict';
  class TDGame{
    constructor(canvas,ui){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.ui=ui;this.path=new ns.systems.PathSystem();this.waves=new ns.systems.WaveSystem();this.build=new ns.systems.BuildSystem();this.monsters=[];this.projectiles=[];this.effects=[];this.hero=new ns.entities.Hero(105,375);this.economy={gold:ns.config.startGold};this.baseHealth=ns.config.baseHealth;this.status='playing';this.dragHero=false;this.lastTime=0;this.attachInput();this.attachUi();this.updateUi();requestAnimationFrame(this.loop.bind(this));}
    attachInput(){const self=this;function point(event){const rect=self.canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*self.canvas.width/rect.width,y:(event.clientY-rect.top)*self.canvas.height/rect.height};}
      this.canvas.addEventListener('pointerdown',function(event){if(self.status!=='playing')return;const p=point(event);if(self.build.selectAt(p.x,p.y)){self.dragHero=false;self.updateUi();}else{self.build.selected=null;self.dragHero=true;self.hero.setTarget(p.x,p.y);self.updateUi();}self.canvas.setPointerCapture(event.pointerId);});
      this.canvas.addEventListener('pointermove',function(event){if(self.dragHero&&self.status==='playing'){const p=point(event);self.hero.setTarget(p.x,p.y);}});this.canvas.addEventListener('pointerup',function(){self.dragHero=false;});
    }
    attachUi(){const self=this;this.ui.wave.onclick=function(){self.startWave();};this.ui.skill.onclick=function(){self.castNova();};this.ui.restart.onclick=function(){self.reset();};this.ui.buildButtons.forEach(function(button){button.onclick=function(){self.buildTower(button.dataset.tower);};});this.ui.upgrade.onclick=function(){if(self.build.upgrade(self.economy))self.flash('防禦塔升級','#ffd36a');self.updateUi();};this.ui.sell.onclick=function(){if(self.build.sell(self.economy))self.flash('已回收 70% 金幣','#d7f7e5');self.updateUi();};}
    reset(){this.waves.reset();this.build.reset();this.monsters=[];this.projectiles=[];this.effects=[];this.hero=new ns.entities.Hero(105,375);this.economy.gold=ns.config.startGold;this.baseHealth=ns.config.baseHealth;this.status='playing';this.ui.overlay.hidden=true;this.updateUi();}
    startWave(){if(this.status!=='playing')return;if(this.waves.start()){this.economy.gold+=8+this.waves.wave*2;this.flash('第 '+this.waves.wave+' 波來襲',this.waves.wave%5===0?'#ff416d':'#ffd36a');this.updateUi();}}
    buildTower(type){if(this.build.build(type,this.economy)){this.flash(ns.config.towers[type].name+' 完成',ns.config.towers[type].color);}else this.flash('金幣不足或塔位無效','#ff765c');this.updateUi();}
    castNova(){if(this.status!=='playing')return;const self=this;if(this.hero.castNova(this.monsters,function(monster){self.onKill(monster); })){this.effects.push({type:'nova',x:this.hero.x,y:this.hero.y,time:.55,max:.55,color:'#70e7ff'});this.flash('霜環震擊！','#70e7ff');}this.updateUi();}
    onKill(monster){this.economy.gold+=monster.reward;this.effects.push({type:'burst',x:monster.x,y:monster.y,time:.35,max:.35,color:monster.color});}
    update(dt){if(this.status!=='playing')return;this.waves.update(dt,this.monsters);this.hero.update(dt,this.monsters,this.projectiles);this.build.towers().forEach(function(tower){tower.update(dt,this.monsters,this.projectiles);},this);const self=this;this.monsters.forEach(function(monster){monster.update(dt,self.hero);if(monster.leaked&&!monster.leakHandled){monster.leakHandled=true;self.baseHealth=Math.max(0,self.baseHealth-monster.baseDamage);self.flash('城門受損 -'+monster.baseDamage,'#ff416d');}});this.projectiles.forEach(function(projectile){projectile.update(dt,self.monsters,function(monster){self.onKill(monster);});});this.effects.forEach(function(effect){effect.time-=dt;});this.monsters=this.monsters.filter(function(m){return m.active;});this.projectiles=this.projectiles.filter(function(p){return p.active;});this.effects=this.effects.filter(function(e){return e.time>0;});if(this.baseHealth<=0)this.end(false);else if(this.waves.complete)this.end(true);this.updateUi();}
    end(victory){this.status=victory?'victory':'gameover';this.ui.overlay.hidden=false;this.ui.overlayTitle.textContent=victory?'王城守住了！':'王城失守';this.ui.overlayMessage.textContent=victory?'你完成全部 20 波英雄遠征。':'敵軍突破城門，抵達第 '+Math.max(1,this.waves.wave)+' 波。';}
    flash(text,color){this.effects.push({type:'text',text:text,x:ns.config.width/2,y:82,time:1.15,max:1.15,color:color});}
    updateUi(){this.ui.gold.textContent=this.economy.gold;this.ui.health.textContent=this.baseHealth+' / '+ns.config.baseHealth;this.ui.waveStatus.textContent=this.waves.label();this.ui.wave.disabled=this.waves.active||this.waves.complete||this.status!=='playing';this.ui.wave.textContent=this.waves.active?'戰鬥中':(this.waves.wave?'開始第 '+(this.waves.wave+1)+' 波':'開始第一波');const cooldown=this.hero.novaCooldown;this.ui.skill.disabled=cooldown>0||this.status!=='playing';this.ui.skill.textContent=cooldown>0?'霜環 '+cooldown.toFixed(1)+'s':'❄ 霜環震擊';const pad=this.build.selected;this.ui.selection.textContent=!pad?'選擇地圖上的塔座或移動英雄':(!pad.tower?'空白塔座':pad.tower.config().name+' L'+pad.tower.level);this.ui.buildPanel.hidden=!pad||Boolean(pad.tower);this.ui.towerPanel.hidden=!pad||!pad.tower;if(pad&&pad.tower){this.ui.upgrade.textContent=pad.tower.level>=3?'已達最高等級':'升級 '+pad.tower.upgradeCost()+'G';this.ui.upgrade.disabled=pad.tower.level>=3;this.ui.sell.textContent='出售 +'+pad.tower.sellValue()+'G';}}
    drawTerrain(){const ctx=this.ctx;const gradient=ctx.createLinearGradient(0,0,0,ns.config.height);gradient.addColorStop(0,'#315d45');gradient.addColorStop(1,'#17392f');ctx.fillStyle=gradient;ctx.fillRect(0,0,ns.config.width,ns.config.height);ctx.save();ctx.globalAlpha=.18;for(let y=20;y<720;y+=45)for(let x=20;x<720;x+=45){ctx.fillStyle=(x+y)%90?'#9bc16b':'#28533c';ctx.beginPath();ctx.arc(x+Math.sin(y)*8,y+Math.cos(x)*6,3+(x%4),0,Math.PI*2);ctx.fill();}ctx.restore();
      ctx.fillStyle='#1b2c28';ctx.fillRect(0,0,720,46);ctx.fillStyle='#d7c59a';ctx.font='700 16px Segoe UI';ctx.fillText('銀葉王國 · 北境關口',20,29);this.path.draw(ctx);
      ctx.save();ctx.translate(678,615);ctx.fillStyle='#2a2022';ctx.fillRect(-40,-55,80,100);ctx.fillStyle='#b54343';ctx.beginPath();ctx.moveTo(-48,-50);ctx.lineTo(0,-88);ctx.lineTo(48,-50);ctx.closePath();ctx.fill();ctx.fillStyle='#ffc865';ctx.fillRect(-9,-6,18,51);ctx.restore();}
    drawEffects(){const ctx=this.ctx;this.effects.forEach(function(effect){const ratio=effect.time/effect.max;ctx.save();if(effect.type==='text'){ctx.globalAlpha=Math.min(1,ratio*2);ctx.fillStyle=effect.color;ctx.shadowColor='#000';ctx.shadowBlur=8;ctx.textAlign='center';ctx.font='800 24px Segoe UI';ctx.fillText(effect.text,effect.x,effect.y-(1-ratio)*24);}else{ctx.globalAlpha=ratio;ctx.strokeStyle=effect.color;ctx.lineWidth=4;ctx.shadowColor=effect.color;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(effect.x,effect.y,(effect.type==='nova'?ns.config.hero.novaRange:32)*(1-ratio*.55),0,Math.PI*2);ctx.stroke();}ctx.restore();});}
    draw(){this.drawTerrain();this.build.draw(this.ctx);this.monsters.forEach(function(m){m.draw(this.ctx);},this);this.projectiles.forEach(function(p){p.draw(this.ctx);},this);this.hero.draw(this.ctx);this.drawEffects();}
    loop(timestamp){const dt=Math.min((timestamp-this.lastTime)/1000||0,.033);this.lastTime=timestamp;this.update(dt);this.draw();requestAnimationFrame(this.loop.bind(this));}
  }
  ns.TDGame=TDGame;
})(globalThis.TowerFrontier);
