'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {load}=require('./helpers/td-runtime.cjs');
function storage(){const data=new Map();return{data,getItem:key=>data.get(key)||null,setItem:(key,value)=>data.set(key,value),removeItem:key=>data.delete(key)};}
function game(ns){const difficulty=new ns.systems.TDDifficultySystem();difficulty.choose('standard');const g={waves:new ns.systems.WaveSystem(),report:new ns.systems.BattleReportSystem(null),economy:new ns.systems.EconomySystem(),hero:new ns.entities.Hero(250,300),build:new ns.systems.BuildSystem(),factions:new ns.systems.FactionSystem(),loot:new ns.systems.LootSystem(),armory:new ns.systems.ArmorySystem(),difficulty,monsters:[],corpses:[],projectiles:[],summons:[],fieldLoot:[],baseHealth:17,maxBaseHealth:20};g.report.beginRun({map:'beginner',mapName:'新手谷地',difficulty:'standard',difficultyName:'邊境守衛',profession:'hunter',professionName:'守誓者・雷恩',faction:'hunter',factionName:'王國遠征軍',strategy:'mixed'});g.factions.choose('hunter');g.hero.chooseClass('hunter');g.waves.setModifiers(difficulty.modifiers());return g;}
test('只在第 10 與 20 波安全整備期建立章節存檔',()=>{const {ns}=load(),system=new ns.systems.ChapterCheckpointSystem(storage()),g=game(ns);g.waves.wave=9;assert.equal(system.capture(g),null);g.waves.wave=10;g.waves.active=true;assert.equal(system.capture(g),null);g.waves.active=false;assert.equal(system.capture(g).wave,10);g.waves.wave=20;assert.equal(system.capture(g).wave,20);});
test('章節存檔可完整還原資源、英雄、軍備、裝備、解鎖與戰報',()=>{const {ns}=load(),system=new ns.systems.ChapterCheckpointSystem(storage()),source=game(ns);source.waves.wave=10;source.economy.gold=1337;source.economy.lumber=21;source.economy.merit=8;source.hero.level=6;source.hero.x=444;source.armory.owned=['lion-bow'];const tower=new ns.entities.Building('arrow',310,240);tower.level=4;tower.branch='volley';tower.kills=19;source.build.items.push(tower);const unit=new ns.entities.CombatUnit('hunter',360,260);unit.unitId=7;unit.level=3;unit.gear.weapon='lion-bow';source.build.items.push(unit);source.factions.unlock('unit','orc');source.loot.claimed.add('orc-contract');source.report.waves.push({wave:10,score:555,time:30,kills:20,leaks:0,gateDamage:0,heroDowns:0,unitDowns:0,unitLosses:0,goldAfter:1337,lumberAfter:21,meritAfter:8});const saved=system.capture(source),target=game(ns);assert.ok(system.restore(target,system.read()));assert.equal(target.waves.wave,10);assert.equal(target.waves.phase,'preparing');assert.equal(target.economy.gold,1337);assert.equal(target.hero.level,6);assert.equal(target.hero.x,444);assert.equal(target.build.items[0].branch,'volley');assert.equal(target.build.items[1].unitId,7);assert.equal(target.armory.wearer('lion-bow'),target.build.items[1]);assert.ok(target.factions.unlockedUnits.has('orc'));assert.ok(target.loot.claimed.has('orc-contract'));assert.equal(target.report.waves[0].score,555);assert.equal(system.describe(saved),'新手谷地 · 邊境守衛 · 第 10 波後');});
test('損壞或舊格式存檔不會提供繼續遠征',()=>{const {ns}=load(),store=storage(),system=new ns.systems.ChapterCheckpointSystem(store);store.setItem(ns.systems.ChapterCheckpointSystem.STORAGE_KEY,'{broken');assert.equal(system.read(),null);store.setItem(ns.systems.ChapterCheckpointSystem.STORAGE_KEY,JSON.stringify({schema:0,wave:10}));assert.equal(system.read(),null);assert.equal(system.clear(),true);});

test('20與50波保存購石和進化结果；禁止存活試煉覆蓋安全存檔',()=>{
  const {ns}=load(),store=storage(),system=new ns.systems.ChapterCheckpointSystem(store),source=game(ns),E=ns.systems.HeroEvolutionSystem;
  source.checkpoints=system;source.saveChapterCheckpoint=()=>system.capture(source);source.waves.wave=20;source.economy.emblems=8;
  source.shop=new ns.systems.ShopSystem(source.hero,source.armory);source.shop.context=source;
  assert.equal(source.shop.buy('evolution-stone',source.economy).ok,true);assert.equal(system.read().hero.evolution.stones,1);assert.equal(system.read().economy.emblems,5);
  E.startTrial(source);assert.equal(system.capture(source),null);assert.equal(system.read().hero.evolution.trialStage,0);
  const boss=source.monsters[0];boss.takeDamage(999999,{owner:source.hero});E.completeTrial(source,boss);assert.equal(system.read().hero.evolution.rank,1);assert.equal(system.read().hero.evolution.stones,0);
  source.waves.wave=50;source.waves.complete=true;source.waves.phase='complete';source.evolutionCamp=true;
  source.shop.buy('evolution-stone',source.economy);E.startTrial(source);const final=source.monsters.at(-1);final.takeDamage(999999,{owner:source.hero});E.completeTrial(source,final);
  const target=game(ns);assert.equal(system.restore(target,system.read()),true);assert.equal(target.hero.evolution.rank,2);assert.equal(target.economy.emblems,0);assert.equal(target.evolutionCamp,true);assert.equal(target.waves.complete,true);assert.equal(target.waves.canStart(),false);assert.equal(target.hero.evolution.trialStage,0);
  E.training(target);assert.ok(system.capture(target),'trial dummy does not block safe final camp saves');
});

test('冰原章節存檔保留武器三階、兵塔與軍械，但不保存寒冬或待發攻擊',()=>{const {ns}=load(),system=new ns.systems.ChapterCheckpointSystem(storage()),source=game(ns);source.hero.chooseClass('frostland');source.factions.choose('frostland');source.hero.equipment.spear=3;source.hero.huntTime=5;source.waves.wave=10;source.build.items=[new ns.entities.CombatUnit('frostBear',120,200),new ns.entities.Building('frostGlacier',200,200)];source.build.items[0].gear.weapon='war-drum';source.build.items[0].frostAction={age:.2};source.armory.owned=['war-drum'];const saved=system.capture(source);assert.equal(saved.schema,1);assert.equal(saved.hero.huntTime,undefined);assert.equal(saved.buildings[0].frostAction,undefined);const target=game(ns);target.synergy={winter:{time:4}};assert.ok(system.restore(target,saved));assert.equal(target.hero.classType,'frostland');assert.equal(target.hero.equipment.spear,3);assert.equal(target.build.items[1].type,'frostGlacier');assert.equal(target.armory.wearer('war-drum'),target.build.items[0]);assert.equal(target.synergy.winter,null);assert.equal(target.hero.huntTime,0);});
