'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {load,game,enemy}=require('./helpers/td-runtime.cjs');
function canvas(){const calls=[];return {calls,ctx:new Proxy({},{get(t,k){return t[k]||((...args)=>calls.push([k,...args]));},set(t,k,v){t[k]=v;return true;}})};}
test('corrosion starts on actual curse/plague, refresh does not replay entry, expires with fade',()=>{const {ns}=load(),m=enemy(ns),f=new ns.systems.CombatFeedbackSystem();f.updateCorrosion(.1,[m]);assert.equal(f.corrosion.size,0);m.vulnerability={time:4,rate:.25};f.updateCorrosion(.1,[m]);assert.equal(f.corrosion.get(m).age,.1);m.vulnerability.time=4;f.updateCorrosion(.5,[m]);assert.equal(f.corrosion.get(m).age,.6);m.vulnerability=null;f.updateCorrosion(.1,[m]);assert.equal(f.corrosion.get(m).ending,true);const c=canvas();f.drawCorrosion(c.ctx,'ground');assert.ok(c.calls.some(x=>x[0]==='ellipse'));f.updateCorrosion(.4,[m]);assert.equal(f.corrosion.size,0);});
test('coexisting curse and plague share ring but have two badges; no false persistent pierce',()=>{const {ns}=load(),m=enemy(ns),f=new ns.systems.CombatFeedbackSystem();m.takeDamage(1,{armorPierce:8});f.updateCorrosion(.1,[m]);assert.equal(f.corrosion.size,0);m.vulnerability={time:4,rate:.25};m.plagueDot={time:4};f.updateCorrosion(.1,[m]);assert.equal(f.corrosion.size,1);const c=canvas();ns.systems.CombatFeedbackSystem.drawCorrosionBadge(c.ctx,m,0,0);assert.equal(c.calls.filter(x=>x[0]==='strokeRect').length,2);m.vulnerability=null;f.updateCorrosion(.1,[m]);assert.equal(f.corrosion.get(m).ending,false);assert.equal(f.corrosion.get(m).kinds.curse,false);});
test('death, removal and reset release references; reacquisition restarts entry',()=>{const {ns}=load(),m=enemy(ns),f=new ns.systems.CombatFeedbackSystem();m.plagueDot={time:4};f.updateCorrosion(.1,[m]);m.plagueDot=null;f.updateCorrosion(.2,[m]);m.plagueDot={time:4};f.updateCorrosion(.1,[m]);assert.equal(f.corrosion.get(m).age,.1);m.active=false;f.updateCorrosion(.1,[m]);assert.equal(f.corrosion.size,0);m.active=true;f.updateCorrosion(.1,[m]);f.updateCorrosion(.1,[]);assert.equal(f.corrosion.size,0);f.updateCorrosion(.1,[m]);f.reset();assert.equal(f.corrosion.size,0);});
test('VFX uses visual feet, has bounded detailed particles, and cannot alter combat',()=>{const {ns}=load(),f=new ns.systems.CombatFeedbackSystem(),monsters=Array.from({length:200},()=>enemy(ns));f.mobile=true;monsters.forEach(m=>{m.plagueDot={time:4};m.visualPosition=()=>({x:456,y:789});});const before=JSON.stringify(monsters);f.updateCorrosion(.6,monsters);const c=canvas();f.drawCorrosion(c.ctx,'ground');f.drawCorrosion(c.ctx,'air');assert.ok(c.calls.some(x=>x[0]==='translate'&&x[1]===456&&x[2]===792));assert.equal(c.calls.filter(x=>x[0]==='arc').length,24*3);assert.equal(JSON.stringify(monsters),before);});
test('real alchemist and plague hooks start VFX; damage and expiry still use synergy',()=>{const {ns}=load(),g=game(ns),m=enemy(ns);g.monsters=[m];g.synergy.hit(m,10,{owner:g.hero,vulnerability:.25,plague:true,damage:20});g.feedback.updateCorrosion(.1,g.monsters);assert.equal(g.feedback.corrosion.get(m).kinds.curse,true);assert.equal(g.feedback.corrosion.get(m).kinds.plague,true);const hp=m.health;g.synergy.update(.5);assert.ok(m.health<hp);g.synergy.update(4);g.feedback.updateCorrosion(.5,g.monsters);assert.equal(g.feedback.corrosion.size,0);});
