'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');
const root=path.resolve(__dirname,'..');const files=['src/td/namespace.js','src/td/config.js','src/td/systems/ProfessionSystem.js','src/td/systems/FactionSystem.js','src/td/systems/ArmorySystem.js','src/td/systems/LootSystem.js','src/td/systems/TDDifficultySystem.js','src/td/systems/BattleReportSystem.js','src/td/systems/PathSystem.js','src/td/systems/LayoutSystem.js','src/td/systems/NavigationSystem.js','src/td/systems/CommandSystem.js','src/td/systems/WaveCatalog.js','src/td/systems/EconomySystem.js','src/td/systems/CombatFeedbackSystem.js','src/td/systems/TowerEvolutionSystem.js','src/td/systems/TowerSkillSystem.js','src/td/systems/EquipmentSystem.js','src/td/systems/ShopSystem.js','src/td/entities/Summon.js','src/td/entities/Monster.js','src/td/systems/EnemyCombatSystem.js','src/td/systems/EnemyTraitSystem.js','src/td/entities/Projectile.js','src/td/entities/CombatUnit.js','src/td/entities/Building.js','src/td/systems/HeroRoster.js','src/td/entities/Hero.js','src/td/systems/WaveSystem.js','src/td/systems/BuildSystem.js'];
function load(){const context=vm.createContext({console});context.globalThis=context;files.forEach((file)=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file}));return context.TowerFrontier;}

test('怪物依道路節點移動並在終點標記漏怪',()=>{const ns=load();const monster=new ns.entities.Monster('runner',1,[{x:0,y:0},{x:10,y:0}]);monster.update(1);assert.equal(monster.active,false);assert.equal(monster.leaked,true);});

test('每波輪換敵人且每五波出現首領',()=>{const ns=load();const waves=new ns.systems.WaveSystem();assert.equal(waves.composition(1)[0].type,'grunt');assert.equal(waves.composition(2)[0].type,'runner');assert.equal(waves.composition(5)[0].type,'boss');assert.equal(waves.composition(5)[0].count,1);});

test('三十波資料表提供預告、獎勵與每五波首領',()=>{const ns=load(),catalog=new ns.systems.WaveCatalog();assert.equal(catalog.total(),30);for(let wave=1;wave<=30;wave+=1){const definition=catalog.get(wave),hasBoss=definition.groups.some((group)=>group.type==='boss');assert.equal(definition.threat,wave);assert.ok(definition.reward.gold>0);assert.equal(hasBoss,wave%5===0);}assert.equal(catalog.get(31),null);});

test('選職後有準備倒數，倒數結束或按鈕皆能開波',()=>{const ns=load(),waves=new ns.systems.WaveSystem(),monsters=[];assert.equal(waves.beginPreparation(),true);assert.equal(waves.phase,'preparing');assert.equal(waves.countdown,18);waves.update(17.5,monsters);assert.equal(waves.wave,0);waves.update(.6,monsters);assert.equal(waves.wave,1);assert.equal(waves.active,true);const manual=new ns.systems.WaveSystem();manual.beginPreparation();assert.equal(manual.start(),true);assert.equal(manual.wave,1);assert.equal(manual.phase,'spawning');});

test('清場獎勵只發出一次並自動進入下一波準備',()=>{const ns=load(),waves=new ns.systems.WaveSystem();waves.beginPreparation();waves.start();waves.queue=[];waves.phase='clearing';const event=waves.update(.1,[]);assert.equal(event.wave,1);assert.equal(waves.update(.1,[]),null);assert.equal(waves.acknowledgeReward(),true);assert.equal(waves.phase,'preparing');assert.equal(waves.countdown,12);});

test('第三十波結算後才完成遠征且不再開啟準備',()=>{const ns=load(),waves=new ns.systems.WaveSystem();waves.wave=29;waves.phase='waiting';assert.equal(waves.start(),true);assert.equal(waves.wave,30);waves.queue=[];waves.phase='clearing';const event=waves.update(.1,[]);assert.equal(event.wave,30);assert.equal(waves.acknowledgeReward(),true);assert.equal(waves.complete,true);assert.equal(waves.phase,'complete');assert.equal(waves.preview(),null);assert.equal(waves.beginPreparation(),false);});

test('後半 Boss 波縮短出兵空檔但保留可讀節奏',()=>{const ns=load(),waves=new ns.systems.WaveSystem();waves.wave=15;const early=waves.spawnInterval();waves.wave=30;const late=waves.spawnInterval();assert.ok(late<early);assert.ok(late>=.52);});

test('經濟系統集中處理消費、擊殺、波次結算與回收',()=>{const ns=load(),economy=new ns.systems.EconomySystem();assert.equal(economy.spend({gold:70,wood:1}),true);assert.equal(economy.gold,170);assert.equal(economy.lumber,4);assert.equal(economy.spend({gold:999}),false);const kill=economy.addKill({reward:13,type:'grunt'},.35);assert.equal(kill.gold,18);const boss=economy.addKill({reward:130,type:'boss'},0);assert.equal(boss.merit,1);const payout=economy.completeWave({gold:24,lumber:1});assert.deepEqual({gold:payout.gold,lumber:payout.lumber},{gold:24,lumber:1});economy.refundGold(49);assert.equal(economy.gold,391);});

test('六個 Boss 波總耐久高於前一波，避免難度反向下降',()=>{const ns=load(),catalog=new ns.systems.WaveCatalog();const health=(wave)=>catalog.get(wave).groups.reduce((sum,group)=>{const monster=new ns.entities.Monster(group.type,wave);return sum+monster.effectiveHealth()*group.count;},0);[5,10,15,20,25,30].forEach((wave)=>assert.ok(health(wave)>health(wave-1),'wave '+wave+' should exceed '+(wave-1)));});

test('建築不可堵路，但作戰單位可以部署到道路攔截',()=>{const ns=load();const build=new ns.systems.BuildSystem(),point=ns.config.path[4];assert.equal(build.canPlaceAt(point.x,point.y,'building'),false);assert.equal(build.canPlaceAt(point.x,point.y,'unit'),true);});

test('作戰單位與防禦建築使用不同實體及經濟',()=>{const ns=load();const build=new ns.systems.BuildSystem();const economy={gold:500,lumber:10,merit:0};assert.equal(build.queue('hunter','unit'),true);assert.equal(build.placeQueued(330,250,economy),true);assert.equal(build.selected.kind,'unit');assert.equal(build.queue('arrow','building'),true);assert.equal(build.placeQueued(480,250,economy),true);assert.equal(build.selected.kind,'building');assert.equal(build.combatUnits().length,1);assert.equal(build.buildings().length,1);});

test('作戰單位接受移動命令並切換行走與待機動畫',()=>{const ns=load();const unit=new ns.entities.CombatUnit('hunter',100,100);unit.setTarget(200,100);unit.update(.25,[],[]);assert.ok(unit.x>100);assert.equal(unit.state,'walk');assert.equal(unit.facing,0);unit.update(2,[],[]);assert.equal(unit.state,'idle');});

test('導航系統讓單位繞過防禦建築',()=>{const ns=load();const navigation=new ns.systems.NavigationSystem(),building={kind:'building',x:210,y:210};const path=navigation.findPath({x:100,y:210},{x:330,y:210},[building]);assert.ok(path.length>=2);assert.ok(path.some((point)=>Math.abs(point.y-210)>20));assert.equal(navigation.segmentClear({x:100,y:210},{x:330,y:210},[building]),false);});

test('指令系統可下達攻擊移動、固守與停止',()=>{const ns=load();const navigation=new ns.systems.NavigationSystem(),commands=new ns.systems.CommandSystem(),unit=new ns.entities.CombatUnit('hunter',100,100);commands.arm('attackMove');assert.equal(commands.issue(unit,250,100,navigation,[]),true);assert.equal(unit.order,'attackMove');assert.equal(commands.mode,'move');assert.equal(commands.hold(unit),true);assert.equal(unit.order,'hold');assert.equal(commands.stop(unit),true);assert.equal(unit.order,'idle');});

test('攻擊移動會停火接戰，一般移動則持續前進',()=>{const ns=load();const enemy=new ns.entities.Monster('grunt',1);enemy.x=120;enemy.y=100;const attackUnit=new ns.entities.CombatUnit('hunter',100,100),moveUnit=new ns.entities.CombatUnit('hunter',100,100),shots=[];attackUnit.cooldown=0;attackUnit.issueCommand('attackMove',{x:300,y:100},[{x:300,y:100}]);attackUnit.update(.1,[enemy],shots);assert.equal(shots.length,1);assert.equal(attackUnit.x,100);moveUnit.issueCommand('move',{x:300,y:100},[{x:300,y:100}]);moveUnit.update(.1,[enemy],[]);assert.ok(moveUnit.x>100);});

test('介面模式可自動判斷或手動切換並保存',()=>{const ns=load(),rootNode={dataset:{}},values={},storage={getItem:(key)=>values[key]||null,setItem:(key,value)=>{values[key]=value;}};let width=390;const layout=new ns.systems.LayoutSystem(rootNode,storage,()=>width);assert.equal(rootNode.dataset.layout,'mobile');assert.equal(layout.select('desktop'),true);assert.equal(rootNode.dataset.layout,'desktop');assert.equal(values.towerFrontierLayout,'desktop');width=1200;assert.equal(layout.select('auto'),true);assert.equal(rootNode.dataset.layout,'desktop');assert.equal(layout.select('invalid'),false);});

test('點擊空地不會在下達移動命令前遺失目前選取',()=>{const ns=load();const build=new ns.systems.BuildSystem(),economy={gold:300,lumber:5,merit:0};build.queue('hunter','unit');build.placeQueued(330,250,economy);const selected=build.selected;assert.equal(build.selectAt(600,600),null);assert.equal(build.selected,selected);});

test('職業單位可升至五級且高階升級消耗功勳',()=>{const ns=load();const build=new ns.systems.BuildSystem();const economy={gold:1000,lumber:5,merit:6};build.queue('arcanist','unit');build.placeQueued(330,250,economy);assert.equal(build.upgrade(economy),true);assert.equal(build.selected.level,2);assert.equal(build.upgrade(economy),true);assert.equal(build.selected.level,3);const merit=economy.merit;assert.equal(build.upgrade(economy),true);assert.equal(build.selected.level,4);assert.ok(economy.merit<merit);while(build.upgrade(economy));assert.equal(build.selected.level,5);assert.equal(build.selected.upgradeCost(),null);});

test('作戰單位停止移動後優先攻擊進度較前的目標',()=>{const ns=load();const unit=new ns.entities.CombatUnit('hunter',100,100);unit.cooldown=0;const back=new ns.entities.Monster('grunt',1),front=new ns.entities.Monster('grunt',1);back.x=110;back.y=100;back.index=2;front.x=120;front.y=100;front.index=4;const projectiles=[];unit.update(.1,[back,front],projectiles);assert.equal(projectiles.length,1);assert.equal(projectiles[0].target,front);assert.equal(unit.state,'attack');});

test('十三種不同外形防禦塔具有穿刺、緩速、範圍、召喚與靈魂戰術',()=>{const ns=load();assert.deepEqual(Object.keys(ns.config.buildings),['arrow','frost','cannon','storm','totem','crypt','soul','barracks','grove','graveyard','ballista','moonwell','plague']);assert.equal(ns.config.buildings.arrow.attackType,'pierce');assert.ok(ns.config.buildings.frost.slow<1);assert.ok(ns.config.buildings.cannon.splash>0);assert.equal(ns.config.buildings.soul.chain,2);assert.equal(ns.config.buildings.barracks.shots,2);assert.equal(ns.config.buildings.ballista.shots,2);assert.equal(ns.config.buildings.moonwell.chain,2);assert.ok(ns.config.buildings.plague.splash>0);});

test('穿刺攻擊對輕甲的傷害高於重甲',()=>{const ns=load();const light=new ns.entities.Monster('grunt',1),heavy=new ns.entities.Monster('brute',1);light.x=heavy.x=100;light.y=heavy.y=100;const lightBefore=light.health,heavyBefore=heavy.health;new ns.entities.Projectile({x:100,y:100},light,{damage:20,attackType:'pierce',color:'#fff'}).update(.1,[light]);new ns.entities.Projectile({x:100,y:100},heavy,{damage:20,attackType:'pierce',color:'#fff'}).update(.1,[heavy]);assert.ok(lightBefore-light.health>heavyBefore-heavy.health);});
test('命中回饋取得實際傷害並把護甲剋制標示為暴擊',()=>{const ns=load(),enemy=new ns.entities.Monster('grunt',1);enemy.x=enemy.y=100;let event;new ns.entities.Projectile({x:100,y:100},enemy,{damage:20,attackType:'pierce',color:'#fff'}).update(.1,[enemy],null,(monster,damage,critical)=>{event={monster,damage,critical};});assert.equal(event.monster,enemy);assert.equal(event.damage,27);assert.equal(event.critical,true);});
test('戰鬥回饋限制同屏數量且會在時間到後清除',()=>{const ns=load(),feedback=new ns.systems.CombatFeedbackSystem(),enemy=new ns.entities.Monster('grunt',1);enemy.x=enemy.y=100;for(let i=0;i<140;i++)feedback.hit(enemy,12,false,'#fff');assert.equal(feedback.items.length,120);feedback.gold(enemy,12);feedback.death(enemy);assert.equal(feedback.items.length,120);feedback.update(2);assert.equal(feedback.items.length,0);});
test('敵人血條以顯示生命平滑追上實際生命',()=>{const ns=load(),enemy=new ns.entities.Monster('brute',1,[{x:0,y:0},{x:500,y:0}]);enemy.takeDamage(60);const actual=enemy.health;assert.ok(enemy.displayHealth>actual);enemy.update(.03);assert.ok(enemy.displayHealth>actual);assert.ok(enemy.displayHealth<enemy.maxHealth);enemy.update(1);assert.equal(enemy.displayHealth,actual);});

test('三種職業可選擇且無效職業不會覆蓋選擇',()=>{const ns=load();const professions=new ns.systems.ProfessionSystem();assert.equal(professions.choose('rogue'),true);assert.equal(professions.current().name,'暗影行會');assert.equal(professions.choose('invalid'),false);assert.equal(professions.selected,'rogue');});

test('英雄可移動、自動攻擊並用霜環干擾範圍怪物',()=>{const ns=load();const hero=new ns.entities.Hero(100,100),monster=new ns.entities.Monster('grunt',1);monster.x=130;monster.y=100;hero.setTarget(200,100);const projectiles=[];hero.update(.1,[monster],projectiles);assert.ok(hero.x>100);assert.equal(hero.state,'attack');assert.equal(projectiles.length,0);hero.update(.19,[monster],projectiles);assert.equal(projectiles.length,1);const health=monster.health;assert.equal(hero.castNova([monster]),true);assert.ok(monster.health<health);assert.equal(monster.slowFactor,.38);assert.equal(hero.castNova([monster]),false);});

test('道路上的作戰單位會降低附近怪物推進速度',()=>{const ns=load();const path=[{x:0,y:100},{x:500,y:100}],normal=new ns.entities.Monster('grunt',1,path),blocked=new ns.entities.Monster('grunt',1,path);normal.update(1,null,[]);blocked.update(1,null,[{x:10,y:100}]);assert.ok(blocked.x<normal.x);});
test('英雄出手前死亡的目標不產生幽靈子彈，施法會取消蓄力',()=>{const ns=load(),hero=new ns.entities.Hero(100,100),enemy=new ns.entities.Monster('grunt',1),shots=[];enemy.x=130;enemy.y=100;hero.update(.01,[enemy],shots);enemy.active=false;hero.update(.2,[enemy],shots);assert.equal(shots.length,0);hero.castNova([],()=>{});assert.equal(hero.state,'cast');assert.equal(hero.pendingTarget,null);hero.update(.6,[],shots);assert.equal(hero.state,'idle');hero.setTarget(300,100);hero.update(.1,[],shots);assert.equal(hero.state,'walk');assert.ok(hero.x>100);});
test('英雄按鈕取消部署並清除守軍選取，不消耗資源',()=>{const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/TDGame.js'),'utf8'),context);const game=Object.create(ns.TDGame.prototype);Object.assign(game,{status:'playing',profession:{selected:'hunter'},build:new ns.systems.BuildSystem(),commands:new ns.systems.CommandSystem(),hero:new ns.entities.Hero(100,100),flash(){},showCommands(){},updateUi(){}});game.build.queue('arrow','building');game.build.selected={kind:'unit'};assert.equal(game.selectHero(),true);assert.equal(game.build.selected,null);assert.equal(game.build.pending,null);assert.equal(game.hero.selected,true);game.status='gameover';assert.equal(game.selectHero(),false);});
test('英雄動畫圖集存在且透明，分格渲染不改寫戰鬥數值',()=>{const file=fs.readFileSync(path.join(root,'assets/td/hero-actions-v1.png'));assert.equal(file.toString('ascii',1,4),'PNG');assert.equal(file[25],6);const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/systems/ArtSystem.js'),'utf8'),context);const art=Object.create(ns.systems.ArtSystem.prototype),draws=[];art.hero={ready:true,width:1254,height:1254};const ctx={save(){},restore(){},translate(){},scale(){},drawImage(...args){draws.push(args);}};const hero=new ns.entities.Hero(100,100);hero.state='attack';hero.frame=2;art.drawHero(ctx,hero);assert.equal(draws[0][1],627);assert.equal(draws[0][2],627);assert.equal(hero.health,100);});
test('三位英雄使用獨立圖集，不再與可部署守軍共用外觀',()=>{for(const file of ['hero-hunter-actions-v2.png','hero-actions-v1.png','hero-rogue-actions-v2.png']){const data=fs.readFileSync(path.join(root,'assets/td',file));assert.equal(data.readUInt32BE(16),1254);assert.equal(data.readUInt32BE(20),1254);assert.equal(data[25],6);}const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/systems/ArtSystem.js'),'utf8'),context);const art=Object.create(ns.systems.ArtSystem.prototype),images={hunter:{ready:true,width:1254,height:1254,id:'hero-hunter'},arcanist:{ready:true,width:1254,height:1254,id:'hero-arcanist'},rogue:{ready:true,width:1254,height:1254,id:'hero-rogue'}};art.heroHunter=images.hunter;art.hero=images.arcanist;art.heroRogue=images.rogue;art.equipmentAtlas=null;const draws=[],ctx={save(){},restore(){},translate(){},scale(){},drawImage(image){draws.push(image);}};for(const type of ['hunter','arcanist','rogue']){const hero=new ns.entities.Hero(100,100);hero.chooseClass(type);art.drawHero(ctx,hero);}assert.deepEqual(draws,Array.from(Object.values(images)));});
test('暫停時不推進波次、攻擊或怪物位置',()=>{const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/TDGame.js'),'utf8'),context);const game=Object.create(ns.TDGame.prototype);Object.assign(game,{paused:true,status:'playing',profession:{selected:'hunter'},waves:{update(){throw Error('Paused wave advanced');}}});assert.doesNotThrow(()=>game.update(1));});
test('戰鬥速度只接受一、二、三倍並同步更新介面',()=>{const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/TDGame.js'),'utf8'),context);const game=Object.create(ns.TDGame.prototype);Object.assign(game,{gameSpeed:1,effects:[],flash(){},updateUi(){this.updated=true;}});assert.equal(game.setGameSpeed(2),true);assert.equal(game.gameSpeed,2);assert.equal(game.updated,true);assert.equal(game.setGameSpeed(4),false);assert.equal(game.gameSpeed,2);});
test('五級外觀增加裝備與戰旗而不修改等級',()=>{const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/systems/ArtSystem.js'),'utf8'),context);const art=Object.create(ns.systems.ArtSystem.prototype),calls=[];const ctx=new Proxy({}, {get(target,key){return target[key]||((...args)=>calls.push([key,...args]));},set(target,key,value){target[key]=value;return true;}});art.drawRank(ctx,0,0,1,'#abc',true,'arrow');assert.equal(calls.length,0);art.drawRank(ctx,0,0,2,'#abc',true,'arrow');const level2=calls.length;calls.length=0;art.drawRank(ctx,0,0,5,'#abc',true,'arrow');assert.ok(calls.length>level2);});
test('六種塔均有技能說明，熟練度依擊殺提升且封頂',()=>{const ns=load();Object.keys(ns.config.buildings).forEach(type=>{const tower=new ns.entities.Building(type,100,100);assert.ok(ns.systems.TowerSkillSystem.describe(tower).includes('Lv.1'));const base=tower.config().damage;for(let i=0;i<5;i++)tower.registerKill();assert.equal(ns.systems.TowerSkillSystem.rank(tower.kills),2);assert.ok(tower.config().damage>base);tower.kills=1000;assert.equal(ns.systems.TowerSkillSystem.rank(tower.kills),5);assert.equal(ns.systems.TowerSkillSystem.progress(tower).next,null);});});
test('擊殺歸屬來源塔，只給一次金幣和熟練度',()=>{const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/TDGame.js'),'utf8'),context);const game=Object.create(ns.TDGame.prototype);game.economy=new ns.systems.EconomySystem();game.effects=[];game.flash=()=>{};const tower=new ns.entities.Building('arrow',100,100),monster=new ns.entities.Monster('grunt',1);monster.x=100;monster.y=100;monster.health=1;const shot=new ns.entities.Projectile(tower,monster,{damage:10});shot.hit([monster],(m,p)=>game.onKill(m,p));const gold=game.economy.gold;game.onKill(monster,shot);assert.equal(tower.kills,1);assert.equal(game.economy.gold,gold);});
test('齊射、冰爆、重砲和震地各有強化行為',()=>{const ns=load(),enemies=Array.from({length:6},(_,i)=>{const m=new ns.entities.Monster('brute',1);m.x=110+i*5;m.y=100;return m;});for(const type of ['arrow','frost','cannon','totem']){const tower=new ns.entities.Building(type,100,100);tower.kills=50;tower.shotsFired=4;const shots=[];ns.systems.TowerSkillSystem.fire(tower,enemies,shots,[]);if(type==='arrow')assert.equal(shots.length,6);else{assert.ok(shots[0].splash>50);if(type==='totem')assert.ok(shots[0].slow<1);}}});
test('連鎖雷電不重複命中同怪，也不越過跳躍距離',()=>{const ns=load(),tower=new ns.entities.Building('storm',100,100),enemies=[110,140,170,500].map(x=>{const m=new ns.entities.Monster('grunt',1);m.x=x;m.y=100;return m;});const health=enemies.map(m=>m.health),shot=new ns.entities.Projectile(tower,enemies[0],{damage:10,chain:6,chainRange:50});shot.hit(enemies,()=>{});assert.equal(health[0]-enemies[0].health,10);assert.equal(health[1]-enemies[1].health,7);assert.equal(health[2]-enemies[2].health,7);assert.equal(health[3],enemies[3].health);shot.update(1,enemies,()=>{});assert.equal(shot.active,false);});
test('召喚塔有數量上限，召喚攻擊繼承來源塔，賣塔解除守衛',()=>{const ns=load(),tower=new ns.entities.Building('crypt',100,100),enemy=new ns.entities.Monster('grunt',1);enemy.x=120;enemy.y=100;const summons=[],shots=[];for(let i=0;i<10;i++){tower.summonCooldown=0;ns.systems.TowerSkillSystem.fire(tower,[enemy],shots,summons);}assert.equal(summons.length,2);const spiritShots=[];summons[0].update(1,[enemy],spiritShots);assert.equal(spiritShots[0].owner,tower);tower.retired=true;summons[0].update(.1,[enemy],[]);assert.equal(summons[0].active,false);});
test('商店精確扣款、提高英雄傷害、拒絕超買與金幣不足',()=>{const ns=load(),hero=new ns.entities.Hero(100,100),shop=new ns.systems.ShopSystem(hero),economy=new ns.systems.EconomySystem();assert.equal(shop.buy('spear',economy).ok,true);assert.equal(economy.gold,140);assert.ok(hero.combatConfig().damage>ns.config.hero.damage);const gold=economy.gold;assert.equal(shop.buy('spear',economy).ok,false);assert.equal(economy.gold,gold);economy.gold=10000;shop.buy('spear',economy);shop.buy('spear',economy);assert.equal(hero.equipment.spear,3);const balance=economy.gold;assert.equal(shop.buy('spear',economy).ok,false);assert.equal(economy.gold,balance);assert.equal(shop.buy('invalid',economy).ok,false);});
test('英雄雷击无目标不消耗冷卻，召喚装备影響數量與壽命',()=>{const ns=load(),hero=new ns.entities.Hero(100,100),summons=[];assert.equal(hero.castThunder([],()=>{}),false);assert.equal(hero.skillCooldowns.thunder,0);hero.equipment.charm=3;hero.equipment.rune=3;assert.equal(hero.castSummon(summons),true);assert.equal(summons.length,3);assert.equal(summons[0].time,21);assert.ok(hero.skillCooldowns.summon<22);assert.equal(hero.castSummon(summons),false);summons[0].update(22,[],[]);assert.equal(summons[0].active,false);});
test('新族群塔升級選擇不同外形，未載入時能降級繪圖',()=>{const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/systems/ArtSystem.js'),'utf8'),context);const art=Object.create(ns.systems.ArtSystem.prototype),calls=[];art.drawRank=()=>{};art.factionTowers={ready:true,width:1254,height:1254};const ctx={drawImage(...args){calls.push(args);}};[1,3,5].forEach(l=>assert.equal(art.drawBuilding(ctx,'crypt',100,100,l),true));assert.ok(calls[0][2]<calls[1][2]&&calls[1][2]<calls[2][2]);art.factionTowers.ready=false;assert.equal(art.drawBuilding(ctx,'storm',100,100,1),false);const png=fs.readFileSync(path.join(root,'assets/td/faction-towers-v1.png'));assert.equal(png[25],6);});
test('三英雄具有不同普攻、技能與無效流派保護',()=>{const ns=load(),hero=new ns.entities.Hero(200,200);const configs=[];for(const type of ['hunter','arcanist','rogue']){assert.equal(hero.chooseClass(type),true);configs.push(hero.combatConfig().range);assert.equal(ns.systems.HeroRoster.get(type).skills.length,3);}assert.equal(new Set(configs).size,3);assert.equal(hero.chooseClass('invalid'),false);assert.equal(hero.classType,'rogue');});
test('獵手多重箭最多三目標，空場不耗冷卻',()=>{const ns=load(),hero=new ns.entities.Hero(200,200);hero.chooseClass('hunter');assert.equal(hero.castNova([],()=>{}),false);assert.equal(hero.novaCooldown,0);const monsters=Array.from({length:4},()=>new ns.entities.Monster('brute',1));monsters.forEach((m,i)=>{m.x=220+i*5;m.y=200;});hero.castNova(monsters,()=>{});assert.equal(monsters.filter(m=>m.health<m.maxHealth).length,3);assert.equal(hero.castNova(monsters,()=>{}),false);});
test('獵手陷阱固定地點緩速且會過期',()=>{const ns=load(),hero=new ns.entities.Hero(200,200),m=new ns.entities.Monster('brute',1);hero.chooseClass('hunter');m.x=210;m.y=200;hero.castThunder([m],()=>{});hero.x=500;ns.systems.HeroRoster.updateFields(hero,.5,[m],()=>{});assert.equal(m.slowFactor,.35);assert.equal(m.health,m.maxHealth);ns.systems.HeroRoster.updateFields(hero,9,[m],()=>{});assert.equal(hero.fields.length,0);});
test('盜賊閃擊移動並重擊，毒霧持續傷害並正確歸屬',()=>{const ns=load(),hero=new ns.entities.Hero(200,200),m=new ns.entities.Monster('boss',1);hero.chooseClass('rogue');m.x=250;m.y=200;hero.castNova([m],()=>{});assert.notEqual(hero.x,200);assert.ok(m.health<m.maxHealth);hero.castThunder([m],()=>{});m.health=1;let kills=0;ns.systems.HeroRoster.updateFields(hero,1,[m],(dead,shot)=>{kills++;assert.equal(shot.owner,hero);});assert.equal(kills,1);});
test('三流派召喚物分別為戰狼、元素與分身並受上限限制',()=>{const ns=load();for(const type of ['hunter','arcanist','rogue']){const hero=new ns.entities.Hero(200,200),summons=[];hero.chooseClass(type);assert.equal(hero.castSummon(summons),true);assert.equal(summons.length,2);assert.equal(summons[0].form,type);assert.notEqual(summons[0].x,summons[1].x);const enemy=new ns.entities.Monster('boss',1);enemy.x=270;enemy.y=220;const shots=[];for(let i=0;i<100;i++)summons[0].update(.03,[enemy],shots);assert.ok(shots.length>0);assert.equal(summons[0].range,type==='arcanist'?120:45);assert.equal(hero.castSummon(summons),false);}});
test('傭兵成功放置才扣金幣、不耗木，取消與無效位置免費',()=>{const ns=load(),build=new ns.systems.BuildSystem(),economy=new ns.systems.EconomySystem();build.queueMercenary('rogue');assert.equal(build.pendingCost().gold,98);assert.equal(build.placeQueued(0,0,economy),false);assert.equal(economy.gold,240);build.cancel();assert.equal(economy.gold,240);build.queueMercenary('arcanist');assert.equal(build.placeQueued(300,250,economy),true);assert.equal(economy.gold,112);assert.equal(economy.lumber,5);assert.equal(build.selected.mercenary,true);assert.equal(build.selected.totalSpent,128);build.selected.setTarget(400,250);build.selected.update(.2,[],[]);assert.ok(build.selected.x>300);economy.gold=500;assert.equal(build.upgrade(economy),true);assert.equal(build.selected.level,2);const refund=build.selected.sellValue(),before=economy.gold;build.sell(economy);assert.equal(economy.gold,before+refund);});
test('傭兵不足金幣不可生成或產生負數餘額',()=>{const ns=load(),build=new ns.systems.BuildSystem(),economy=new ns.systems.EconomySystem();economy.gold=0;build.queueMercenary('hunter');assert.equal(build.placeQueued(300,250,economy),false);assert.equal(build.items.length,0);assert.equal(economy.gold,0);assert.equal(build.queueMercenary('unknown'),false);});
test('怪物行走幀隨距離前進，緩速時步頻降低',()=>{const ns=load(),path=[{x:100,y:100},{x:700,y:100}],normal=new ns.entities.Monster('grunt',1,path),slow=new ns.entities.Monster('grunt',1,path);slow.applySlow(.5,5);normal.update(.4);slow.update(.4);assert.equal(normal.walkDistance,22);assert.equal(slow.walkDistance,11);assert.ok(normal.frame>slow.frame);assert.equal(normal.state,'walk');});
test('轉彎改變朝向，受擊動畫不修改移動距離',()=>{const ns=load(),m=new ns.entities.Monster('brute',1,[{x:100,y:100},{x:200,y:100},{x:100,y:100}]);m.update(3);assert.equal(m.facing,Math.PI);const x=m.x;m.takeDamage(1);assert.equal(m.state,'hit');m.update(.1);assert.equal(m.x,x-4);m.update(.2);assert.equal(m.state,'walk');});
test('死亡立即停止戰鬥且動畫只往前，不再重複掉錢',()=>{const ns=load(),m=new ns.entities.Monster('grunt',1);assert.equal(m.takeDamage(999),true);assert.equal(m.active,false);assert.equal(m.state,'death');assert.equal(m.takeDamage(999),false);const x=m.x;m.update(5);assert.equal(m.x,x);m.updateDeath(.4);assert.equal(m.frame,2);m.updateDeath(.5);assert.equal(m.frame,3);});
test('屍體不阻塞下一波清場結算',()=>{const ns=load(),wave=new ns.systems.WaveSystem(),m=new ns.entities.Monster('grunt',1);wave.beginPreparation();wave.start();wave.queue=[];wave.phase='clearing';m.takeDamage(999);assert.ok(wave.update(.1,[m]));});
test('敵軍動畫圖集具透明RGBA與一致四乘四尺寸',()=>{for(const type of ['grunt','runner','brute']){const bytes=fs.readFileSync(path.join(root,'assets/td/enemy-'+type+'-actions-v1.png'));assert.equal(bytes.readUInt32BE(16),bytes.readUInt32BE(20));assert.equal(bytes[25],6);assert.ok(bytes.length>10000);}});
test('新版半獸人步兵與武器圖集具透明 alpha 並符合格表尺寸',()=>{const grunt=fs.readFileSync(path.join(root,'assets/td/enemy-orc-grunt-actions-v2.png')),weapons=fs.readFileSync(path.join(root,'assets/td/items/weapons-atlas-v5.png'));assert.equal(grunt.readUInt32BE(16),grunt.readUInt32BE(20));assert.equal(grunt[25],6);assert.equal(weapons.readUInt32BE(16),1536);assert.equal(weapons.readUInt32BE(20),1024);assert.equal(weapons[25],6);assert.ok(grunt.length>10000&&weapons.length>10000);});

test('三職業各有四階武器且商店顯示正確下一階裝備',()=>{const ns=load();for(const type of ['hunter','arcanist','rogue']){const hero=new ns.entities.Hero(100,100);hero.chooseClass(type);const chain=ns.systems.EquipmentSystem.WEAPONS[type];assert.equal(chain.length,4);assert.equal(ns.systems.EquipmentSystem.weapon(hero).rarity,'base');assert.equal(ns.systems.EquipmentSystem.nextWeapon(hero).id,chain[1].id);const shop=new ns.systems.ShopSystem(hero);assert.equal(shop.offer('spear').visual.id,chain[1].id);}});
test('職業武器鍛造沿用原價格與每級百分之二十傷害成長',()=>{const ns=load(),hero=new ns.entities.Hero(100,100),shop=new ns.systems.ShopSystem(hero),economy=new ns.systems.EconomySystem();hero.chooseClass('rogue');economy.gold=1000;const base=hero.combatConfig().damage;assert.equal(shop.offer('spear').price,100);const result=shop.buy('spear',economy);assert.equal(result.ok,true);assert.equal(result.item.id,'steel-daggers');assert.equal(economy.gold,900);assert.equal(hero.combatConfig().damage,base*1.2);assert.equal(shop.offer('spear').price,160);});
test('職業武器簽名特效不改寫英雄戰鬥狀態',()=>{const ns=load(),hero=new ns.entities.Hero(100,100);hero.chooseClass('hunter');hero.equipment.spear=3;const snapshot={health:hero.health,x:hero.x,y:hero.y,state:hero.state};const ctx=new Proxy({}, {get(target,key){return target[key]||(()=>{});},set(target,key,value){target[key]=value;return true;}});ns.systems.EquipmentSystem.drawSignature(ctx,hero);assert.deepEqual({health:hero.health,x:hero.x,y:hero.y,state:hero.state},snapshot);});
test('九宮格職業武器圖集可離線載入且為透明 RGBA',()=>{const data=fs.readFileSync(path.join(root,'assets/td/items/class-weapons-atlas-v1.png'));assert.equal(data.readUInt32BE(16),1536);assert.equal(data.readUInt32BE(20),1024);assert.equal(data[25],6);assert.ok(data.length>10000);});
test('新版暗影英雄換裝使用專屬無武器底圖並逐手繪製兩把武器',()=>{const data=fs.readFileSync(path.join(root,'assets/td/hero-rogue-actions-unarmed-v2.png'));assert.equal(data.readUInt32BE(16),1254);assert.equal(data.readUInt32BE(20),1254);assert.equal(data[25],6);const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/systems/ArtSystem.js'),'utf8'),context);const art=Object.create(ns.systems.ArtSystem.prototype),draws=[];art.heroRogue={ready:true,width:1254,height:1254};art.rogueUnarmed={ready:true,width:1254,height:1254};art.weaponAtlas={ready:true,width:1536,height:1024};art.equipmentAtlas=null;const ctx=new Proxy({}, {get(target,key){if(key==='drawImage')return(...args)=>draws.push(args);return target[key]||(()=>{});},set(target,key,value){target[key]=value;return true;}}),hero=new ns.entities.Hero(100,100);hero.chooseClass('rogue');hero.equipment.spear=2;hero.state='attack';hero.frame=2;assert.equal(art.drawHero(ctx,hero),true);assert.equal(draws.length,3);assert.equal(draws[0][0],art.rogueUnarmed);assert.equal(draws[1][0],art.weaponAtlas);assert.equal(draws[2][0],art.weaponAtlas);});

test('英雄受傷倒下後在營地復活並取得短暫守護',()=>{const ns=load(),hero=new ns.entities.Hero(200,220);assert.equal(hero.takeDamage(35),35);assert.equal(hero.health,65);assert.equal(hero.takeDamage(999),65);assert.equal(hero.active,false);assert.equal(hero.setTarget(400,400),false);hero.update(ns.config.hero.respawnTime+.1,[],[]);assert.equal(hero.active,true);assert.equal(hero.health,65);assert.equal(hero.x,200);assert.equal(hero.y,220);assert.ok(hero.invulnerable>0);assert.equal(hero.takeDamage(20),0);});

test('守軍具有生命護甲、升級補血，死亡後由建造系統移除',()=>{const ns=load(),unit=new ns.entities.CombatUnit('hunter',200,200),build=new ns.systems.BuildSystem();const dealt=unit.takeDamage(12);assert.equal(dealt,11);const oldMax=unit.maxHealth;unit.upgrade();assert.ok(unit.maxHealth>oldMax);assert.ok(unit.health>oldMax-11);build.items.push(unit);unit.takeDamage(999);assert.equal(unit.active,false);assert.equal(build.combatUnits().length,0);unit.update(.81,[],[]);assert.equal(build.removeDefeated().length,1);assert.equal(build.items.length,0);});

test('一般難度守軍負傷後保留等級熟練與軍械並在倒數後歸隊',()=>{const ns=load(),build=new ns.systems.BuildSystem(),economy={gold:500,lumber:10,merit:0};build.setUnitRecovery({enabled:true,time:10,health:.6,guard:1.5});build.queue('orc','unit');build.placeQueued(300,250,economy);const unit=build.selected;unit.level=4;unit.kills=31;unit.gear.relic='war-drum';unit.takeDamage(999);assert.equal(unit.recovering,true);assert.equal(unit.permanentDefeat,false);unit.update(.81,[],[]);assert.equal(build.removeDefeated().length,0);assert.equal(build.items.length,1);unit.update(9.19,[],[]);assert.equal(unit.active,true);assert.equal(unit.level,4);assert.equal(unit.kills,31);assert.equal(unit.gear.relic,'war-drum');assert.equal(unit.health,Math.ceil(unit.maxHealth*.6));assert.equal(unit.order,'hold');assert.equal(unit.justRecovered,true);});

test('難度控制守軍恢復代價且災厄維持永久陣亡',()=>{const ns=load(),difficulty=new ns.systems.TDDifficultySystem();assert.equal(difficulty.current().unitRecovery.time,10);difficulty.choose('story');assert.equal(difficulty.current().unitRecovery.time,6);difficulty.choose('veteran');assert.equal(difficulty.current().unitRecovery.time,16);difficulty.choose('calamity');assert.equal(difficulty.current().unitRecovery.enabled,false);});

test('岩甲巨獸只攻擊近身守軍，虛空術士遠程獵殺英雄',()=>{const ns=load(),combat=new ns.systems.EnemyCombatSystem(),hero=new ns.entities.Hero(100,100),unit=new ns.entities.CombatUnit('hunter',205,200),brute=new ns.entities.Monster('brute',1),shaman=new ns.entities.Monster('shaman',1),hits=[];brute.x=200;brute.y=200;shaman.x=120;shaman.y=100;combat.update(1,[brute,shaman],hero,[unit],{onHit:(target)=>hits.push(target)});combat.update(.6,[brute,shaman],hero,[unit],{onHit:(target)=>hits.push(target)});assert.ok(unit.health<unit.maxHealth);assert.ok(hero.health<hero.maxHealth);assert.ok(hits.includes(unit));assert.ok(hits.includes(hero));});

test('Boss 低血量呼叫增援、進入狂暴並以預警踐踏傷害範圍友軍',()=>{const ns=load(),combat=new ns.systems.EnemyCombatSystem(),hero=new ns.entities.Hero(200,200),unit=new ns.entities.CombatUnit('hunter',230,200),boss=new ns.entities.Monster('boss',5),monsters=[boss],phases=[],warnings=[];boss.x=210;boss.y=200;boss.health=boss.maxHealth*.6;combat.update(.1,monsters,hero,[unit],{onBossPhase:(m,phase)=>phases.push(phase),onWarning:(m,label)=>warnings.push(label)});assert.equal(phases[0],2);assert.equal(monsters.length,3);boss.health=boss.maxHealth*.3;boss.abilityCooldown=0;combat.update(.1,monsters,hero,[unit],{onBossPhase:(m,phase)=>phases.push(phase),onWarning:(m,label)=>warnings.push(label)});assert.deepEqual(phases,[2,3]);assert.equal(boss.enraged,true);assert.ok(warnings.includes('戰爭踐踏'));const heroHealth=hero.health,unitHealth=unit.health;combat.update(1.2,monsters,hero,[unit],{});assert.ok(hero.health<heroHealth);assert.ok(unit.health<unitHealth);});

test('四種塔防難度提供不同城門、敵軍與收益且拒絕無效值',()=>{const ns=load(),difficulty=new ns.systems.TDDifficultySystem();assert.equal(difficulty.selected,'standard');assert.equal(difficulty.choose('calamity'),true);assert.equal(difficulty.current().baseHealth,15);assert.ok(difficulty.current().enemyHealth>1);assert.ok(difficulty.current().enemyDamage>1);assert.ok(difficulty.current().reward<1);assert.equal(difficulty.choose('invalid'),false);assert.equal(difficulty.selected,'calamity');assert.equal(Object.keys(ns.systems.TDDifficultySystem.MODES).length,4);});

test('難度修正同步影響生成怪物、準備時間與經濟收益',()=>{const ns=load(),difficulty=new ns.systems.TDDifficultySystem(),normal=new ns.entities.Monster('grunt',1);difficulty.choose('veteran');const waves=new ns.systems.WaveSystem();waves.setModifiers(difficulty.modifiers());waves.beginPreparation();assert.ok(waves.countdown<ns.config.wave.firstPreparation);waves.start();const monsters=[];waves.update(.2,monsters);assert.ok(monsters[0].maxHealth>normal.maxHealth);assert.ok(monsters[0].speed>normal.speed);const economy=new ns.systems.EconomySystem();economy.setRewardRate(difficulty.current().reward);assert.equal(economy.completeWave({gold:100,lumber:0}).gold,98);});

test('三十波會輪番出現八種敵軍定位而非只增加血量',()=>{const ns=load(),catalog=new ns.systems.WaveCatalog(),types=new Set();for(let wave=1;wave<=30;wave++)catalog.get(wave).groups.forEach(group=>types.add(group.type));assert.deepEqual(Array.from(types).sort(),['boss','brute','commander','grunt','healer','runner','shaman','warder']);assert.ok(catalog.get(18).groups.some(group=>group.type==='healer'));assert.ok(catalog.get(23).groups.some(group=>group.type==='brute'));assert.equal(catalog.get(30).groups.length,7);});

test('戰紋盾衛先以護盾吸收傷害並回報實際有效傷害',()=>{const ns=load(),warder=new ns.entities.Monster('warder',4),beforeHealth=warder.health,beforeBarrier=warder.barrier;let damage=0;new ns.entities.Projectile({x:warder.x,y:warder.y},warder,{damage:30,attackType:'magic',color:'#fff'}).hit([warder],null,(target,value)=>{damage=value;});assert.equal(warder.health,beforeHealth);assert.ok(warder.barrier<beforeBarrier);assert.equal(damage,beforeBarrier-warder.barrier);});

test('血契祭司定期治療低血友軍且不超過生命上限',()=>{const ns=load(),traits=new ns.systems.EnemyTraitSystem(),healer=new ns.entities.Monster('healer',7),target=new ns.entities.Monster('brute',7);healer.x=target.x=100;healer.y=target.y=100;target.health-=80;const before=target.health;let healed=0;traits.update(2,[healer,target],{onHeal:(source,unit,value)=>{healed+=value;}});assert.ok(target.health>before);assert.equal(healed,target.health-before);assert.ok(target.health<=target.maxHealth);});

test('軍團旗手強化附近敵軍速度與護甲但不影響遠方單位',()=>{const ns=load(),traits=new ns.systems.EnemyTraitSystem(),commander=new ns.entities.Monster('commander',6),near=new ns.entities.Monster('grunt',6),far=new ns.entities.Monster('grunt',6);commander.x=near.x=100;commander.y=near.y=100;far.x=500;far.y=500;traits.update(.1,[commander,near,far]);assert.equal(near.moveAura,1.18);assert.equal(near.temporaryArmor,1);assert.equal(far.moveAura,1);assert.equal(far.temporaryArmor,0);});

test('逐波戰報記錄擊破、漏怪、城門傷害與資源收入',()=>{const ns=load(),report=new ns.systems.BattleReportSystem();report.beginRun({difficultyName:'軍團老兵',professionName:'王國巡林者'});report.startWave(1,{baseHealth:18,gold:100,lumber:3});report.update(12.5);report.recordKill({type:'grunt'},{gold:13});report.recordLeak(2);const record=report.completeWave({baseHealth:16,gold:150,lumber:4},{gold:37,lumber:1});assert.equal(record.kills,1);assert.equal(record.leaks,1);assert.equal(record.gateDamage,2);assert.equal(record.totalGold,50);assert.equal(record.time,12.5);assert.equal(record.rank,'穩固');});

test('英雄倒下、守軍負傷與永久陣亡分開統計且 Boss 波被辨識為里程碑',()=>{const ns=load(),report=new ns.systems.BattleReportSystem();report.startWave(5,{baseHealth:20,gold:0,lumber:0});report.recordDefeat({});report.recordDefeat({kind:'unit',recovering:true});report.recordDefeat({kind:'unit',recovering:false});const record=report.completeWave({baseHealth:20,gold:80,lumber:1},{gold:80,lumber:1});assert.equal(record.heroDowns,1);assert.equal(record.unitDowns,1);assert.equal(record.unitLosses,1);assert.equal(report.milestone(record),true);assert.equal(record.rank,'險守');});

test('戰敗中的波次會封存為潰敗並加入總計',()=>{const ns=load(),report=new ns.systems.BattleReportSystem();report.startWave(3,{baseHealth:4,gold:90,lumber:2});report.recordKill({type:'runner'},{gold:10});report.recordLeak(5);const record=report.abortWave({baseHealth:0,gold:100,lumber:2});assert.equal(record.cleared,false);assert.equal(record.rank,'潰敗');assert.equal(report.totals().kills,1);assert.match(report.finalLine(),/總漏怪 1/);});

test('倒數自動開波與手動開波共用同一個開始事件',()=>{const ns=load(),waves=new ns.systems.WaveSystem(),started=[];waves.onStart=(wave)=>started.push(wave);waves.beginPreparation();waves.update(ns.config.wave.firstPreparation,[]);assert.deepEqual(started,[1]);waves.phase='reward';waves.pendingClear=null;waves.active=false;waves.acknowledgeReward();waves.update(ns.config.wave.preparation,[]);assert.deepEqual(started,[1,2]);});

test('三個英雄流派各提供兩種守軍與四種不同建築',()=>{const ns=load(),factions=new ns.systems.FactionSystem(),signature={hunter:'ballista',arcanist:'moonwell',rogue:'plague'};for(const id of ['hunter','arcanist','rogue']){assert.equal(factions.choose(id),true);assert.equal(factions.available('unit').length,2);assert.equal(factions.available('building').length,4);assert.equal(factions.allows('building',signature[id]),true);}factions.choose('hunter');assert.equal(factions.allows('unit','orc'),false);assert.equal(factions.unlock('unit','orc'),true);assert.equal(factions.allows('unit','orc'),true);});

test('第五波戰利品保證出現半獸人戰契並實際解鎖軍團',()=>{const ns=load(),loot=new ns.systems.LootSystem(()=>0),factions=new ns.systems.FactionSystem(),hero=new ns.entities.Hero(100,100),economy=new ns.systems.EconomySystem();factions.choose('hunter');const offers=loot.createOffers(5,'hunter');assert.ok(offers.some(item=>item.id==='orc-contract'));const item=loot.claim('orc-contract',{factions,hero,economy});assert.equal(item.name,'赤牙戰契');assert.equal(factions.allows('unit','orc'),true);assert.equal(factions.allows('building','totem'),true);assert.equal(loot.claim('orc-contract',{factions,hero,economy}),null);});

test('半獸人、盾衛、骷髏與幼龍都是可移動且可逐級進化的玩家單位',()=>{const ns=load();for(const type of ['orc','shield','skeleton','dragon']){const unit=new ns.entities.CombatUnit(type,100,100),names=[];for(let level=1;level<=5;level++){names.push(unit.evolutionName());if(level<5)unit.upgrade();}assert.equal(new Set(names).size,5);unit.setTarget(180,100);unit.update(.2,[],[]);assert.ok(unit.x>100);}});

test('作戰單位擊殺熟練度會提升並強化傷害',()=>{const ns=load(),unit=new ns.entities.CombatUnit('orc',100,100),base=unit.config().damage;for(let i=0;i<15;i++)unit.registerKill();assert.equal(unit.mastery(),3);assert.ok(unit.config().damage>base);});

test('防禦塔三級後可選擇互斥的進階分支',()=>{const ns=load(),tower=new ns.entities.Building('arrow',100,100);assert.equal(tower.chooseBranch('volley'),false);tower.upgrade();tower.upgrade();const before=tower.config();assert.equal(tower.chooseBranch('sniper'),true);const after=tower.config();assert.ok(after.damage>before.damage);assert.ok(after.range>before.range);assert.equal(ns.systems.TowerEvolutionSystem.label(tower),'巨獸獵塔');assert.equal(tower.chooseBranch('unknown'),false);});

test('戰狼使用四乘四透明動作圖集並具有跑步與撲咬狀態',()=>{const data=fs.readFileSync(path.join(root,'assets/td/war-wolf-actions-v1.png'));assert.equal(data.readUInt32BE(16)%4,0);assert.equal(data.readUInt32BE(20)%4,0);assert.equal(data[25],6);const ns=load(),hero=new ns.entities.Hero(100,100),summons=[];hero.chooseClass('hunter');hero.castSummon(summons);const wolf=summons[0],enemy=new ns.entities.Monster('boss',1);enemy.x=200;enemy.y=100;wolf.update(.1,[enemy],[]);assert.equal(wolf.state,'walk');wolf.x=170;wolf.cooldown=0;const shots=[];wolf.update(.1,[enemy],shots);assert.equal(wolf.state,'attack');assert.equal(shots[0].style,'bite');});

test('英雄擊殺經驗可升至十五級並同步強化生命、普攻與召喚物',()=>{const ns=load(),hero=new ns.entities.Hero(100,100),base=hero.combatConfig().damage;const result=hero.gainExperience(52);assert.equal(result.levels,1);assert.equal(hero.level,2);assert.equal(hero.maxHealth,110);assert.ok(hero.combatConfig().damage>base);hero.chooseClass('hunter');const summons=[];hero.castSummon(summons);assert.equal(summons[0].level,1);hero.skillCooldowns.summon=0;hero.level=6;summons.length=0;hero.castSummon(summons);assert.equal(summons[0].level,3);hero.gainExperience(100000);assert.equal(hero.level,15);assert.equal(hero.xpForNext(),null);});

test('後期 Boss 會沿用階段系統並增加戰術型援軍',()=>{const ns=load(),combat=new ns.systems.EnemyCombatSystem(),boss=new ns.entities.Monster('boss',30),monsters=[boss];boss.health=boss.maxHealth*.6;combat.phase(boss,monsters,{});assert.deepEqual(monsters.slice(1).map(monster=>monster.type),['runner','commander','healer','runner']);assert.ok(boss.abilityRadius>126);});

test('三族大型建築使用九宮格三級外觀並各有兩條進階分支',()=>{const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/systems/ArtSystem.js'),'utf8'),context);const art=Object.create(ns.systems.ArtSystem.prototype),calls=[];art.factionStructures={ready:true,width:1224,height:1224};art.drawRank=()=>{};const ctx={drawImage(...args){calls.push(args);}};for(const type of ['barracks','grove','graveyard']){assert.equal(ns.systems.TowerEvolutionSystem.branches(type).length,2);assert.equal(art.drawBuilding(ctx,type,100,100,1),true);assert.equal(art.drawBuilding(ctx,type,100,100,3),true);assert.equal(art.drawBuilding(ctx,type,100,100,5),true);}assert.equal(calls.length,9);assert.notEqual(calls[0][2],calls[1][2]);assert.notEqual(calls[0][1],calls[3][1]);const png=fs.readFileSync(path.join(root,'assets/td/faction-structures-v1.png'));assert.equal(png[25],6);});
test('三座增援塔使用獨立九宮格三級外觀與進階分支',()=>{const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/systems/ArtSystem.js'),'utf8'),context);const art=Object.create(ns.systems.ArtSystem.prototype),calls=[];art.factionTowersV2={ready:true,width:1254,height:1254};art.drawRank=()=>{};const ctx={drawImage(...args){calls.push(args);}};for(const type of ['ballista','moonwell','plague']){assert.equal(ns.systems.TowerEvolutionSystem.branches(type).length,2);for(const level of [1,3,5])assert.equal(art.drawBuilding(ctx,type,100,100,level),true);}assert.equal(calls.length,9);assert.notEqual(calls[0][2],calls[1][2]);assert.notEqual(calls[0][1],calls[3][1]);const png=fs.readFileSync(path.join(root,'assets/td/faction-towers-v2.png'));assert.equal(png[25],6);});

test('第三波依英雄流派保證一件可立即使用的軍械',()=>{const ns=load();const expectations={hunter:'lion-bow',arcanist:'moon-staff',rogue:'soul-lantern'};Object.entries(expectations).forEach(([profession,gear])=>{const loot=new ns.systems.LootSystem(()=>.7),offers=loot.createOffers(3,profession);assert.ok(offers.some(item=>item.gear===gear));});});

test('戰利裝備收入軍械庫後才能配置，且拒絕不相容單位',()=>{const ns=load(),loot=new ns.systems.LootSystem(()=>0),armory=new ns.systems.ArmorySystem(),factions=new ns.systems.FactionSystem(),hero=new ns.entities.Hero(100,100),economy=new ns.systems.EconomySystem();hero.chooseClass('hunter');loot.createOffers(3,'hunter');const reward=loot.claim('gear-lion-bow',{armory,factions,hero,economy});assert.equal(reward.gear,'lion-bow');assert.equal(armory.owned.join(','),'lion-bow');const orc=new ns.entities.CombatUnit('orc',100,100);assert.equal(armory.equip('lion-bow',orc).ok,false);assert.equal(armory.equip('lion-bow',hero).ok,true);assert.equal(hero.gear.weapon,'lion-bow');});

test('獅心王弓與月銀古杖改變英雄普攻配置和進階稱號',()=>{const ns=load(),armory=new ns.systems.ArmorySystem();const hunter=new ns.entities.Hero(100,100);hunter.chooseClass('hunter');const hunterBase=hunter.combatConfig();armory.obtain('lion-bow');assert.equal(armory.equip('lion-bow',hunter).ok,true);assert.ok(hunter.combatConfig().damage>hunterBase.damage);assert.equal(hunter.combatConfig().shots,2);assert.equal(ns.systems.ArmorySystem.title(hunter,'英雄'),'獅心神射手');const mage=new ns.entities.Hero(100,100);mage.chooseClass('arcanist');armory.obtain('moon-staff');assert.equal(armory.equip('moon-staff',mage).ok,true);assert.equal(mage.combatConfig().chain,2);});

test('赤牙戰鞍使半獸人變成更快的狼騎督軍',()=>{const ns=load(),armory=new ns.systems.ArmorySystem(),orc=new ns.entities.CombatUnit('orc',100,100),base=orc.config();armory.obtain('wolf-saddle');assert.equal(armory.equip('wolf-saddle',orc).ok,true);const mounted=orc.config();assert.ok(mounted.speed>base.speed);assert.ok(mounted.damage>base.damage);assert.equal(orc.evolutionName(),'赤牙狼騎督軍');assert.equal(ns.systems.ArmorySystem.visual(orc).mount,'wolf');});

test('狼騎外觀會合成戰狼、半獸人與戰鞍三層素材',()=>{const ns=load(),context=vm.createContext({TowerFrontier:ns});vm.runInContext(fs.readFileSync(path.join(root,'src/td/systems/ArtSystem.js'),'utf8'),context);const art=Object.create(ns.systems.ArtSystem.prototype),drawn=[];art.combatUnits={orc:{ready:true,width:400,height:400}};art.wolf={ready:true,width:400,height:400};art.equipmentAtlas={ready:true,width:1200,height:1200};art.drawRank=()=>{};const ctx=new Proxy({drawImage(image){drawn.push(image);}}, {get(target,key){return target[key]||(()=>{});},set(target,key,value){target[key]=value;return true;}}),unit={type:'orc',x:100,y:100,level:1,state:'walk',frame:1,frameClock:.3,facing:0,gear:{relic:'wolf-saddle'},config(){return{color:'#d76a48'};}};assert.equal(art.drawCombatUnit(ctx,unit),true);assert.ok(drawn.includes(art.wolf));assert.ok(drawn.includes(art.combatUnits.orc));assert.ok(drawn.includes(art.equipmentAtlas));});

test('唯一軍械轉裝時會從原持有人卸下並保留在新目標',()=>{const ns=load(),armory=new ns.systems.ArmorySystem(),first=new ns.entities.CombatUnit('orc',100,100),second=new ns.entities.CombatUnit('orc',140,100);armory.obtain('wolf-saddle');assert.equal(armory.equip('wolf-saddle',first).ok,true);const moved=armory.equip('wolf-saddle',second);assert.equal(moved.ok,true);assert.ok(moved.movedFrom);assert.equal(first.gear.relic,undefined);assert.equal(second.gear.relic,'wolf-saddle');assert.equal(armory.wearer('wolf-saddle'),second);});

test('生命軍械轉裝會同步新舊守軍生命上限且不殘留幽靈生命',()=>{const ns=load(),armory=new ns.systems.ArmorySystem(),first=new ns.entities.CombatUnit('shield',100,100),second=new ns.entities.CombatUnit('shield',140,100),base=first.maxHealth;armory.obtain('lion-shield');assert.equal(armory.equip('lion-shield',first).ok,true);assert.ok(first.maxHealth>base);assert.equal(first.health,first.maxHealth);assert.equal(armory.equip('lion-shield',second).ok,true);assert.equal(first.maxHealth,base);assert.equal(first.health,base);assert.ok(second.maxHealth>base);assert.equal(second.health,second.maxHealth);assert.equal(armory.unequip('armor',second).ok,true);assert.equal(second.maxHealth,base);assert.equal(second.health,base);});

test('卸裝、遣散與戰敗清除都會把唯一軍械送回軍械庫',()=>{const ns=load(),armory=new ns.systems.ArmorySystem(),build=new ns.systems.BuildSystem(),economy={gold:500,lumber:10,merit:0};build.onRemove=target=>armory.releaseTarget(target);build.queue('orc','unit');build.placeQueued(300,250,economy);const first=build.selected;armory.obtain('war-drum');armory.equip('war-drum',first);assert.equal(armory.unequip('relic',first).ok,true);assert.equal(armory.wearer('war-drum'),null);armory.equip('war-drum',first);assert.equal(build.sell(economy),true);assert.equal(armory.wearer('war-drum'),null);build.queue('orc','unit');build.placeQueued(340,250,economy);const second=build.selected;armory.equip('war-drum',second);second.active=false;second.deathTime=.9;build.removeDefeated();assert.equal(armory.wearer('war-drum'),null);});
