'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{load}=require('./helpers/td-runtime.cjs');
function context(ns){return{factions:new ns.systems.FactionSystem(),hero:new ns.entities.Hero(100,100),economy:new ns.systems.EconomySystem(),armory:new ns.systems.ArmorySystem()};}
test('Boss 必定掉裝備，地面已有三件時停止生成',()=>{const {ns}=load(),loot=new ns.systems.LootSystem(()=>.99),boss={type:'boss'};const drop=loot.rollDrop(boss,'hunter','hunter',0);assert.ok(drop&&drop.gear);assert.equal(loot.rollDrop(boss,'hunter','hunter',3),null);});
test('普通怪低機率、特殊怪較高機率，未觸發時不產生掉落',()=>{const {ns}=load();assert.equal(new ns.systems.LootSystem(()=>.5).rollDrop({type:'grunt'},'hunter','hunter',0),null);assert.ok(new ns.systems.LootSystem(()=>.01).rollDrop({type:'grunt'},'hunter','hunter',0));assert.ok(new ns.systems.LootSystem(()=>.15).rollDrop({type:'healer'},'hunter','hunter',0));});
test('英雄靠近自動拾取，逾時也可交由遊戲自動回收',()=>{const {ns}=load(),item=ns.systems.LootSystem.ITEMS['gear-lion-bow'],drop=new ns.entities.FieldLoot('gear-lion-bow',item,100,100);assert.equal(drop.update(.1,{x:140,y:100,active:true}),true);const far=new ns.entities.FieldLoot('gear-lion-bow',item,100,100);far.time=.05;assert.equal(far.update(.1,{x:500,y:500,active:true}),true);});
test('地面裝備使用軍械圖集、稀有度光柱與底座，不再只顯示文字圓章',()=>{const fs=require('node:fs'),field=fs.readFileSync('src/td/entities/FieldLoot.js','utf8'),game=fs.readFileSync('src/td/TDGame.js','utf8');assert.match(field,/equipmentAtlas/);assert.match(field,/drawImage\(atlas/);assert.match(field,/createLinearGradient/);assert.match(field,/roundRect/);assert.match(field,/ellipse/);assert.match(game,/drop\.draw\(this\.ctx,this\.art\)/);});
test('舊赤牙里程碑退役，其餘關鍵兵種仍直接解鎖',()=>{const {ns}=load(),loot=new ns.systems.LootSystem(()=>0),ctx=context(ns);ctx.factions.choose('hunter');assert.equal(loot.milestone(5,ctx),null);assert.equal(ctx.factions.allows('unit','orc'),false);assert.equal(loot.milestone(10,ctx).id,'dragon-egg');assert.equal(loot.milestone(15,ctx).id,'bone-contract');ctx.factions.choose('wild');assert.equal(ctx.factions.allows('unit','orc'),true);});
test('商城六種軍械可購買、收入軍械庫，單種最多三件',()=>{const {ns}=load(),ctx=context(ns),shop=new ns.systems.ShopSystem(ctx.hero,ctx.armory);ctx.economy.gold=5000;const ids=['gear-lion-bow','gear-moon-staff','gear-vine-crown','gear-war-drum','gear-soul-lantern','gear-bone-crown'];for(const id of ids){const offer=shop.offer(id);assert.ok(offer.gearItem);assert.equal(shop.buy(id,ctx.economy).ok,true);}for(let i=1;i<3;i++)assert.equal(shop.buy('gear-lion-bow',ctx.economy).ok,true);assert.equal(shop.buy('gear-lion-bow',ctx.economy).ok,false);assert.equal(ctx.armory.owned.filter(id=>id.startsWith('lion-bow')).length,3);});
test('波次守成邏輯不再呼叫強制戰利品選擇視窗',()=>{const fs=require('node:fs'),source=fs.readFileSync('src/td/TDGame.js','utf8'),waveBlock=source.slice(source.indexOf('const waveEvent='),source.indexOf('if(this.joystick)',source.indexOf('const waveEvent=')));assert.doesNotMatch(waveBlock,/openLoot\(/);assert.match(waveBlock,/collectAllFieldLoot\(\)/);});
