'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {load,game}=require('./helpers/td-runtime.cjs'),{rgba}=require('./png-pixels.cjs');
function setup(id='tidegateoutfall'){const {ns,context}=load();vm.runInContext(fs.readFileSync('src/td/maps.js','utf8'),context);ns.maps.apply(id);const g=game(ns);g.status='playing';g.profession.choose('hunter');g.waves={wave:2,active:true};g.adventure=new ns.systems.AdventureSystem(g);g.adventure.configure(ns.maps.definitions[id]);return {ns,g,s:g.adventure,A:ns.systems.AdventureArt};}
function canvas(){let depth=0;const commands=[],ctx=new Proxy({}, {get(target,key){if(key==='save')return()=>{depth++;commands.push(['save']);};if(key==='restore')return()=>{depth--;assert.ok(depth>=0);commands.push(['restore']);};return target[key]??((...args)=>{args.filter(v=>typeof v==='number').forEach(v=>assert.ok(Number.isFinite(v),key));commands.push([key,...args]);});},set(target,key,value){target[key]=value;return true;}});return {ctx,commands,depth:()=>depth};}
test('five production atlases contain real transparent alpha and every declared frame is nonempty and in bounds',()=>{const {A}=setup(),worker=fs.readFileSync('sw.js','utf8');for(const sheet of Object.values(A.SHEETS)){const path=A.ROOT+sheet.file,{width,height,pixels}=rgba(path);assert.ok(pixels[3]<=2,path);assert.ok(pixels[(width*height-1)*4+3]<=2,path);assert.ok(worker.includes(path),path+' cached');for(const [x,y,w,h] of sheet.frames){assert.ok([x,y,w,h].every(Number.isInteger));assert.ok(x>=0&&y>=0&&x+w<=width&&y+h<=height,path);let visible=0,clear=0;for(let py=y;py<y+h;py++)for(let px=x;px<x+w;px++){const a=pixels[(py*width+px)*4+3];if(a>32)visible++;if(a===0)clear++;}assert.ok(visible>10000,path+' populated frame');assert.ok(clear>1000,path+' has actual cutout');}}});
test('water sluice opens, loops two different flow frames, closes, freezes on pause and returns idle on expiry',()=>{const {g,s,A}=setup();assert.equal(A.choice(s,s.node('main')).frame,0);s.act('main','activate');assert.equal(A.choice(s,s.node('main')).frame,0);s.update(.25);assert.equal(A.choice(s,s.node('main')).frame,1);s.update(.25);s.update(.25);const flow=s.fields[0],frames=new Set();for(let i=0;i<10;i++){s.update(.1);frames.add(A.choice(s,s.node('main')).frame);}assert.deepEqual([...frames].sort(),[2,3]);const clock=s.clock,frame=A.waterFrame(flow),time=flow.time;g.paused=true;s.update(.25);assert.equal(s.clock,clock);assert.equal(flow.time,time);assert.equal(A.waterFrame(flow),frame);g.paused=false;flow.time=.3;assert.equal(A.waterFrame(flow),1);flow.time=.1;assert.equal(A.waterFrame(flow),0);s.update(.25);assert.equal(s.fields.length,0);assert.equal(A.choice(s,s.node('main')).frame,0);});
test('water flow follows current published paths, is clipped to the effect and never changes combat positions',()=>{const {g,s,A}=setup();s.act('main','activate');s.update(.25);const before=JSON.stringify({hero:[g.hero.x,g.hero.y,g.hero.health,g.hero.targetX,g.hero.targetY],paths:s.definition.nodes}),a=canvas();A.fields(a.ctx,s);assert.ok(a.commands.some(c=>c[0]==='clip'));assert.ok(a.commands.some(c=>c[0]==='lineTo'));assert.ok(!a.commands.some(c=>c[0]==='fill'),'water is directional flow, not a filled circle');assert.equal(a.depth(),0);assert.equal(JSON.stringify({hero:[g.hero.x,g.hero.y,g.hero.health,g.hero.targetX,g.hero.targetY],paths:s.definition.nodes}),before);const first=JSON.stringify(a.commands),b=canvas();s.update(.25);A.fields(b.ctx,s);assert.notEqual(JSON.stringify(b.commands),first,'foam actually advances');});
test('repair and platform use distinct raster states; missing art can retry without adding rewards or blocking actions',()=>{const {s,A}=setup('westernsignal'),node=s.node('main');assert.equal(A.choice(s,node).frame,0);s.states.main.status='repaired';assert.equal(A.choice(s,node).frame,1);let loads=0,retries=0;const art={load(src){loads++;return {ready:false,failed:false,assetSrc:src};},request(image){retries++;image.ready=true;}};A.preload(art);A.preload(art);assert.equal(loads,5);assert.equal(A.status(art).ready,0);art.adventureAssets.water.failed=true;A.retry(art);assert.equal(retries,1);assert.equal(A.status(art).ready,1);const c=canvas();assert.equal(A.cell(c.ctx,art,'water',0,100,false),true);assert.equal(A.cell(c.ctx,art,'beacons',0,100,false),false);assert.equal(c.depth(),0);});
test('repair checks actual wood costs and never charges gold when wood is missing',()=>{const {g,s}=setup('westernsignal');g.economy.gold=100;g.economy.lumber=0;assert.equal(s.act('main','repair').ok,false);assert.equal(g.economy.gold,100);g.economy.lumber=2;assert.equal(s.act('main','repair').ok,true);assert.equal(g.economy.gold,40);assert.equal(g.economy.lumber,1);assert.equal(s.act('main','repair').ok,false);assert.equal(g.economy.lumber,1);});
