'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {rgba}=require('./png-pixels.cjs');const {load,game}=require('./helpers/td-runtime.cjs');
const assets=['assets/td/dwarf/hero-actions-v2.png','assets/td/dwarf/weapons-v1.png','assets/td/dragonkin/hero-actions-v2.png','assets/td/dragonkin/weapons-v1.png','assets/td/egypt/hero-actions-v3.png','assets/td/egypt/weapons-v1.png'];
const towerAssets=['assets/td/dwarf/buildings-atlas-v1.png','assets/td/dragonkin/buildings-atlas-v2.png','assets/td/egypt/buildings-atlas-v2.png'];
test('三個南方軍團可遊玩；埃及島劇情保留伏筆',()=>{const {ns}=load();for(const id of ['dwarf','dragonkin','egypt']){const f=ns.systems.FactionSystem.FACTIONS[id];assert.equal(f.status,'TESTABLE');assert.equal(f.storyStatus,id==='egypt'?'FORESHADOW':'CONCEPT');assert.equal(f.units.length,4);assert.equal(f.buildings.length,4);assert.ok(f.units.every(unit=>ns.config.units[unit][id]));assert.ok(f.buildings.every(building=>ns.config.buildings[building][id]));}assert.match(ns.systems.HeroRoster.get('egypt').faction,/劇情伏筆/);});
test('三位新英雄均使用既有四階武器鍛造，三個軍團所有士兵都有相容軍械',()=>{const {ns}=load(),armory=Object.values(ns.systems.ArmorySystem.ITEMS);for(const heroType of ['dwarf','dragonkin','egypt']){const hero={classType:heroType,equipment:{spear:0}},weapons=ns.systems.EquipmentSystem.WEAPONS[heroType];assert.equal(weapons.length,4);assert.equal(ns.systems.EquipmentSystem.weapon(hero).id,weapons[0].id);assert.equal(ns.systems.EquipmentSystem.nextWeapon(hero).id,weapons[1].id);assert.ok(weapons.every(w=>w.atlas&&fs.existsSync(w.atlas)));}for(const f of ['dwarf','dragonkin','egypt'])for(const unit of ns.systems.FactionSystem.FACTIONS[f].units)assert.ok(armory.some(item=>(item.types||[]).includes(unit)),unit+' has no compatible armory item');});
test('埃及軍團四兵四塔都能從遊戲入口排隊並在合法位置建造',()=>{
  const {ns}=load(),g=game(ns);g.factions.choose('egypt');g.profession.choose('egypt');g.difficulty={allows:()=>true};g.art={preloadDeploy(){}};g.showCommands=()=>{};g.updateUi=()=>{};
  for(const kind of ['unit','building'])for(const type of g.factions.available(kind)){
    g.build.reset();g.economy.gold=100000;g.economy.lumber=100;
    assert.equal(g.queueDeploy(type,kind),true,type+' queue');
    let point=null;for(let y=90;y<ns.config.height-60&&!point;y+=20)for(let x=70;x<ns.config.width-50;x+=20)if(g.build.canPlaceAt(x,y,kind)){point={x,y};break;}
    assert.ok(point,type+' has a legal position');assert.equal(g.build.placeQueued(point.x,point.y,g.economy),true,type+' build');assert.equal(g.build.items[0].type,type);
  }
});
test('埃及女英雄的實戰圖是 4×4 非空透明動作圖，肖像與新圖集隨離線版本出貨',()=>{
  const {ns}=load(),portrait=ns.systems.HeroRoster.get('egypt').selectionArt,atlasPath=ns.systems.ImperialFactionArt.HERO.egypt,cache=fs.readFileSync('sw.js','utf8'),png=rgba(atlasPath);
  assert.equal(portrait,'assets/td/egypt/hero-selection-v1.png');assert.equal(atlasPath,'assets/td/egypt/hero-actions-v3.png');assert.ok(cache.includes('./'+portrait));assert.ok(cache.includes('./'+atlasPath));assert.equal(png.width,1254);assert.equal(png.height,1254);
  for(let row=0;row<4;row++)for(let col=0;col<4;col++){
    let body=0;const x0=Math.round(col*png.width/4),x1=Math.round((col+1)*png.width/4),y0=Math.round(row*png.height/4),y1=Math.round((row+1)*png.height/4);
    for(let y=y0;y<y1;y+=2)for(let x=x0;x<x1;x+=2)if(png.pixels[(y*png.width+x)*4+3]>80)body++;
    assert.ok(body>600,'hero action '+row+','+col+' is empty');
  }
});
test('共鳴塔只加速同族；三英雄圖集與埃及島選角圖加入離線清單',()=>{const {ns}=load(),dwarfForge=new ns.entities.Building('dwarfRuneForge',100,100),dwarfUnit=new ns.entities.CombatUnit('dwarfRifle',105,100),dragonRoost=new ns.entities.Building('dragonkinRoost',200,100),dragonUnit=new ns.entities.CombatUnit('dragonkinEmberwing',205,100),egyptAltar=new ns.entities.Building('egyptSunAltar',300,100),egyptUnit=new ns.entities.CombatUnit('egyptSunGuard',305,100),hero=new ns.entities.Hero(106,100);hero.chooseClass('dwarf');const game={hero,build:{items:[dwarfForge,dwarfUnit,dragonRoost,dragonUnit,egyptAltar,egyptUnit]},monsters:[],summons:[],projectiles:[],feedback:null,report:null};new ns.systems.BattleSynergySystem(game).update(.1);assert.equal(dwarfUnit.supportHaste,.18);assert.equal(hero.supportHaste,.18);assert.equal(dragonUnit.supportHaste,.18);assert.equal(egyptUnit.supportHaste,.16);const cache=fs.readFileSync('sw.js','utf8');for(const file of assets){assert.ok(cache.includes('./'+file),file);const {width,height,pixels}=rgba(file);assert.equal(width,height);assert.ok(width>=1000);assert.ok(pixels[3]<=5,file+' transparent corner');}for(const faction of ['dwarf','dragonkin','egypt']){const file=ns.systems.FactionSystem.FACTIONS[faction].selectionArt;assert.ok(fs.existsSync(file),file);assert.ok(cache.includes('./'+file),file);}});
test('三軍團塔使用四欄透明插畫圖集並隨離線版本下載',()=>{const cache=fs.readFileSync('sw.js','utf8');for(const file of towerAssets){assert.ok(cache.includes('./'+file),file);const {width,height,pixels}=rgba(file);assert.ok(width>=height*2.4,file+' must have four portrait tower columns');assert.ok(pixels[3]<=5,file+' outer corner must remain transparent');for(let col=0;col<4;col++){let filled=0;for(let y=Math.floor(height*.18);y<Math.floor(height*.82);y+=8)for(let x=Math.floor(col*width/4+width/4*.2);x<Math.floor((col+1)*width/4-width/4*.2);x+=8)if(pixels[(y*width+x)*4+3]>80)filled++;assert.ok(filled>12,file+' empty tower '+col);}}});
test('三英雄有選角肖像與技能圖，三軍團全部部署卡可在戰場選用',()=>{const {ns}=load(),cache=fs.readFileSync('sw.js','utf8'),markup=fs.readFileSync('td.html','utf8'),css=fs.readFileSync('td.css','utf8');for(const hero of ['dwarf','dragonkin','egypt']){const data=ns.systems.HeroRoster.get(hero);assert.match(data.selectionArt,/hero-selection-v1\.png$/);assert.match(data.skillArt,/skill-icons-v1\.png$/);assert.ok(fs.existsSync(data.selectionArt),data.selectionArt);assert.ok(fs.existsSync(data.skillArt),data.skillArt);assert.ok(cache.includes('./'+data.selectionArt),data.selectionArt);assert.ok(cache.includes('./'+data.skillArt),data.skillArt);assert.ok(css.includes('[data-hero="'+hero+'"]'),hero+' selection CSS');}assert.equal(ns.systems.HeroRoster.get('bull').selectionFocus,'50% 0%');for(const faction of ['dwarf','dragonkin','egypt'])for(const [kind,ids] of [['unit',ns.systems.FactionSystem.FACTIONS[faction].units],['building',ns.systems.FactionSystem.FACTIONS[faction].buildings]])for(const id of ids)assert.match(markup,new RegExp('data-build-kind="'+kind+'" data-build-type="'+id+'"'),id+' deployment card');});
