'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const files=['src/td/namespace.js','src/td/config.js','src/td/systems/TargetSelector.js','src/td/systems/ArmorySystem.js','src/td/systems/TowerEvolutionSystem.js','src/td/systems/TowerSkillSystem.js','src/td/entities/Summon.js','src/td/entities/Monster.js','src/td/entities/Projectile.js','src/td/entities/CombatUnit.js','src/td/entities/Building.js','src/td/systems/BuildSystem.js'];
function load(){const context=vm.createContext({console});context.globalThis=context;files.forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),context,{filename:file}));return context.TowerFrontier;}
function enemy(ns,type,x,index){const monster=new ns.entities.Monster(type,1);monster.x=x;monster.y=100;monster.index=index;return monster;}

test('所有塔在建造卡上有不同的用途說明',()=>{const ns=load(),roles=Object.values(ns.config.buildings).map(tower=>tower.role);assert.equal(roles.length,14);assert.ok(roles.every(Boolean));assert.equal(new Set(roles).size,roles.length);});

test('戰鼓只支援範圍內守軍，兩座不疊加，移除後效果消失',()=>{const ns=load(),build=new ns.systems.BuildSystem(),near=new ns.entities.CombatUnit('hunter',100,100),far=new ns.entities.CombatUnit('hunter',500,500),first=new ns.entities.Building('barracks',110,100),second=new ns.entities.Building('barracks',105,105);build.items.push(near,far,first,second);const base=near.config().interval;build.applyTowerSupport();assert.equal(near.supportHaste,.08);assert.equal(far.supportHaste,0);assert.ok(near.config().interval<base);first.level=3;first.chooseBranch('command');build.applyTowerSupport();assert.equal(near.supportHaste,.15);assert.ok(near.config().interval<base*.9);first.retired=true;build.applyTowerSupport();assert.equal(near.supportHaste,.08);second.retired=true;build.applyTowerSupport();assert.equal(near.supportHaste,0);assert.equal(near.config().interval,base);});

test('選取戰鼓堡時可看見獨立於攻擊射程的守軍支援範圍',()=>{const ns=load(),tower=new ns.entities.Building('barracks',100,100),arcs=[],ctx=new Proxy({arc(x,y,radius){arcs.push(radius);}}, {get(target,key){return target[key]||(()=>{});},set(target,key,value){target[key]=value;return true;}});tower.draw(ctx,true,{drawBuilding(){return true;}});assert.ok(arcs.includes(tower.config().range));assert.ok(arcs.includes(tower.config().allyHasteRadius));});

test('暫停時新建與出售戰鼓會立即更新守軍攻速，不需等待下一 frame',()=>{const ns=load(),build=new ns.systems.BuildSystem(),economy={gold:500,lumber:10,merit:0};build.queue('barracks','building');assert.equal(build.placeQueued(480,250,economy),true);const tower=build.selected;build.queue('hunter','unit');assert.equal(build.placeQueued(390,250,economy),true);const soldier=build.selected;assert.equal(soldier.supportHaste,.08);build.selected=tower;assert.equal(build.sell(economy),true);assert.equal(soldier.supportHaste,0);});

test('獅翼弩砲優先清除祭司旗手，普通弩塔仍按行進進度射擊',()=>{const ns=load(),front=enemy(ns,'grunt',128,8),healer=enemy(ns,'healer',165,3),commander=enemy(ns,'commander',175,4),monsters=[front,healer,commander];const ballista=new ns.entities.Building('ballista',100,100),arrow=new ns.entities.Building('arrow',100,100),ballistaShots=[],arrowShots=[];ballista.update(.3,monsters,ballistaShots,[]);arrow.update(.3,monsters,arrowShots,[]);assert.equal(ballistaShots[0].target,healer);assert.equal(ballistaShots[1].target,commander);assert.equal(arrowShots[0].target,front);});

test('召喚殿偏快速近距，墓園偏長駐遠程，沿用同一 Summon 實體',()=>{const ns=load(),target=enemy(ns,'grunt',120,2),crypt=new ns.entities.Building('crypt',100,100),graveyard=new ns.entities.Building('graveyard',100,100),cryptSummons=[],graveSummons=[];for(let i=0;i<8;i++){crypt.summonCooldown=0;graveyard.summonCooldown=0;ns.systems.TowerSkillSystem.fire(crypt,[target],[],cryptSummons);ns.systems.TowerSkillSystem.fire(graveyard,[target],[],graveSummons);}assert.equal(cryptSummons.length,2);assert.equal(graveSummons.length,3);assert.ok(cryptSummons[0].speed>graveSummons[0].speed);assert.ok(cryptSummons[0].range<graveSummons[0].range);assert.ok(cryptSummons[0].damage>graveSummons[0].damage);assert.ok(cryptSummons[0].time<graveSummons[0].time);graveyard.level=3;graveyard.chooseBranch('legion');assert.ok(graveyard.config().summonDuration>ns.config.buildings.graveyard.summonDuration);});

test('銀葉四塔分別提供強緩速、範圍遲滯、連鎖輸出與連鎖鋪控',()=>{const ns=load(),target=enemy(ns,'brute',120,2),fire=type=>{const tower=new ns.entities.Building(type,100,100),shots=[];tower.shotsFired=1;ns.systems.TowerSkillSystem.fire(tower,[target],shots,[]);return shots[0];};const frost=fire('frost'),grove=fire('grove'),storm=fire('storm'),moonwell=fire('moonwell');assert.ok(frost.slow<grove.slow);assert.ok(!frost.splash);assert.ok(grove.splash>0);assert.ok(storm.chain>1);assert.ok(!storm.slow);assert.ok(moonwell.chain>1);assert.ok(moonwell.slow<1);assert.ok(storm.damage>moonwell.damage);});
