'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {load,game,enemy,tick}=require('./helpers/td-runtime.cjs');
function canvas(){const calls=[];return{calls,ctx:new Proxy({}, {get(t,k){return t[k]||((...a)=>calls.push([k,...a]));},set(t,k,v){t[k]=v;return true;}})};}
test('VFX 01 chain lightning shows ordered, nonduplicate connections including weapon proc',()=>{const {ns}=load(),hero=new ns.entities.Hero(100,100);hero.chooseClass('hunter');hero.equipment.spear=2;const targets=[enemy(ns,130),enemy(ns,170),enemy(ns,210)],p=new ns.entities.Projectile(hero,targets[0],ns.systems.EquipmentSystem.projectileOptions(hero,{damage:1},()=>0));p.hit(targets);assert.equal(p.chainPoints.length,4);p.trail=.2;const c=canvas();p.draw(c.ctx);assert.ok(c.calls.filter(x=>x[0]==='lineTo').length>=15);assert.equal(p.weaponProc,'chain');});
test('VFX 02 cannon flies in arc then emits one radius-matched core/shock/smoke event',()=>{const {ns}=load(),g=game(ns),m=enemy(ns),p=new ns.entities.Projectile(g.hero,m,{damage:10,splash:54,style:'cannon',color:'#ff984f'});g.monsters=[m,enemy(ns,160)];p.hit(g.monsters,null,(m,d,c,s)=>g.onHit(m,d,c,s));const fx=g.feedback.items.filter(i=>i.type==='explosion');assert.equal(fx.length,1);assert.equal(fx[0].radius,54);const c=canvas();g.feedback.draw(c.ctx);assert.ok(c.calls.some(x=>x[0]==='arc'));const flight=new ns.entities.Projectile({x:20,y:100},m,{style:'cannon'});flight.x=80;flight.y=100;const trail=canvas();flight.draw(trail.ctx);assert.ok(trail.calls.find(x=>x[0]==='translate')[2]<100,'cannon sprite lifts above straight flight line');});
for(const [number,form,delay,radius]of [[3,'bomb',.18,44],[4,'heavyBomb',.65,100]])test('VFX 0'+number+' '+form+' materializes, arms visibly and explodes',()=>{const {ns}=load(),owner=new ns.entities.Building('bombWorkshop',100,100),s=new ns.entities.Summon(owner,{form,range:23,offsetX:0,splash:radius}),m=enemy(ns,105,110),shots=[];assert.ok(s.spawnTime>0);s.update(.55,[m],shots);s.update(.1,[m],shots);assert.ok(s.armedTime>0);assert.equal(shots.length,0);s.update(delay,[m],shots);assert.equal(s.active,false);assert.equal(shots[0].splash,radius);assert.equal(shots[0].style,'explosion');});
for(const [number,form,tags]of [[5,'crypt',['summon','undead']],[6,'bear',['summon','nature']]])test('VFX 0'+number+' '+form+' summons use distinct formation language before combat',()=>{const {ns}=load(),s=new ns.entities.Summon({x:100,y:100},{form,tags});const c=canvas();s.spawnTime=.3;s.draw(c.ctx,{drawSummon(){return true;}});assert.ok(c.calls.some(x=>x[0]==='ellipse'));assert.equal(c.ctx.strokeStyle,form==='bear'?'#97ed9e':'#b88bff');s.update(.1,[enemy(ns,110)],[]);assert.equal(s.cooldown,.2);});
test('VFX 07 soul collection moves from death to actual collector and caps bursts',()=>{const {ns}=load(),g=game(ns);g.build.items=[new ns.entities.Building('crypt',200,200)];for(let i=0;i<100;i++)g.synergy.onEnemyDeath(enemy(ns,100+i));const particles=g.feedback.items.filter(i=>i.type==='soul');assert.equal(g.synergy.souls,100);assert.ok(particles.length<=18);assert.equal(particles[0].toX,200);});
test('VFX 08 plague/DOT renders haze, curse rune and shock arcs, not just icon',()=>{const {ns}=load(),m=enemy(ns);m.plagueDot={};m.vulnerability={};m.shockTime=1;const c=canvas();ns.systems.CombatFeedbackSystem.drawStatus(c.ctx,m,.1);assert.ok(c.calls.some(x=>x[0]==='arc'));assert.ok(c.calls.filter(x=>x[0]==='lineTo').length>=4);});
test('VFX 09 frost uses shards; natural roots use vines',()=>{const {ns}=load(),m=enemy(ns);m.applySlow(.5,2);m.rootTime=1;const c=canvas();ns.systems.CombatFeedbackSystem.drawStatus(c.ctx,m,1);assert.ok(c.calls.filter(x=>x[0]==='lineTo').length>=6);assert.ok(c.calls.some(x=>x[0]==='quadraticCurveTo'));});
test('VFX 10 buff aura is a short local pulse, full range only on selection',()=>{const {ns}=load(),f=new ns.systems.CombatFeedbackSystem();f.aura({x:100,y:100},'#ffe39a');assert.equal(f.items[0].max,.6);const c=canvas();f.draw(c.ctx);assert.ok(c.calls.find(x=>x[0]==='ellipse')[3]<30);f.update(1);assert.equal(f.items.length,0);});
test('VFX 11 critical adds impact sparks and sprite micro-jitter without camera mutation',()=>{const {ns}=load(),f=new ns.systems.CombatFeedbackSystem(),m=enemy(ns);f.hit(m,50,true);assert.ok(m.criticalFlash>0);assert.ok(f.items.find(i=>i.type==='impact').heavy);assert.equal(m.x,140);});
test('VFX 12 mass deaths remain bounded, typed boss/magic death and clear',()=>{const {ns}=load(),f=new ns.systems.CombatFeedbackSystem();f.mobile=true;for(let i=0;i<300;i++)f.death(enemy(ns,100,100,i%2?'boss':'revenant'));assert.ok(f.items.length<=90);assert.ok(f.items.some(i=>i.variant==='boss'));assert.ok(f.items.some(i=>i.variant==='magic'));f.update(2);assert.equal(f.items.length,0);});
test('VFX 13 mixed battlefield effects draw safely and never alter damage outcomes',()=>{const {ns}=load(),g=game(ns);g.build.items=['crypt','plague','cannon','moonwell','bombWorkshop','grove'].map((type,i)=>new ns.entities.Building(type,100+i*10,100));g.monsters=Array.from({length:60},(_,i)=>enemy(ns,130+i%10*10,100+Math.floor(i/10)*10));for(let i=0;i<120;i++)tick(g,.05);const c=canvas();g.feedback.draw(c.ctx);g.synergy.draw(c.ctx);g.projectiles.forEach(p=>p.draw(c.ctx));assert.ok(g.monsters.some(m=>m.health<1000));assert.ok(g.feedback.items.length<=140);assert.ok(g.synergy.visuals.length<=100);});
