'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {load,game,enemy}=require('./helpers/td-runtime.cjs');
function canvas(){const calls=[];return {calls,ctx:new Proxy({},{get(t,k){return t[k]||((...args)=>calls.push([k,...args]));},set(t,k,v){t[k]=v;return true;}})};}
test('root visual grows once, survives refresh, retracts and restarts on renewed root',()=>{const {ns}=load(),m=enemy(ns),f=new ns.systems.CombatFeedbackSystem();f.updateRoots(.1,[m]);assert.equal(f.roots.size,0);m.rootTime=1;f.updateRoots(.1,[m]);m.rootTime=2;f.updateRoots(.2,[m]);assert.ok(f.roots.get(m).age>.29);m.rootTime=0;f.updateRoots(.1,[m]);assert.equal(f.roots.get(m).ending,true);m.rootTime=1;f.updateRoots(.1,[m]);assert.equal(f.roots.get(m).age,.1);m.rootTime=0;f.updateRoots(.4,[m]);assert.equal(f.roots.size,0);});
test('grove roots stop movement while VFX cannot mutate combat or extend root duration',()=>{const {ns}=load(),g=game(ns),m=enemy(ns);g.build.items=[new ns.entities.Building('grove',100,100)];g.monsters=[m];g.synergy.update(.01);assert.ok(m.rootTime>0);const x=m.x;m.update(.1);assert.equal(m.x,x);const before=JSON.stringify(m);g.feedback.updateRoots(.25,[m]);const c=canvas();g.feedback.drawRoots(c.ctx,'ground');g.feedback.drawRoots(c.ctx,'air');assert.equal(JSON.stringify(m),before);assert.ok(c.calls.some(x=>x[0]==='bezierCurveTo'));assert.ok(c.calls.some(x=>x[0]==='quadraticCurveTo'));g.synergy.update(2);g.feedback.updateRoots(.4,[m]);assert.equal(g.feedback.roots.size,0);});
test('death removal reset clean roots and drawing follows visual foot coordinates',()=>{const {ns}=load(),m=enemy(ns),f=new ns.systems.CombatFeedbackSystem();m.rootTime=2;m.visualPosition=()=>({x:300,y:400});f.updateRoots(.2,[m]);const c=canvas();f.drawRoots(c.ctx,'air');assert.ok(c.calls.some(x=>x[0]==='translate'&&x[1]===300&&x[2]===404));m.active=false;f.updateRoots(.1,[m]);assert.equal(f.roots.size,0);m.active=true;f.updateRoots(.1,[m]);f.updateRoots(.1,[]);assert.equal(f.roots.size,0);f.updateRoots(.1,[m]);f.reset();assert.equal(f.roots.size,0);});
test('crowds keep two solid vines but cap decorative leaves and particles on mobile',()=>{const {ns}=load(),f=new ns.systems.CombatFeedbackSystem();f.mobile=true;const monsters=Array.from({length:200},()=>{const m=enemy(ns);m.rootTime=2;return m;});f.updateRoots(.4,monsters);const c=canvas();f.drawRoots(c.ctx,'air');assert.equal(c.calls.filter(x=>x[0]==='arc').length,24*3);assert.equal(c.calls.filter(x=>x[0]==='bezierCurveTo').length,(24*3+176*2)*3);});
test('nature explosion draws radial thorn branches and leaves rather than a generic circle',()=>{const {ns}=load(),f=new ns.systems.CombatFeedbackSystem();f.explosion({x:10,y:20},52,'#9eea85','nature');f.update(.2);const c=canvas();f.draw(c.ctx);assert.ok(c.calls.filter(x=>x[0]==='quadraticCurveTo').length>=24);assert.equal(c.calls.filter(x=>x[0]==='createRadialGradient').length,0);});
