'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const root=path.resolve(__dirname,'..');
function load(){const context=vm.createContext({console,Math:Object.create(Math)});context.globalThis=context;['namespace.js','config.js','entities.js','AIStrategy.js','VersusMatch.js'].forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,'src/versus',file),'utf8'),context));return context.FrontierVersus;}
test('對戰採十二分鐘、雙路與左右各三分之一保護區',()=>{const ns=load(),m=new ns.systems.VersusMatch({random:()=>0});assert.equal(ns.config.duration,720);assert.deepEqual(Array.from(Object.keys(ns.config.lanes)),['upper','lower']);assert.equal(m.allowed('player',900),false);assert.equal(m.allowed('enemy',380),false);m.moveWorker('player',1200,300);m.moveWorker('enemy',0,300);assert.ok(Math.abs(m.workers.player.targetX-ns.config.width*2/3)<1e-9);assert.ok(Math.abs(m.workers.enemy.targetX-ns.config.width/3)<1e-9);});
test('雙方工人必須靠近才能建造且工人不會成為攻擊目標',()=>{const ns=load(),m=new ns.systems.VersusMatch({random:()=>0});assert.equal(m.build('player','tower',700,'upper'),false);m.workers.player.x=300;m.workers.player.y=303;assert.equal(m.build('player','tower',300,'upper'),true);const tower=m.structures.at(-1),enemyWorker=m.workers.enemy;enemyWorker.x=tower.x;enemyWorker.y=tower.y;tower.update(3,m);assert.equal(enemyWorker.hp,undefined);});
test('士兵相遇會交戰，防禦塔只攻擊士兵，士兵可破壞建築與主堡',()=>{const ns=load(),m=new ns.systems.VersusMatch({random:()=>0});m.structures=[];const a=new ns.entities.Unit('player','infantry','upper'),b=new ns.entities.Unit('enemy','infantry','upper');a.x=b.x=500;m.units=[a,b];m.update(.1);assert.ok(a.hp<a.maxHp||b.hp<b.maxHp);const target=new ns.entities.Structure('enemy','tower',520,'upper');m.structures=[target];m.units=[a];b.active=false;a.cooldown=0;a.x=500;const before=target.hp;a.update(.1,m);assert.ok(target.hp<before);m.bases.enemy.x=520;m.structures=[];a.cooldown=0;const baseBefore=m.bases.enemy.hp;a.update(.1,m);assert.ok(m.bases.enemy.hp<baseBefore);});
test('中央補給站由士兵占領並持續提供可逆轉的小額資源',()=>{const ns=load(),m=new ns.systems.VersusMatch({random:()=>0}),unit=new ns.entities.Unit('player','infantry','upper'),node=m.nodes[0];unit.x=node.x;unit.y=node.y;m.units=[unit];for(let i=0;i<51;i++)m.updateNodes(.1);assert.equal(node.owner,'player');const before=m.gold.player;for(let i=0;i<121;i++)m.updateNodes(.1);assert.ok(m.gold.player>=before+30);});
test('時間到依主堡生命與軍備價值判定，主堡歸零立即結束',()=>{const ns=load(),m=new ns.systems.VersusMatch({random:()=>0});m.ai.update=()=>{};m.elapsed=719.95;m.bases.player.hp=2500;m.bases.enemy.hp=2400;m.update(.1);assert.equal(m.result.reason,'time');assert.equal(m.result.winner,'player');const sudden=new ns.systems.VersusMatch({random:()=>0});sudden.ai.update=()=>{};sudden.bases.enemy.hp=0;sudden.update(.01);assert.equal(sudden.result.reason,'base');assert.equal(sudden.result.winner,'player');});
test('電腦具有五種可重抽的戰略人格，而非單純隨機蓋塔',()=>{const ns=load(),ids=new Set([0,.21,.41,.61,.81].map(value=>new ns.systems.AIStrategy(()=>value).id));assert.equal(ids.size,5);for(const profile of Object.values(ns.systems.AIStrategy.PROFILES)){assert.ok(profile.order.length>=4);assert.ok(profile.lane);}});
test('對戰頁面提供完整入口、工人模式、建造、路線、速度與回到遠征操作',()=>{const html=fs.readFileSync(path.join(root,'versus.html'),'utf8');for(const value of ['versus-game','versus-worker-mode','data-build="tower"','data-build="infantry"','data-build="ranger"','data-build="siege"','data-lane="upper"','data-lane="lower"','versus-speed','href="td.html"'])assert.ok(html.includes(value),value);});
test('對戰顯示層重用正式地圖、工匠、守軍、攻城與建築素材',()=>{const source=fs.readFileSync(path.join(root,'src/versus/main.js'),'utf8'),assets=['versus-battlefield-concept-v1.png','towers-atlas-v1.png','faction-structures-v1.png','faction-shield-v1.png','faction-musketeer-actions-v1.png','bomb-robot-actions-v2.png','blacksmith-actions-v2.png'];for(const name of assets){assert.ok(source.includes(name),name);assert.ok(fs.existsSync(path.join(root,'assets/td',name)),name);}});
test('建造先預覽再確認，己方建築可維修或拆除退款',()=>{const ns=load(),m=new ns.systems.VersusMatch({random:()=>0});m.workers.player.x=300;m.workers.player.y=303;const check=m.validateBuild('player','tower',300,'upper');assert.equal(check.ok,true);assert.equal(m.build('player','tower',300,'upper'),true);const tower=m.structures.at(-1);tower.hp=100;const before=m.gold.player;assert.equal(m.repair('player',tower),true);assert.ok(tower.hp>100);assert.ok(m.gold.player<before);const afterRepair=m.gold.player;assert.equal(m.demolish('player',tower),true);assert.equal(tower.active,false);assert.equal(m.gold.player,afterRepair+65);});
test('對戰介面具有塔防同層級的 HUD、快捷欄、建造抽屜、選取及選單',()=>{const html=fs.readFileSync(path.join(root,'versus.html'),'utf8');for(const id of ['battle-hud','quick-rail','versus-build-drawer','versus-placement','versus-selection','versus-repair','versus-demolish','versus-menu','versus-rules-panel'])assert.ok(html.includes(id),id);});
