(function(ns){
  'use strict';
  class Building{
    constructor(type,x,y){const cfg=ns.config.buildings[type];this.kills=0;this.shotsFired=0;this.skillPulse=0;this.summonCooldown=0;this.retired=false;this.kind='building';this.type=type;this.x=x;this.y=y;this.level=1;this.branch=null;this.cooldown=.2;this.totalSpent=cfg.cost;this.aim=-Math.PI/2;}
    config(){const cfg=ns.config.buildings[this.type];const power=(1+(this.level-1)*.34)*(1+(ns.systems.TowerSkillSystem.rank(this.kills)-1)*.08),scaled=Object.assign({},cfg,{damage:cfg.damage*power,range:cfg.range+(this.level-1)*8,interval:cfg.interval*Math.pow(.94,this.level-1),splash:cfg.splash?cfg.splash+(this.level-1)*5:0,allyHaste:cfg.allyHaste?Math.min(.12,cfg.allyHaste+(this.level-1)*.01):0,allyHasteRadius:cfg.allyHasteRadius?cfg.allyHasteRadius+(this.level-1)*4:0});return ns.systems.TowerEvolutionSystem?ns.systems.TowerEvolutionSystem.apply(this,scaled):scaled;}
    chooseBranch(id){return ns.systems.TowerEvolutionSystem&&ns.systems.TowerEvolutionSystem.choose(this,id);}
    registerKill(){if(!this.retired)this.kills+=1;}
    update(dt,monsters,projectiles,summons){this.skillPulse=Math.max(0,this.skillPulse-dt);this.summonCooldown=Math.max(0,this.summonCooldown-dt);this.cooldown-=dt;if(this.cooldown>0)return;const cfg=this.config();const targets=monsters.filter(function(monster){return monster.active&&ns.utils.distance(this,monster)<=cfg.range;},this).sort(function(a,b){const priority=cfg.priorityTargets;if(priority){const aPriority=priority.indexOf(a.type),bPriority=priority.indexOf(b.type);if((aPriority>=0)!==(bPriority>=0))return aPriority>=0?-1:1;if(aPriority>=0&&aPriority!==bPriority)return aPriority-bPriority;}return b.progress()-a.progress();});const target=targets[0];if(!target)return;this.aim=Math.atan2(target.y-this.y,target.x-this.x);this.shotsFired+=1;ns.systems.TowerSkillSystem.fire(this,targets,projectiles,summons);this.cooldown=cfg.interval;}
    upgradeCost(){if(this.level>=5)return null;const multiples=[2.8,4.2,6.2,8.4];return{gold:Math.round(ns.config.buildings[this.type].cost*multiples[this.level-1]/10)*10,merit:this.level===4?1:0};}
    upgrade(){const cost=this.upgradeCost();if(!cost)return null;this.level+=1;this.totalSpent+=cost.gold;return cost;}
    sellValue(){return Math.floor(this.totalSpent*.7);}
    draw(ctx,selected,art){const cfg=this.config();if(this.skillPulse>0){ctx.save();ctx.globalAlpha=this.skillPulse;ctx.strokeStyle=cfg.color;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(this.x,this.y+10,44,20,0,0,Math.PI*2);ctx.stroke();ctx.restore();}if(selected){ctx.save();ctx.globalAlpha=.13;ctx.fillStyle=cfg.color;ctx.beginPath();ctx.arc(this.x,this.y,cfg.range,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.9;ctx.strokeStyle=cfg.color;ctx.lineWidth=2;ctx.stroke();ctx.restore();if(cfg.allyHasteRadius){ctx.save();ctx.globalAlpha=.85;ctx.strokeStyle='#f4d684';ctx.lineWidth=1.5;ctx.setLineDash([6,5]);ctx.beginPath();ctx.arc(this.x,this.y,cfg.allyHasteRadius,0,Math.PI*2);ctx.stroke();ctx.restore();}}if(!(art&&art.drawBuilding(ctx,this.type,this.x,this.y,this.level,this.branch))){ctx.save();ctx.translate(this.x,this.y);ctx.fillStyle='#88704b';ctx.fillRect(-25,-36,50,52);ctx.restore();}if(this.branch){ctx.save();ctx.globalAlpha=.65;ctx.strokeStyle=cfg.color;ctx.shadowColor=cfg.color;ctx.shadowBlur=10;ctx.lineWidth=3;ctx.beginPath();ctx.arc(this.x,this.y-43,15,0,Math.PI*2);ctx.stroke();ctx.restore();}ctx.save();ctx.fillStyle='#fff4bd';ctx.strokeStyle='rgba(0,0,0,.85)';ctx.lineWidth=3;ctx.font='700 11px Segoe UI';ctx.textAlign='center';ctx.strokeText('L'+this.level,this.x,this.y+30);ctx.fillText('L'+this.level,this.x,this.y+30);ctx.restore();}
  }
  ns.entities.Building=Building;
})(globalThis.TowerFrontier);
