(function(ns){
  'use strict';
  class CombatUnit{
    constructor(type,x,y){const cfg=ns.config.units[type];this.kind='unit';this.type=type;this.x=x;this.y=y;this.level=1;this.cooldown=.18;this.totalSpent=cfg.cost;this.facing=-Math.PI/2;this.state='idle';this.frame=0;this.frameClock=0;this.attackTimer=0;this.commandPulse=0;this.order='idle';this.orderX=x;this.orderY=y;this.path=[];this.waypoint=0;this.active=true;this.maxHealth=cfg.health;this.health=this.maxHealth;this.displayHealth=this.health;this.hitFlash=0;this.deathTime=0;this.justDefeated=false;}
    config(){const cfg=ns.config.units[this.type];const power=1+(this.level-1)*.38;return Object.assign({},cfg,{maxHealth:Math.round(cfg.health*(1+(this.level-1)*.3)),armor:(cfg.armor||0)+Math.floor((this.level-1)/2),damage:cfg.damage*power,range:cfg.range+(this.level-1)*9,interval:cfg.interval*Math.pow(.92,this.level-1),shots:this.type==='hunter'&&this.level>=3?(this.level>=5?3:2):1,splash:cfg.splash?cfg.splash+(this.level-1)*5:0,bountyBonus:cfg.bountyBonus?cfg.bountyBonus+(this.level-1)*.08:0});}
    setState(state){if(this.state===state)return;this.state=state;this.frame=0;this.frameClock=0;}
    animate(dt){const fps={idle:2.8,walk:8,attack:10,hit:8,death:6}[this.state]||4;this.frameClock+=dt*fps;this.frame=Math.floor(this.frameClock)%4;}
    issueCommand(mode,destination,path){if(!this.active)return false;this.order=mode==='attackMove'?'attackMove':'move';this.orderX=destination.x;this.orderY=destination.y;this.path=(path||[]).slice();this.waypoint=0;this.commandPulse=.5;return true;}
    setTarget(x,y){return this.issueCommand('move',{x:ns.utils.clamp(x,28,ns.config.width-28),y:ns.utils.clamp(y,58,ns.config.height-28)},[{x:ns.utils.clamp(x,28,ns.config.width-28),y:ns.utils.clamp(y,58,ns.config.height-28)}]);}
    stop(){this.order='idle';this.orderX=this.x;this.orderY=this.y;this.path=[];this.waypoint=0;this.setState('idle');}
    holdPosition(){this.stop();this.order='hold';}
    isMoving(){return this.waypoint<this.path.length;}
    targetInRange(monsters,range){return monsters.filter(function(monster){return monster.active&&ns.utils.distance(this,monster)<=range;},this).sort(function(a,b){return b.progress()-a.progress();});}
    attack(targets,cfg,projectiles){const target=targets[0];if(!target)return false;this.facing=Math.atan2(target.y-this.y,target.x-this.x);if(this.cooldown<=0){targets.slice(0,cfg.shots).forEach(function(enemy){projectiles.push(new ns.entities.Projectile(this,enemy,{damage:cfg.damage,color:cfg.color,splash:cfg.splash,attackType:cfg.attackType,bountyBonus:cfg.bountyBonus,speed:this.type==='arcanist'?320:480}));},this);this.cooldown=cfg.interval;this.attackTimer=Math.min(.38,cfg.interval*.65);this.setState('attack');}else if(this.attackTimer<=0)this.setState('idle');return true;}
    followPath(dt,cfg){if(!this.isMoving())return false;const target=this.path[this.waypoint],dx=target.x-this.x,dy=target.y-this.y,distance=Math.hypot(dx,dy);if(distance<=3){this.x=target.x;this.y=target.y;this.waypoint+=1;if(!this.isMoving()){this.order='idle';return false;}return this.followPath(dt,cfg);}const move=Math.min(distance,cfg.speed*dt);this.x+=dx/distance*move;this.y+=dy/distance*move;this.facing=Math.atan2(dy,dx);if(move>=distance){this.x=target.x;this.y=target.y;this.waypoint+=1;if(!this.isMoving()){this.order='idle';this.setState('idle');return false;}}this.setState('walk');return true;}
    takeDamage(amount){if(!this.active)return 0;const before=this.health,damage=Math.max(1,Math.round(amount-(this.config().armor||0)));this.health=Math.max(0,this.health-damage);this.hitFlash=.16;if(this.health<=0){this.active=false;this.justDefeated=true;this.deathTime=0;this.path=[];this.pendingTarget=null;this.setState('death');}else this.setState('hit');return before-this.health;}
    update(dt,monsters,projectiles){if(!this.active){this.deathTime+=dt;this.animate(dt);return;}const cfg=this.config();this.displayHealth+=(this.health-this.displayHealth)*Math.min(1,dt*10);this.hitFlash=Math.max(0,this.hitFlash-dt);this.cooldown-=dt;this.attackTimer=Math.max(0,this.attackTimer-dt);this.commandPulse=Math.max(0,this.commandPulse-dt);const targets=this.targetInRange(monsters,cfg.range);if((this.order==='attackMove'||!this.isMoving())&&this.attack(targets,cfg,projectiles)){this.animate(dt);return;}if(this.followPath(dt,cfg)){this.animate(dt);return;}if(this.attack(targets,cfg,projectiles)){this.animate(dt);return;}this.setState('idle');this.animate(dt);}
    upgradeCost(){if(this.level>=5)return null;return{gold:45+this.level*40,merit:this.level>=3?this.level-2:0};}
    upgrade(){const cost=this.upgradeCost();if(!cost||!this.active)return null;const oldMax=this.maxHealth;this.level+=1;this.maxHealth=this.config().maxHealth;this.health=Math.min(this.maxHealth,this.health+(this.maxHealth-oldMax));this.displayHealth=this.health;this.totalSpent+=cost.gold;return cost;}
    sellValue(){return Math.floor(this.totalSpent*.7);}
    orderLabel(){return{move:'移動',attackMove:'攻擊移動',hold:'固守',idle:'待命'}[this.order]||'待命';}
    draw(ctx,selected,art){const cfg=this.config();ctx.save();if(!this.active)ctx.globalAlpha=Math.max(0,1-this.deathTime/.8);if(selected&&this.active){ctx.save();ctx.globalAlpha=.13;ctx.fillStyle=cfg.color;ctx.beginPath();ctx.arc(this.x,this.y,cfg.range,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.95;ctx.strokeStyle=this.order==='hold'?'#ffd65e':'#63ff72';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(this.x,this.y+18,25,10,0,0,Math.PI*2);ctx.stroke();if(this.path.length>this.waypoint){ctx.globalAlpha=.55;ctx.lineWidth=2;ctx.setLineDash([6,6]);ctx.beginPath();ctx.moveTo(this.x,this.y);this.path.slice(this.waypoint).forEach(function(point){ctx.lineTo(point.x,point.y);});ctx.stroke();ctx.setLineDash([]);}ctx.restore();}
      if(!(art&&art.drawCombatUnit(ctx,this))){ctx.save();ctx.translate(this.x,this.y);ctx.fillStyle=cfg.color;ctx.beginPath();ctx.arc(0,-12,15,0,Math.PI*2);ctx.fill();ctx.restore();}
      if(this.hitFlash>0&&this.active){ctx.save();ctx.globalAlpha=this.hitFlash*4;ctx.fillStyle='#fff0e2';ctx.beginPath();ctx.arc(this.x,this.y-14,20,0,Math.PI*2);ctx.fill();ctx.restore();}if(this.commandPulse>0){ctx.save();ctx.globalAlpha=this.commandPulse/.5;ctx.strokeStyle=this.order==='attackMove'?'#ffb04a':'#7dff85';ctx.lineWidth=2;ctx.beginPath();ctx.arc(this.orderX,this.orderY,9+(1-this.commandPulse/.5)*13,0,Math.PI*2);ctx.stroke();ctx.restore();}
      if(this.active){ctx.save();ctx.fillStyle='rgba(3,4,5,.82)';ctx.fillRect(this.x-22,this.y+18,44,4);ctx.fillStyle='#76272c';ctx.fillRect(this.x-22,this.y+18,44*(this.health/this.maxHealth),4);ctx.globalAlpha=.72;ctx.fillStyle='#69d98d';ctx.fillRect(this.x-22,this.y+18,44*(this.displayHealth/this.maxHealth),4);ctx.globalAlpha=1;ctx.fillStyle='#fff4bd';ctx.strokeStyle='rgba(0,0,0,.85)';ctx.lineWidth=3;ctx.font='700 11px Segoe UI';ctx.textAlign='center';ctx.strokeText('L'+this.level,this.x,this.y+34);ctx.fillText('L'+this.level,this.x,this.y+34);ctx.restore();}ctx.restore();}
  }
  ns.entities.CombatUnit=CombatUnit;
})(globalThis.TowerFrontier);
