(function(ns){
  'use strict';
  class CombatUnit{
    constructor(type,x,y){const cfg=ns.config.units[type];this.kind='unit';this.type=type;this.x=x;this.y=y;this.guardX=x;this.guardY=y;this.targetStrategy='front';this.lockedTarget=null;this.level=1;this.kills=0;this.strikes=0;this.gear={};this.supportHaste=0;this.cooldown=.18;this.totalSpent=cfg.cost;this.facing=-Math.PI/2;this.state='idle';this.frame=0;this.frameClock=0;this.attackTimer=0;this.attackVisualMode=null;this.commandPulse=0;this.order='idle';this.orderX=x;this.orderY=y;this.path=[];this.waypoint=0;this.active=true;this.maxHealth=cfg.health;this.health=this.maxHealth;this.displayHealth=this.health;this.hitFlash=0;}
    mastery(){return 1+[5,15,30,50].filter(value=>this.kills>=value).length;}
    registerKill(){this.kills+=1;if(this.type==='knight'&&this.level>=3)this.cooldown=Math.max(0,this.cooldown-.45);if(ns.config.units[this.type].berserk){this.berserkStacks=Math.min(5,(this.berserkStacks||0)+1);this.berserkTime=5;}}
    config(){const cfg=ns.config.units[this.type];const power=(1+(this.level-1)*.38)*(1+(this.mastery()-1)*.06),hunterShots=[0,2,2,3,4,4],frenzy=(this.berserkStacks||0)*.05+(this.tribalFrenzy>0?.28:0),tideCommand=this.nagaCommand>0?.18:0,scaled=Object.assign({},cfg,{maxHealth:Math.round(cfg.health*(1+(this.level-1)*.3)),armor:(cfg.armor||0)+Math.floor((this.level-1)/2),damage:cfg.damage*power*(1+(ns.systems.BattleSynergySystem?ns.systems.BattleSynergySystem.damageRate(this):(this.supportDamage||0)))*(1+(this.networkDamage||0)+tideCommand),range:cfg.range+(this.level-1)*9,interval:cfg.interval*Math.pow(.92,this.level-1)/(1+(this.supportHaste||0)+frenzy+(this.networkHaste||0)+(this.engineerHaste||0)+tideCommand),shots:this.type==='hunter'?hunterShots[this.level]:this.type==='skeleton'&&this.level>=3?(this.level>=5?3:2):1,splash:cfg.splash?cfg.splash+(this.level-1)*5:0,bountyBonus:cfg.bountyBonus?cfg.bountyBonus+(this.level-1)*.08:0});return ns.systems.ArmorySystem?ns.systems.ArmorySystem.apply(this,scaled):scaled;}
    evolutionName(){const names={hunter:['邊境見習獵手','王國獵手','獅徽斥候','金弦遊俠','王庭神射'],shield:['新兵盾衛','鐵壁衛士','王國重衛','獅心禁衛','不落壁壘'],musketeer:['火銃新兵','王國火槍手','霹靂射手','獅徽神銃','王城轟雷'],knight:['日耀侍從','日耀騎士','破陣騎士','王冠戰槌','曙光統領'],kingdomMage:['學院見習','王國魔法師','雷紋術士','皇家雷導師','風暴議長'],alchemist:['藥劑學徒','王國煉金術師','腐蝕調劑師','金焰煉成師','萬象賢者'],royalCommander:['王庭先鋒','皇家重裝統領','王冠戰將','獅心大元帥','邊境守護王'],arcanist:['月影見習','銀葉術士','星輝法師','月冠先知','森月賢者'],dragon:['翡翠古龍','月紋古龍','銀翼古龍','月蝕龍王','翡翠龍皇'],beastmaster:['林徑馭獸師','森靈馭獸師','月牙熊衛','古樹馴獸官','萬獸林王'],treant:['銀芽樹靈','銀葉守衛','月痕古木','永翠長老','世界根守護者'],dryad:['林間幼鹿','林裔獵手','翠枝追獵者','森語先鋒','永翠女獵王'],moonblade:['月刃見習','月刃哨兵','雙月舞者','銀輝刃主','新月劍聖'],rogue:['暗巷斥候','暮影刺客','夜幕行刑者','魂刃領主','無月終結者'],skeleton:['初醒骷髏','幽骨劍士','墓穴勇士','詛咒衛士','不朽劍魂'],golem:['殘魂石偶','魂鋼魔像','暮鐵破陣者','深淵巨像','永夜泰坦'],banshee:['幽語亡靈','暮影女妖','魂縛歌姬','冥界女王','永夜嚎歌'],boneRider:['骸骨騎手','幽騎骸將','冥騎衝鋒者','黑旌騎王','終焉死騎'],soulsteel:['殘魂鐵衛','深淵魂鋼魔像','噬魂破城者','冥鋼戰君','萬魂終焉體'],orc:['赤牙新兵','赤牙戰士','狂斧勇士','部族戰將','赤牙霸主'],goblinEngineer:['工坊學徒','地精工程師','渦輪技師','黃銅機巧師','超載總工'],goblinGunner:['火器新手','連發火器手','齒輪快槍手','熔芯砲兵','雷鳴連發大師'],goblinRiveter:['鉚釘學徒','鉚釘重射手','蒸汽穿甲手','鋼梁破城者','鐵雨總砲手'],goblinRecycler:['廢料跑腿','回收技師','循環工程師','能源修補師','永動回收宗師'],goblinMech:['試作機偶','重型工程機偶','鍋爐戰甲','攻城主機','超載泰坦'],frostWolf:['雪徑幼狼','冰原狼人','霜牙獵狼','凜冬狼王','永凍獵主'],frostBear:['霜原幼熊','冰原巨熊','碎冰戰熊','雪嶺霸主','凜冬巨獸王'],frostBird:['寒羽雛鳥','極凍鳥','冰晶掠翼','極光風暴鳥','永霜天穹使'],frostHunter:['雪徑新手','雪徑獵手','霜弦追獵者','白夜神射','冰原狩王'],frostShaman:['骨鈴學徒','霜骨薩滿','凜風祭司','冰魂先知','永冬大薩滿'],frostMammoth:['凍原幼獸','冰脊長毛巨獸','霜岳踐踏者','極地戰象王','冰河滅城獸'],nagaTideguard:['潮門衛兵','潮汐衛士','珊瑚戟衛','深潮護衛長','萬潮禁軍'],nagaShellbreaker:['鹽甲幼衛','鹽甲破殼者','裂殼戰士','深淵破城者','海皇碎甲衛'],nagaDeepWargod:['潮刃侍從','深潮戰神','漩渦戰君','海溝毀滅者','萬潮戰神王'],nagaMantaRaider:['翼潮斥候','魔鬼魚翼襲者','雷鰭掠擊手','風暴翼衛','深海天穹獵王'],nagaVenomStalker:['毒沼潛徒','毒沼潛獵者','珊瑚毒刃','深潭蝕魂者','萬毒潮影']},base=(names[this.type]||[])[this.level-1]||this.config().name;return ns.systems.ArmorySystem?ns.systems.ArmorySystem.title(this,base):base;}
    setState(state){if(this.state===state)return;this.state=state;this.frame=0;this.frameClock=0;}
    animate(dt){const fps={idle:2.8,walk:8,attack:10,hit:8,death:6}[this.state]||4;this.frameClock+=dt*fps;if(this.state==='attack'&&this.attackVisualMode==='windup')this.frame=this.cooldown<=.08?1:0;else if(this.state==='attack'&&this.attackVisualMode==='release')this.frame=this.attackTimer>.16?2:3;else this.frame=Math.floor(this.frameClock)%4;}
    setTargetStrategy(strategy){if(!ns.systems.TargetSelector.supports(strategy))return false;this.targetStrategy=strategy;this.lockedTarget=null;return true;}
    setGuardPoint(x,y){this.guardX=x;this.guardY=y;this.lockedTarget=null;}
    // Built soldiers are emplacements: their deployment coordinate is permanent.
    // Keep the legacy command seam inert so old callers cannot move them.
    issueCommand(){return false;}
    setTarget(){return false;}
    stop(){this.order='idle';this.orderX=this.x;this.orderY=this.y;this.path=[];this.waypoint=0;this.setState('idle');return true;}
    holdPosition(){return this.stop();}
    isMoving(){return false;}
    targetInRange(monsters,range){return ns.systems.TargetSelector.rank(this,monsters,this.targetStrategy,monster=>ns.utils.distance(this,monster)<=range);}
    attack(target,cfg,projectiles,monsters){if(!target||ns.utils.distance(this,target)>cfg.range)return false;this.facing=Math.atan2(target.y-this.y,target.x-this.x);if(this.cooldown<=0){this.strikes+=1;const empowered=this.strikes%4===0,heavyBonus=(this.type==='orc'&&empowered)?1.45:(this.type==='golem'&&empowered)?1.55:1,bonusSplash=(this.type==='orc'&&empowered)?18+this.mastery()*5:(this.type==='golem'&&empowered)?16+this.mastery()*4:(this.type==='shield'&&empowered)?44:0,stunStrike=(this.type==='shield'||this.type==='halberdier')&&empowered,options={damage:cfg.damage*heavyBonus,color:cfg.color,splash:(cfg.splash||0)+bonusSplash,slow:stunStrike?.58:cfg.slow,slowTime:stunStrike?1.05:cfg.slowTime,attackType:cfg.attackType,bonusVsHeavy:cfg.bonusVsHeavy,bountyBonus:cfg.bountyBonus,chain:cfg.chain,chainRange:cfg.chainRange||92,speed:cfg.projectileSpeed||(this.type==='arcanist'||this.type==='dragon'||this.type==='treant'?320:(cfg.range<65?900:480)),style:cfg.style||(cfg.chain?'spirit':this.type==='dragon'?'flame':this.type==='treant'?'nature':this.type==='skeleton'||this.type==='golem'?'spirit':undefined)};if(ns.systems.BattleSynergySystem)ns.systems.BattleSynergySystem.prepare(this,target,cfg,options);const count=Math.max(1,cfg.shots||1),others=count>1?this.targetInRange(monsters,cfg.range).filter(enemy=>enemy!==target):[];const victims=[target].concat(others).slice(0,count);if(cfg.frostland&&ns.systems.FrostlandAnimation)ns.systems.FrostlandAnimation.queue(this,victims,options);else if(this.type.startsWith('goblin')&&ns.systems.GoblinAnimation)ns.systems.GoblinAnimation.queue(this,victims,options);else victims.forEach(function(enemy){projectiles.push(new ns.entities.Projectile(this,enemy,options));},this);this.cooldown=cfg.interval;this.attackTimer=Math.min(.38,cfg.interval*.65);this.setState('attack');this.attackVisualMode='release';}else if(this.attackTimer<=0){if(this.cooldown<=Math.min(.18,cfg.interval*.28)){this.setState('attack');this.attackVisualMode='windup';}else{this.setState('idle');this.attackVisualMode=null;}}return true;}
    finishPath(){this.stop();}
    followPath(){return false;}
    validTarget(target,monsters,range){return ns.systems.TargetSelector.valid(target)&&monsters.includes(target)&&ns.utils.distance(this,target)<=range;}
    acquireTarget(monsters,cfg){if(cfg.frostland&&(cfg.shatter||cfg.frozenBonus>1.5)&&this.targetStrategy==='front'){const frozen=monsters.filter(m=>this.validTarget(m,monsters,cfg.range)&&ns.systems.FrostStatusSystem.isWindow(m)).sort((a,b)=>b.progress()-a.progress());if(frozen.length)return frozen[0];}if(cfg.priorityTargets){const preferred=monsters.filter(m=>this.validTarget(m,monsters,cfg.range)).sort((a,b)=>Number(b.elite||b.type==='boss')-Number(a.elite||a.type==='boss')||(cfg.priorityTargets.includes(b.type)?1:0)-(cfg.priorityTargets.includes(a.type)?1:0)||b.progress()-a.progress());return preferred[0]||null;}return ns.systems.TargetSelector.select(this,monsters,this.targetStrategy,target=>ns.utils.distance(this,target)<=cfg.range);}
    takeDamage(){return 0;}
    update(dt,monsters,projectiles,context){
      if(ns.systems.FrostlandAnimation)ns.systems.FrostlandAnimation.update(this,dt,monsters,projectiles);
      if(ns.systems.GoblinAnimation)ns.systems.GoblinAnimation.update(this,dt,monsters,projectiles);
      if(!this.active)return;
      this.berserkTime=Math.max(0,(this.berserkTime||0)-dt);if(!this.berserkTime)this.berserkStacks=0;this.tribalFrenzy=Math.max(0,(this.tribalFrenzy||0)-dt);this.nagaCommand=Math.max(0,(this.nagaCommand||0)-dt);const cfg=this.config();if(cfg.supportOnly||this.networkCooling||cfg.networkCost>=2&&!this.networkPowered){this.setState('idle');this.animate(dt);return;}this.cooldown-=dt;this.attackTimer=Math.max(0,this.attackTimer-dt);this.commandPulse=Math.max(0,this.commandPulse-dt);
      if(this.lockedTarget&&!this.validTarget(this.lockedTarget,monsters,cfg.range))this.lockedTarget=null;
      if(!this.lockedTarget)this.lockedTarget=this.acquireTarget(monsters,cfg);
      const target=this.lockedTarget;
      if(target){this.attack(target,cfg,projectiles,monsters);this.animate(dt);return;}
      this.setState('idle');this.attackVisualMode=null;
      this.animate(dt);
    }
    upgradeCost(){if(this.level>=5)return null;const cfg=ns.config.units[this.type],multiples=this.type==='musketeer'?[.8,1.3,1.7,2.2]:[1,1.3,1.7,2.2];return{gold:Math.round(cfg.cost*multiples[this.level-1]/5)*5,merit:this.level>=3?this.level-2:0};}
    upgrade(){const cost=this.upgradeCost();if(!cost||!this.active)return null;const oldMax=this.maxHealth;this.level+=1;this.maxHealth=this.config().maxHealth;this.health=Math.min(this.maxHealth,this.health+(this.maxHealth-oldMax));this.displayHealth=this.health;this.totalSpent+=cost.gold;return cost;}
    sellValue(){return Math.floor(this.totalSpent*.7);}
    orderLabel(){return'永久定點';}
    draw(ctx,selected,art){if(ns.systems.BattleSynergySystem)ns.systems.BattleSynergySystem.drawFlag(ctx,this);const cfg=this.config();ctx.save();if(selected&&this.active){ctx.save();ctx.globalAlpha=.13;ctx.fillStyle=cfg.color;ctx.beginPath();ctx.arc(this.x,this.y,cfg.range,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.95;ctx.strokeStyle='#63ff72';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(this.x,this.y+18,25,10,0,0,Math.PI*2);ctx.stroke();ctx.restore();}
      const e=this.excursion,t=e&&e.time>0?Math.sin((1-e.time/e.max)*Math.PI):0,visual=t?Object.assign(Object.create(Object.getPrototypeOf(this)),this,{x:this.x+(e.x-this.x)*t,y:this.y+(e.y-this.y)*t-(e.fly?Math.sin(t*Math.PI)*22:0),state:'attack'}):this;if(t){ctx.save();ctx.globalAlpha=.35;ctx.strokeStyle=cfg.color;ctx.lineWidth=e.fly?5:9;ctx.beginPath();ctx.moveTo(this.x,this.y);ctx.lineTo(visual.x,visual.y);ctx.stroke();ctx.restore();}if(!(art&&art.drawCombatUnit(ctx,visual))){ctx.save();ctx.translate(this.x,this.y);ctx.fillStyle=cfg.color;ctx.beginPath();ctx.arc(0,-12,15,0,Math.PI*2);ctx.fill();ctx.restore();}
      if(this.active&&this.supportHaste>0){ctx.save();ctx.globalAlpha=.72;ctx.strokeStyle='#f4d684';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(this.x,this.y+13,19,6,0,0,Math.PI*2);ctx.stroke();ctx.restore();}
      if(this.active&&this.engineerBoost>0){ctx.save();ctx.globalAlpha=.45+.2*Math.sin(this.frameClock*12);ctx.strokeStyle='#b8ffe7';ctx.lineWidth=2.5;ctx.setLineDash([4,3]);ctx.beginPath();ctx.ellipse(this.x,this.y+12,23,8,0,0,Math.PI*2);ctx.stroke();ctx.restore();}
      if(this.active&&this.nagaCommand>0){ctx.save();ctx.globalAlpha=.38+.24*Math.sin(this.frameClock*10);ctx.strokeStyle='#67f5ee';ctx.shadowColor='#55d3d0';ctx.shadowBlur=8;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(this.x,this.y+13,25,8,0,0,Math.PI*2);ctx.stroke();ctx.restore();}
      if(this.active){ctx.save();ctx.fillStyle='#fff4bd';ctx.strokeStyle='rgba(0,0,0,.85)';ctx.lineWidth=3;ctx.font='700 11px Segoe UI';ctx.textAlign='center';ctx.strokeText('L'+this.level+' · 技'+this.mastery(),this.x,this.y+34);ctx.fillText('L'+this.level+' · 技'+this.mastery(),this.x,this.y+34);ctx.restore();}ctx.restore();}
  }
  // 王國長戟兵沿用早期配置，但也必須有完整、可讀的五階進化線。
  const baseEvolutionName=CombatUnit.prototype.evolutionName;
  CombatUnit.prototype.evolutionName=function(){
   if(this.type!=='halberdier')return baseEvolutionName.call(this);
   const base=['王國槍兵','獅徽長戟衛','鐵陣衛士','獅心戟將','不破長城'][this.level-1];
   return ns.systems.ArmorySystem?ns.systems.ArmorySystem.title(this,base):base;
  };
  const evolutionBase=CombatUnit.prototype.evolutionName,wildEvolutions={centaur:['草原斥候','疾風獵手','裂蹄神射','逐日獵王','蒼穹追獵者'],boarRider:['幼豬騎手','赤鬃騎兵','碎陣衝鋒者','獠牙戰將','荒原破軍'],minotaur:['角鬥奴兵','巨角戰士','迷宮震地者','蠻角霸主','大地戰神'],shaman:['骨杖學徒','祖靈祭司','雷骨巫師','萬靈先知','荒野大薩滿']};
  CombatUnit.prototype.evolutionName=function(){const names=wildEvolutions[this.type];if(!names)return evolutionBase.call(this);const base=names[this.level-1]||this.config().name;return ns.systems.ArmorySystem?ns.systems.ArmorySystem.title(this,base):base;};
  ns.entities.CombatUnit=CombatUnit;
})(globalThis.TowerFrontier);
