(function(ns){
  'use strict';
  class Hero{
    constructor(x,y){const cfg=ns.config.hero;Object.assign(this,{x:x,y:y,spawnX:x,spawnY:y,targetX:x,targetY:y,health:cfg.maxHealth,maxHealth:cfg.maxHealth,displayHealth:cfg.maxHealth,level:1,xp:0,gear:{},cooldown:0,novaCooldown:0,facing:0,active:true,state:'idle',frame:0,animationTime:0,attackTimer:0,castTimer:0,pendingTarget:null,moveOrder:false,selected:false,classType:'arcanist',fields:[],equipment:{spear:0,rune:0,charm:0},skillCooldowns:{thunder:0,summon:0,ultimate:0},evolution:{rank:0,stones:0,healthFloor:0,trialStage:0},hitFlash:0,invulnerable:0,respawnTimer:0,deathTime:0,justDowned:false,justRevived:false});}
    chooseClass(type){if(!ns.systems.HeroRoster.CLASSES[type])return false;this.classType=type;return true;}
    xpForNext(){return this.level>=15?null:40+this.level*this.level*12;}
    xpProgress(){const next=this.xpForNext();return{level:this.level,xp:this.xp,next:next,ratio:next?Math.min(1,this.xp/next):1};}
    healthAtLevel(){const floor=this.evolution&&this.evolution.healthFloor||0;return Math.max(ns.config.hero.maxHealth+(this.level-1)*10,floor);}
    gainExperience(amount){let gained=Math.max(0,Math.round(amount||0)),levels=0;this.xp+=gained;let next=this.xpForNext();while(next!==null&&this.xp>=next){this.xp-=next;this.level+=1;levels+=1;const before=this.maxHealth;this.maxHealth=this.healthAtLevel();this.health=Math.min(this.maxHealth,this.health+(this.maxHealth-before)+8);this.displayHealth=this.health;next=this.xpForNext();}return{gained:gained,levels:levels,level:this.level};}
    skillPower(){const evolution=ns.systems.HeroEvolutionSystem?ns.systems.HeroEvolutionSystem.powerMultiplier(this):1;return(1+this.equipment.spear*.2)*(1+(this.level-1)*.08)*evolution;}
    combatConfig(){const base=ns.config.hero,power=this.skillPower(),levelSpeed=Math.pow(.985,this.level-1),scaled=Object.assign({},base,ns.systems.HeroRoster.get(this.classType),{damage:ns.systems.HeroRoster.get(this.classType).damage*power*(1+(this.synergy?this.synergy.flagRate(this):0)),interval:ns.systems.HeroRoster.get(this.classType).interval*levelSpeed/(1+(this.supportHaste||0)),novaDamage:base.novaDamage*power,novaCooldown:base.novaCooldown*(1-this.equipment.rune*.1)});if(this.classType==='goblin'&&this.goblinOverclock>0)scaled.interval*=.7;return ns.systems.ArmorySystem?ns.systems.ArmorySystem.apply(this,scaled):scaled;}
    beginCast(){this.castTimer=.56;this.attackTimer=0;this.pendingTarget=null;this.setState('cast');}
    castThunder(monsters,onKill,projectiles,onHit){if(!this.active)return false;if(this.classType!=='arcanist')return ns.systems.HeroRoster.cast(this,1,monsters,onKill,onHit);if(this.skillCooldowns.thunder>0)return false;const targets=monsters.filter(function(m){return m.active&&ns.utils.distance(this,m)<=220;},this).sort(function(a,b){return b.progress()-a.progress();}).slice(0,4);if(!targets.length)return false;const shot=new ns.entities.Projectile(this,targets[0],{damage:55*this.skillPower(),color:ns.systems.EquipmentSystem.effectColor(this,'#b9eaff'),attackType:'magic',style:'lightning',chain:4,chainRange:110});shot.hit(monsters,onKill,onHit);if(projectiles)projectiles.push(shot);ns.systems.HeroSkillVFX.emit(this,'lightning',{duration:.35});this.skillCooldowns.thunder=12*(1-this.equipment.rune*.1);this.beginCast();return true;}
    castSummon(summons){if(this.classType==='frostland')return ns.systems.FrostlandHero.hunt(this);if(this.classType==='chief'||!this.active||this.skillCooldowns.summon>0)return false;if(this.classType==='naga'){const units=this.synergy?.game?.build?.combatUnits?.().filter(unit=>unit.active&&unit.type.startsWith('naga')&&ns.utils.distance(this,unit)<=220)||[];if(!units.length)return false;units.forEach(unit=>{unit.nagaCommand=Math.max(unit.nagaCommand||0,5);unit.commandPulse=5;});ns.systems.HeroSkillVFX.emit(this,'naga-command',{radius:220,targets:units.map(unit=>({x:unit.x,y:unit.y})),duration:.8});this.skillCooldowns.summon=22*(1-this.equipment.rune*.1);this.beginCast();return true;}if(this.classType==='goblin'){if(summons.some(unit=>unit.active&&unit.owner===this&&unit.form==='goblin'))return false;summons.push(new ns.entities.Summon(this,{offsetX:28,duration:12+this.equipment.charm*2,damage:21*this.skillPower(),level:Math.min(5,Math.ceil(this.level/2)),color:'#88e7d8',form:'goblin',range:145,leash:260,speed:105,tags:['summon','mechanical','goblin']}));ns.systems.HeroSkillVFX.emit(this,'goblin-deploy',{radius:38,duration:.8});this.skillCooldowns.summon=22*(1-this.equipment.rune*.1);this.beginCast();return true;}const cap=2+(this.equipment.charm>=3?1:0),existing=summons.filter(function(unit){return unit.active&&unit.owner===this;},this).length;if(existing>=cap)return false;for(let i=existing;i<cap;i++)summons.push(new ns.entities.Summon(this,{offsetX:(i-(cap-1)/2)*42,duration:12+this.equipment.charm*3,damage:14*(1+this.equipment.charm*.2)*(1+(this.level-1)*.08),level:Math.min(5,Math.ceil(this.level/2)),color:ns.systems.HeroRoster.get(this.classType).color,form:this.classType,range:this.classType==='arcanist'?120:45,speed:this.classType==='hunter'?160:140}));this.skillCooldowns.summon=22*(1-this.equipment.rune*.1);this.beginCast();return true;}
    castShockwave(waves){if(this.classType!=='chief'||!this.active||this.skillCooldowns.summon>0)return false;waves.push(new ns.systems.ChiefShockwave(this));ns.systems.HeroSkillVFX.emit(this,'chief-shockwave-cast',{duration:.34,radius:58});this.skillCooldowns.summon=22*(1-this.equipment.rune*.1);this.beginCast();return true;}
    setTarget(x,y,speedScale=1){
      if(!this.active)return false;
      this.targetX=ns.utils.clamp(x,25,ns.config.width-25);this.targetY=ns.utils.clamp(y,55,ns.config.height-25);this.moveSpeedScale=Number.isFinite(speedScale)?ns.utils.clamp(speedScale,0,1):1;
      // A player move is an explicit disengage order.  Do not make the player
      // wait through a spear swing or spell recovery before escaping a pack.
      this.moveOrder=Math.hypot(this.targetX-this.x,this.targetY-this.y)>2;
      this.pendingTarget=null;this.attackTimer=0;this.castTimer=0;
      return true;
    }
    takeDamage(amount){if(!this.active||this.invulnerable>0)return 0;const before=this.health,damage=Math.max(1,Math.round(amount));this.health=Math.max(0,this.health-damage);this.hitFlash=.16;if(this.health<=0){this.active=false;this.selected=false;this.state='death';this.respawnTimer=ns.config.hero.respawnTime;this.deathTime=0;this.pendingTarget=null;this.attackTimer=0;this.castTimer=0;this.justDowned=true;}return before-this.health;}
    updateDowned(dt){this.deathTime+=dt;this.respawnTimer=Math.max(0,this.respawnTimer-dt);this.displayHealth+=(this.health-this.displayHealth)*Math.min(1,dt*10);if(this.respawnTimer>0)return false;this.active=true;this.health=Math.ceil(this.maxHealth*ns.config.hero.respawnHealth);this.displayHealth=this.health;this.x=this.spawnX;this.y=this.spawnY;this.targetX=this.x;this.targetY=this.y;this.invulnerable=ns.config.hero.invulnerability;this.state='idle';this.animationTime=0;this.justRevived=true;return true;}
    setState(state){if(this.state!==state){this.state=state;this.animationTime=0;}}
    update(dt,monsters,projectiles){
      this.justDowned=false;this.justRevived=false;if(!this.active){this.updateDowned(dt);return;}const cfg=this.combatConfig();
      this.displayHealth+=(this.health-this.displayHealth)*Math.min(1,dt*10);this.hitFlash=Math.max(0,this.hitFlash-dt);this.invulnerable=Math.max(0,this.invulnerable-dt);
      this.goblinOverclock=Math.max(0,(this.goblinOverclock||0)-dt);
      if(ns.systems.HeroEvolutionSystem)ns.systems.HeroEvolutionSystem.update(this,dt);
      Object.keys(this.skillCooldowns).forEach(function(id){this.skillCooldowns[id]=Math.max(0,this.skillCooldowns[id]-dt);},this);
      this.cooldown=Math.max(0,this.cooldown-dt);this.novaCooldown=Math.max(0,this.novaCooldown-dt);
      this.castTimer=Math.max(0,this.castTimer-dt);
      if(this.attackTimer>0){const before=this.attackTimer;this.attackTimer=Math.max(0,this.attackTimer-dt);if(before>.18&&this.attackTimer<=.18){const target=this.pendingTarget;if(target&&target.active&&ns.utils.distance(this,target)<=cfg.range+20){const targets=monsters.filter(function(monster){return monster.active&&ns.utils.distance(this,monster)<=cfg.range+20;},this).sort(function(a,b){return b.progress()-a.progress();}).slice(0,Math.max(1,cfg.shots||1));targets.forEach(function(enemy){const options=ns.systems.EquipmentSystem.projectileOptions(this,{damage:cfg.damage,color:ns.systems.EquipmentSystem.effectColor(this,cfg.color),attackType:cfg.attackType,style:this.classType==='naga'?'tidebolt':undefined,speed:520,chain:cfg.chain,chainRange:105,bountyBonus:cfg.bountyBonus});if(ns.systems.FrostStatusSystem)ns.systems.FrostStatusSystem.prepare(this,cfg,options);projectiles.push(new ns.entities.Projectile(this,enemy,options));},this);}this.pendingTarget=null;}}
      const dx=this.targetX-this.x,dy=this.targetY-this.y,distance=Math.hypot(dx,dy),movingByOrder=distance>2;
      if(this.castTimer>0)this.setState('cast');
      else if(this.attackTimer>0)this.setState('attack');
      else if(movingByOrder){const move=Math.min(distance,cfg.speed*dt*(this.moveSpeedScale??1));this.x+=dx/distance*move;this.y+=dy/distance*move;this.facing=Math.atan2(dy,dx);this.setState('walk');}
      else this.setState('idle');
      if(this.moveOrder&&Math.hypot(this.targetX-this.x,this.targetY-this.y)<=2)this.moveOrder=false;
      if(!movingByOrder&&this.cooldown<=0&&this.castTimer<=0&&this.attackTimer<=0){const target=monsters.filter(function(m){return m.active&&ns.utils.distance(this,m)<=cfg.range;},this).sort(function(a,b){return b.progress()-a.progress();})[0];if(target){this.facing=Math.atan2(target.y-this.y,target.x-this.x);this.pendingTarget=target;this.attackTimer=.36;this.cooldown=cfg.interval;this.setState('attack');}}
      this.animationTime+=dt;
      // 賽洛的原始圖集第 4 格是倒地收勢，不可當作施法循環的最後一格；
      // 待機也只在兩個呼吸姿勢間切換，避免長兵器每 1/3 秒跳位。
      if(this.classType==='naga'){
        if(this.state==='cast')this.frame=Math.min(2,Math.floor(this.animationTime/.16));
        else if(this.state==='attack')this.frame=Math.min(3,Math.floor(this.animationTime/.1));
        else if(this.state==='walk')this.frame=Math.floor(this.animationTime*6)%4;
        else this.frame=Math.floor(this.animationTime*1.25)%2;
      }else this.frame=(this.state==='attack'||this.state==='cast')?Math.min(3,Math.floor(this.animationTime/(this.state==='cast'?.14:.09))):Math.floor(this.animationTime*(this.state==='walk'?9:3))%4;
    }
    castNova(monsters,onKill,onHit){if(!this.active)return false;if(this.classType!=='arcanist')return ns.systems.HeroRoster.cast(this,0,monsters,onKill,onHit);const cfg=this.combatConfig();if(this.novaCooldown>0)return false;const targets=monsters.filter(function(monster){return monster.active&&ns.utils.distance(this,monster)<=cfg.novaRange;},this);if(!targets.length)return false;targets.forEach(function(monster){monster.applySlow(.38,2.4);const before=typeof monster.effectiveHealth==='function'?monster.effectiveHealth():monster.health,killed=monster.takeDamage(cfg.novaDamage),after=typeof monster.effectiveHealth==='function'?monster.effectiveHealth():monster.health;if(onHit)onHit(monster,before-after,false,{color:'#70e7ff',owner:this});if(killed&&onKill)onKill(monster);},this);ns.systems.HeroSkillVFX.emit(this,'frost',{radius:cfg.novaRange,duration:.65});this.novaCooldown=cfg.novaCooldown;this.castTimer=.56;this.attackTimer=0;this.pendingTarget=null;this.setState('cast');return true;}
    draw(ctx,art){
      if(!this.active){ctx.save();ctx.globalAlpha=.78;ctx.fillStyle='rgba(9,12,13,.82)';ctx.strokeStyle='#9bb9bd';ctx.lineWidth=2;ctx.beginPath();ctx.arc(this.x,this.y,24,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#e5f4ef';ctx.font='800 15px Segoe UI';ctx.textAlign='center';ctx.fillText(this.respawnTimer.toFixed(1)+'s',this.x,this.y+5);ctx.font='700 10px Segoe UI';ctx.fillText('復活中',this.x,this.y+38);ctx.restore();return;}
      if(ns.systems.BattleSynergySystem)ns.systems.BattleSynergySystem.drawFlag(ctx,this);
      ctx.save();ctx.strokeStyle=this.invulnerable>0?'#ffffff':this.selected?'#95ffe0':'#cbb66b';ctx.lineWidth=this.selected?3:1;ctx.globalAlpha=this.invulnerable>0?.55+Math.sin(this.invulnerable*14)*.25:1;ctx.beginPath();ctx.ellipse(this.x,this.y+15,28,11,0,0,Math.PI*2);ctx.stroke();ctx.restore();
      const evolutionRank=ns.systems.HeroEvolutionSystem?ns.systems.HeroEvolutionSystem.rank(this):0;if(evolutionRank){const color=evolutionRank===2?'#ffe2a0':ns.systems.HeroRoster.get(this.classType).color;ctx.save();ctx.globalAlpha=evolutionRank===2?.72:.52;ctx.strokeStyle=color;ctx.shadowColor=color;ctx.shadowBlur=evolutionRank===2?12:7;ctx.lineWidth=evolutionRank===2?2.5:1.5;ctx.beginPath();ctx.ellipse(this.x,this.y+16,31+(evolutionRank===2?5:0),12+(evolutionRank===2?2:0),0,0,Math.PI*2);ctx.stroke();ctx.restore();}
      if(!(art&&art.drawHero(ctx,this))&&!(art&&art.drawUnit(ctx,'hero',this.x,this.y,88))){ctx.save();ctx.fillStyle='#8fffc4';ctx.fillRect(this.x-12,this.y-32,24,46);ctx.restore();}
      ns.systems.EquipmentSystem.drawSignature(ctx,this);ns.systems.HeroEvolutionPresentation?.draw(ctx,art,this);
      ctx.save();if(this.state==='attack'){ctx.translate(this.x,this.y-18);ctx.rotate(this.facing);ctx.globalAlpha=this.attackTimer/.36;ctx.strokeStyle=ns.systems.EquipmentSystem.effectColor(this,'#aaffdb');ctx.lineWidth=3+this.equipment.spear*.7;ctx.beginPath();ctx.moveTo(15,0);ctx.lineTo(48+this.equipment.spear*4,0);ctx.stroke();}ctx.restore();
      ctx.save();if(this.hitFlash>0){ctx.globalAlpha=this.hitFlash*4;ctx.fillStyle='#ffebe0';ctx.beginPath();ctx.arc(this.x,this.y-12,27,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(this.x-28,this.y+29,56,5);ctx.fillStyle='#7a2525';ctx.fillRect(this.x-28,this.y+29,56*(this.health/this.maxHealth),5);ctx.globalAlpha=.72;ctx.fillStyle='#65efb2';ctx.fillRect(this.x-28,this.y+29,56*(this.displayHealth/this.maxHealth),5);ctx.globalAlpha=1;ctx.fillStyle='#fff1be';ctx.font='bold 10px Segoe UI';ctx.textAlign='center';ctx.fillText(this.invulnerable>0?'英雄 · 守護':'英雄',this.x,this.y+46);ctx.restore();
    }
  }
  ns.entities.Hero=Hero;
})(globalThis.TowerFrontier);
