(function(ns){
  'use strict';
  class Projectile{
    constructor(source,target,options){this.owner=source;this.x=source.x;this.y=source.y;this.target=target;Object.assign(this,options);this.speed=this.speed||420;this.active=true;}
    update(dt,monsters,onKill){
      if(!this.active)return;if(this.hitResolved){this.trail-=dt;if(this.trail<=0)this.active=false;return;}const target=this.target;if(!target||!target.active){this.active=false;return;}const distance=ns.utils.distance(this,target);const move=this.speed*dt;
      if(distance<=move+target.radius){this.hit(monsters,onKill);this.active=Boolean(this.chain);return;}this.x+=(target.x-this.x)/distance*move;this.y+=(target.y-this.y)/distance*move;
    }
    hit(monsters,onKill){const self=this;let victims=this.splash?monsters.filter(function(m){return m.active&&ns.utils.distance(m,self.target)<=self.splash;}):[this.target];if(this.chain){victims=[this.target];let last=this.target;while(victims.length<this.chain){const candidates=monsters.filter(function(m){return m.active&&!victims.includes(m)&&ns.utils.distance(last,m)<=self.chainRange;}).sort(function(a,b){return ns.utils.distance(last,a)-ns.utils.distance(last,b);});if(!candidates.length)break;last=candidates[0];victims.push(last);}}this.hitResolved=true;this.trail=.18;this.chainPoints=[{x:this.x,y:this.y}].concat(victims.map(function(m){return{x:m.x,y:m.y};}));victims.forEach(function(monster,index){if(!monster.active)return;if(self.slow)monster.applySlow(self.slow,self.slowTime);const table=ns.config.damageMultipliers[self.attackType]||{};const damage=self.damage*(table[monster.armorType]||1)*(self.chain&&index>0?.7:1);if(monster.takeDamage(damage)&&onKill)onKill(monster,self);});}
    draw(ctx){ctx.save();if(this.chain&&this.hitResolved){ctx.strokeStyle=this.color;ctx.lineWidth=3;ctx.globalAlpha=Math.max(0,this.trail/.18);ctx.beginPath();this.chainPoints.forEach(function(point,index){if(!index)ctx.moveTo(point.x,point.y);else{const previous=this.chainPoints[index-1];ctx.lineTo((point.x+previous.x)/2+7,(point.y+previous.y)/2-6);ctx.lineTo(point.x,point.y);}},this);ctx.stroke();ctx.restore();return;}if(this.style==='lightning'){ctx.strokeStyle=this.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(this.x-5,this.y+12);ctx.lineTo(this.x+4,this.y+3);ctx.lineTo(this.x-3,this.y-2);ctx.lineTo(this.x+5,this.y-12);ctx.stroke();}ctx.strokeStyle=this.color;ctx.lineWidth=3;ctx.shadowColor=this.color;ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(this.x,this.y+8);ctx.lineTo(this.x,this.y);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(this.x,this.y,3.5,0,Math.PI*2);ctx.fill();ctx.restore();}
  }
  ns.entities.Projectile=Projectile;
})(globalThis.TowerFrontier);
