(function(ns){
  'use strict';
  class Summon{
    constructor(owner,options){const offsetX=options.offsetX===undefined?16:options.offsetX,offsetY=options.offsetY===undefined?10:options.offsetY;Object.assign(this,{owner:owner,x:owner.x+offsetX,y:owner.y+offsetY,active:true,time:options.duration||12,damage:options.damage||12,range:options.range||120,leash:options.leash||195,color:options.color||'#97ffe0',cooldown:.2,clock:0,offsetX,offsetY,speed:options.speed||90,form:options.form||'spirit',state:'idle',frame:0,frameClock:0,facing:0,level:options.level||Math.max(1,(owner.equipment&&owner.equipment.charm||0)+1),attackTimer:0,tags:options.tags||['summon',options.form==='crypt'||options.form==='graveyard'?'undead':'magic'],splash:options.splash||0,spawnTime:.55,launchDelay:options.launchDelay||0,armedTime:0});}
    setState(state){if(this.state===state)return;this.state=state;this.frame=0;this.frameClock=0;}
    animate(dt){const fps={idle:2.5,walk:8,attack:10,hit:7,death:5}[this.state]||4;this.frameClock+=dt*fps;this.frame=Math.floor(this.frameClock)%4;}
    update(dt,monsters,projectiles){
      if(this.owner.retired){this.active=false;return;}if(this.launchDelay>0){this.launchDelay=Math.max(0,this.launchDelay-dt);return;}if(this.spawnTime>0){const elapsed=Math.min(dt,this.spawnTime);this.spawnTime-=elapsed;this.clock+=elapsed;dt-=elapsed;if(dt<=0)return;}this.time-=dt;this.clock+=dt;this.cooldown-=dt;this.attackTimer=Math.max(0,this.attackTimer-dt);
      if(this.time<=0||this.owner.retired){this.active=false;this.setState('death');return;}
      const target=monsters.filter(function(m){return m.active&&ns.utils.distance(this.owner,m)<=this.leash;},this).sort(function(a,b){return b.progress()-a.progress();})[0];
      const bomb=this.form==='bomb'||this.form==='heavyBomb';if(bomb&&target&&ns.utils.distance(this,target)<=this.range+target.radius){this.armedTime+=dt;this.facing=Math.atan2(target.y-this.y,target.x-this.x);this.setState('attack');this.animate(dt);if(this.armedTime>=(this.form==='heavyBomb'?.65:.18)){projectiles.push(new ns.entities.Projectile(this.owner,target,{x:this.x,y:this.y,damage:this.damage*(1+(this.supportDamage||0)),splash:this.splash,attackType:'chaos',color:'#ffb15b',style:'explosion',speed:99999,secondary:true}));this.active=false;}return;}
      const destination=target||this.owner,dx=destination.x+this.offsetX-this.x,dy=destination.y+this.offsetY-this.y,distance=Math.hypot(dx,dy);
      let moved=false;if(distance>(target?Math.max(2,Math.min(35,this.range-Math.abs(this.offsetX)-5)):25)){const move=Math.min(distance,this.speed*dt);this.x+=dx/distance*move;this.y+=dy/distance*move;this.facing=Math.atan2(dy,dx);moved=true;}
      if(!bomb&&target&&this.cooldown<=0&&ns.utils.distance(this,target)<=this.range){this.facing=Math.atan2(target.y-this.y,target.x-this.x);const melee=this.form==='hunter',bear=this.form==='bear',goblin=this.form==='goblin';this.strikes=(this.strikes||0)+1;projectiles.push(new ns.entities.Projectile(this.owner,target,{x:this.x,y:this.y,damage:this.damage*(1+(this.supportDamage||0))*(melee?(1+.12*(this.level-1)):1),color:this.color,attackType:melee||goblin?'pierce':'magic',speed:bear?99999:melee?950:goblin?580:360,style:goblin?'goblin-rivet':bear?'claw':melee?'bite':'spirit',splash:goblin&&this.strikes%3===0?24:this.form==='bear'&&this.level>=3?35:0,secondary:true}));this.cooldown=goblin?Math.max(.5,.7-(this.level-1)*.03):Math.max(.5,.85-(this.level-1)*.06);this.attackTimer=.34;this.setState('attack');}
      else if(this.attackTimer<=0)this.setState(moved?'walk':'idle');this.animate(dt);
    }
    draw(ctx,art){if(this.launchDelay>0)return;if(this.spawnTime>0){if(art&&art.summonVfxCount!==undefined&&art.summonVfxCount++>=art.maxSummonVfx){ctx.save();ctx.globalAlpha=1-this.spawnTime/.55;art.drawSummon(ctx,this);ctx.restore();return;}if(ns.systems.HeroSkillVFX&&['hunter','arcanist','rogue','chief'].includes(this.form)){ns.systems.HeroSkillVFX.summonBirth(ctx,this);ctx.save();ctx.globalAlpha=1-this.spawnTime/.55;if(art&&art.drawSummon)art.drawSummon(ctx,this);ctx.restore();return;}ctx.save();const t=1-this.spawnTime/.55,nature=this.tags.includes('nature'),mechanical=this.tags.includes('mechanical');ctx.globalAlpha=.75;ctx.strokeStyle=nature?'#97ed9e':mechanical?'#ffc17b':'#b88bff';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(this.x,this.y+5,12+22*t,5+8*t,0,0,Math.PI*2);ctx.stroke();for(let i=0;i<5;i++){const a=i*Math.PI*2/5+t*3;ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.ellipse(this.x+Math.cos(a)*24*(1-t),this.y-35*t+Math.sin(a)*12,3,nature?1.5:3,a,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=t;if(art&&art.drawSummon)art.drawSummon(ctx,this);ctx.restore();return;}if(this.armedTime>0){ctx.save();ctx.strokeStyle='#ff633b';ctx.globalAlpha=.5+Math.sin(this.armedTime*36)*.3;ctx.lineWidth=3;ctx.beginPath();ctx.arc(this.x,this.y,18+this.armedTime*20,0,Math.PI*2);ctx.stroke();ctx.restore();}if(art&&art.drawSummon&&art.drawSummon(ctx,this))return;if(this.form==='rogue'&&art){ctx.save();ctx.globalAlpha=.65;art.drawCombatUnit(ctx,{type:'rogue',x:this.x,y:this.y,level:1,state:this.state,frame:this.frame,facing:this.facing,config:function(){return{color:'#c884df'};}});ctx.restore();return;}ctx.save();ctx.translate(this.x,this.y);ctx.globalAlpha=Math.min(.85,this.time/2);ctx.strokeStyle=this.color;ctx.fillStyle=this.color;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,8,17,6,0,0,Math.PI*2);ctx.stroke();ctx.rotate(this.clock*2);for(let i=0;i<3;i++){ctx.rotate(Math.PI*2/3);ctx.beginPath();ctx.arc(13,0,3,0,Math.PI*2);ctx.fill();}ctx.rotate(-this.clock*2);ctx.globalAlpha*=.45;ctx.beginPath();ctx.arc(0,-8,10+Math.sin(this.clock*5)*2,0,Math.PI*2);ctx.fill();ctx.restore();}
  }
  ns.entities.Summon=Summon;
})(globalThis.TowerFrontier);
