(function(ns){
  'use strict';
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const number=value=>Number(value||0).toLocaleString('zh-TW');
  const time=value=>{const n=Number(value);if(!Number.isFinite(n)||n<0)return '—';return String(Math.floor(n/3600)).padStart(2,'0')+':'+String(Math.floor(n%3600/60)).padStart(2,'0')+':'+String(Math.floor(n%60)).padStart(2,'0');};
  const outcome={success:'通關',failure:'失敗',retreated:'撤退'};
  const tabs=[['total','🏆','總積分榜','完成 16 波起'],['map','▥','地圖排行榜','依戰場篩選'],['weekly','⚔','本週挑戰','敬請期待'],['friends','♟','好友排行','敬請期待']];
  class RankingView{
    constructor(profileStore){this.source=new ns.ranking.RankingDataSource(profileStore);this.tab='total';this.map='all';this.page=0;this.selected=0;this.rules=false;}
    action(action,value){
      if(action==='ranking-tab'){this.tab=tabs.some(row=>row[0]===value)?value:'total';this.page=0;this.selected=0;}
      if(action==='ranking-map'){this.map=value in ns.ranking.RankingDataSource.maps?value:'all';this.page=0;this.selected=0;}
      if(action==='ranking-row')this.selected=Math.max(0,Number(value)||0);
      if(action==='ranking-page'){this.page=Math.max(0,this.page+(value==='next'?1:-1));this.selected=this.page*10;}
      if(action==='ranking-rules')this.rules=!this.rules;
    }
    rows(){const data=this.source.read(),seen=new Set();let records=data.records.filter(record=>{if(seen.has(record.runId))return false;seen.add(record.runId);return true;}).sort((a,b)=>b.finalScore-a.finalScore||String(b.timestamp||'').localeCompare(String(a.timestamp||'')));if(this.tab==='map'&&this.map!=='all')records=records.filter(row=>row.mapId===this.map);return {records:records.map(ns.ranking.RankingDataSource.display),status:data.status};}
    render(){
      const {records,status}=this.rows(),available=this.tab==='total'||this.tab==='map',pageCount=Math.max(1,Math.ceil(records.length/10));this.page=Math.min(this.page,pageCount-1);this.selected=Math.min(this.selected,Math.max(0,records.length-1));
      const selected=available?records[this.selected]:null,shown=available?records.slice(this.page*10,this.page*10+10):[];
      const mapOptions=this.tab==='map'?'<div class="rank-filters" aria-label="地圖篩選"><span>地圖</span>'+[['all','全部地圖'],...Object.entries(ns.ranking.RankingDataSource.maps).map(([id,m])=>[id,m[0]])].map(([id,name])=>'<button type="button" data-action="ranking-map" data-value="'+id+'" aria-pressed="'+(this.map===id)+'" class="'+(this.map===id?'active':'')+'">'+escape(name)+'</button>').join('')+'</div>':'';
      const rows=shown.map((r,i)=>{const index=this.page*10+i,rank=index+1;return '<button type="button" class="rank-row '+(index===this.selected?'selected ':'')+(rank===1?'first':'')+'" data-action="ranking-row" data-value="'+index+'" aria-label="查看第 '+rank+' 名，'+escape(outcome[r.outcome]||'失敗')+'，'+number(r.finalScore)+' 分" aria-pressed="'+(index===this.selected)+'"><span class="rank-position '+(rank<=3?'medal':'')+'">'+rank+'</span><span class="rank-player"><img src="'+r.heroImage+'" alt=""><span>'+escape(r.playerName)+'<small>'+escape(r.heroName)+'</small></span></span><span class="rank-faction">'+escape(r.factionName)+'</span><span class="rank-map"><img src="'+r.mapImage+'" alt=""><span>'+escape(r.mapName)+'<small class="difficulty '+escape(r.difficultyId)+'">'+escape(r.difficultyName)+'</small></span></span><strong class="rank-score">'+number(r.finalScore)+'<small class="rank-outcome '+escape(r.outcome)+'">'+escape(outcome[r.outcome]||'失敗')+'</small></strong></button>';}).join('');
      let body='';
      if(!available)body='<div class="rank-empty"><span aria-hidden="true">'+(this.tab==='weekly'?'⚔':'♟')+'</span><h2>'+ (this.tab==='weekly'?'本週挑戰尚未開放':'好友排行尚未開放')+'</h2><p>目前沒有線上賽季或好友排名服務。</p><button type="button" data-action="ranking-tab" data-value="total">查看本機紀錄</button></div>';
      else if(status==='error')body='<div class="rank-empty"><span aria-hidden="true">!</span><h2>積分紀錄無法讀取</h2><p>原始資料已保留。請先備份玩家存檔，再檢查瀏覽器儲存空間。</p></div>';
      else if(!shown.length)body='<div class="rank-empty"><span aria-hidden="true">🏆</span><h2>還沒有遠征積分紀錄</h2><p>自由遠征完成至少 16 波後，通關、失敗或撤退的成績才會列入排行榜。</p><button type="button" data-action="free">開始自由遠征 →</button></div>';
      else body='<div class="rank-table" aria-label="遠征積分紀錄"><div class="rank-columns"><span>排名</span><span>玩家 / 英雄</span><span>所屬陣營</span><span>戰場 / 難度</span><span>積分 / 結果</span></div><div class="rank-rows">'+rows+'</div></div>';
      const profileArt={kingdom:'assets/td/lobby/kingdom-lobby-v1.png',snow:'assets/td/lobby/expedition-card-v1.png',goblin:'assets/td/goblin-chief-engineer-v1.png'}[this.source.profileStore.current().profileArt]||'assets/td/lobby/kingdom-lobby-v1.png';
      const detail=selected?'<div class="rank-detail-hero" style="--rank-hero:url(\''+profileArt+'\')"><span class="rank-detail-place">#'+(this.selected+1)+'</span><div><img class="rank-detail-avatar" src="'+selected.heroImage+'" alt=""><h2>'+escape(selected.playerName)+'</h2><p>'+escape(selected.heroName)+'　·　'+escape(selected.factionName)+'</p><small>本機實際紀錄 · '+escape(outcome[selected.outcome]||'失敗')+'</small></div></div><div class="rank-detail-content"><button type="button" data-action="profile">查看我的個人頁籤</button><h3>遠征紀錄</h3><div class="rank-detail-run"><img src="'+selected.mapImage+'" alt="'+escape(selected.mapName)+'地圖"><div><b>'+escape(selected.mapName)+'</b><span class="difficulty '+escape(selected.difficultyId)+'">'+escape(selected.difficultyName)+'</span><small>◷ 遊玩時間　'+time(selected.clearTime)+'</small><small>♥ 基地生命　'+(Number.isFinite(Number(selected.remainingBaseHP))?escape(selected.remainingBaseHP):'—')+(selected.maxBaseHP?'/'+escape(selected.maxBaseHP):'')+'</small><small>⚔ 完成波次　'+(Number.isFinite(Number(selected.waveCount))?escape(selected.waveCount):'—')+'</small></div></div><div class="rank-detail-total"><span>'+escape(outcome[selected.outcome]||'失敗')+' · 遠征積分</span><strong>'+number(selected.finalScore)+'</strong></div></div>':'<div class="rank-detail-placeholder"><h2>選擇一筆紀錄</h2><p>查看地圖、英雄、結果與實際積分。</p></div>';
      return '<section class="ranking-page"><header class="rank-heading"><div><small>HERO FRONTIER · RANKING</small><h1>排行榜 <span>RANKING</span></h1><p>完成 16 波起列入排行；撤退也會清楚標記。</p></div></header><p class="rank-scope" role="status">目前玩家的本機自由遠征紀錄 · 依實際積分排序 · 尚未連接線上排行榜</p><div class="rank-layout"><div class="rank-list-panel"><div class="rank-tabs" role="tablist" aria-label="排行榜種類">'+tabs.map(([id,icon,title,subtitle])=>'<button type="button" role="tab" data-action="ranking-tab" data-value="'+id+'" aria-selected="'+(this.tab===id)+'" class="'+(this.tab===id?'active':'')+'"><span aria-hidden="true">'+icon+'</span><b>'+title+'</b><small>'+subtitle+'</small></button>').join('')+'</div>'+mapOptions+body+'<div class="rank-footer"><span>'+(available?'共 '+records.length+' 筆實際紀錄':'線上排行功能待開放')+'</span>'+(available&&pageCount>1?'<nav aria-label="排行榜分頁"><button type="button" data-action="ranking-page" data-value="previous" '+(this.page===0?'disabled':'')+'>‹ 上一頁</button><span>'+(this.page+1)+' / '+pageCount+'</span><button type="button" data-action="ranking-page" data-value="next" '+(this.page===pageCount-1?'disabled':'')+'>下一頁 ›</button></nav>':'')+'</div></div><aside class="rank-detail-panel" aria-label="所選紀錄詳情">'+detail+'<button type="button" class="rank-rules-button" data-action="ranking-rules" aria-expanded="'+this.rules+'">積分規則　'+(this.rules?'−':'+')+'</button>'+(this.rules?'<div class="rank-rules"><p>僅收錄完成超過 15 波（至少 16 波）的自由遠征；未完成的當前波不計入門檻。每波擊殺、守城與速度計分；難度倍率依戰場設定。撤退時保留已完成波次與本波目前擊殺分。勝利、失敗、撤退採同一算法，結果分開標示。</p><p>本機紀錄未經伺服器驗證，不代表世界名次。</p></div>':'')+'</aside></div></section>';
    }
  }
  ns.ranking.RankingView=RankingView;
})(globalThis.TowerFrontier);
