(function(ns){
  'use strict';
  const canvas=document.getElementById('versus-game'),ctx=canvas.getContext('2d'),C=ns.config;
  let match=new ns.systems.VersusMatch(),selected=null,lane='upper',speed=1,last=performance.now(),placement=null,selectedStructure=null,paused=false;
  const $=id=>document.getElementById(id),buttons=Array.from(document.querySelectorAll('[data-build]')),laneButtons=Array.from(document.querySelectorAll('[data-lane]'));
  const asset=src=>{const image=new Image();image.src=src;return image;};
  const art={background:asset('assets/td/versus-battlefield-concept-v1.png'),tower:asset('assets/td/towers-atlas-v1.png'),structures:asset('assets/td/faction-structures-v1.png'),infantry:asset('assets/td/faction-shield-v1.png'),ranger:asset('assets/td/faction-musketeer-actions-v1.png'),siege:asset('assets/td/bomb-robot-actions-v2.png'),worker:asset('assets/td/blacksmith-actions-v2.png')};
  function sprite(image,x,y,size,frame,row){if(!image.complete||!image.naturalWidth)return false;const sw=image.naturalWidth/4,sh=image.naturalHeight/4;ctx.drawImage(image,(frame||0)*sw,(row||0)*sh,sw,sh,x-size/2,y-size*.76,size,size);return true;}
  function healthBar(subject,width,y){ctx.fillStyle='#160e0caa';ctx.fillRect(subject.x-width/2,y,width,5);ctx.fillStyle=subject.side==='player'?'#54c6ff':'#ff655c';ctx.fillRect(subject.x-width/2,y,width*Math.max(0,subject.hp/subject.maxHp),5);}
  function drawBackground(){if(art.background.complete&&art.background.naturalWidth)ctx.drawImage(art.background,0,0,C.width,C.height);else{ctx.fillStyle='#477c45';ctx.fillRect(0,0,C.width,C.height);}ctx.fillStyle='rgba(67,151,209,.08)';ctx.fillRect(0,0,C.width/3,C.height);ctx.fillStyle='rgba(215,84,72,.07)';ctx.fillRect(C.width*2/3,0,C.width/3,C.height);ctx.strokeStyle='#f1dc8b66';ctx.lineWidth=2;ctx.setLineDash([10,12]);[C.width/3,C.width*2/3].forEach(x=>{ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,C.height);ctx.stroke();});ctx.setLineDash([]);}
  function drawBase(base){healthBar(base,108,base.y+98);ctx.fillStyle='#fff2c8';ctx.font='700 15px sans-serif';ctx.textAlign='center';ctx.fillText(Math.ceil(base.hp),base.x,base.y+120);}
  function drawStructure(s){if(s.side==='enemy'&&!match.visibleToPlayer(s))return;let drawn=false;if(s.type==='tower'&&art.tower.complete&&art.tower.naturalWidth){const sw=art.tower.naturalWidth/3;ctx.drawImage(art.tower,0,0,sw,art.tower.naturalHeight,s.x-42,s.y-66,84,84);drawn=true;}else if(art.structures.complete&&art.structures.naturalWidth){const column={infantry:0,ranger:1,siege:2}[s.type],sw=art.structures.naturalWidth/3,sh=art.structures.naturalHeight*.29;ctx.drawImage(art.structures,column*sw,0,sw,sh,s.x-45,s.y-70,90,88);drawn=true;}if(!drawn){ctx.fillStyle=s.side==='player'?'#377bb0':'#a9443e';ctx.fillRect(s.x-22,s.y-25,44,50);}healthBar(s,48,s.y+28);}
  function drawUnit(u){if(u.side==='enemy'&&!match.visibleToPlayer(u))return;const frame=Math.floor(performance.now()/180)%4,drawn=sprite(art[u.type],u.x,u.y,u.type==='siege'?48:42,frame,1);if(!drawn){ctx.fillStyle=u.side==='player'?'#8ed8ff':'#ff9188';ctx.beginPath();ctx.arc(u.x,u.y,10,0,Math.PI*2);ctx.fill();}healthBar(u,30,u.y+8);}
  function drawWorker(side,w){if(side==='enemy'&&!match.visibleToPlayer(w))return;const frame=Math.floor(performance.now()/220)%4;if(!sprite(art.worker,w.x,w.y,45,frame,1)){ctx.fillStyle=side==='player'?'#fff0a8':'#ffb496';ctx.beginPath();ctx.moveTo(w.x,w.y-12);ctx.lineTo(w.x+11,w.y+10);ctx.lineTo(w.x-11,w.y+10);ctx.closePath();ctx.fill();}ctx.strokeStyle=side==='player'?'#68caff':'#ff6b61';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(w.x,w.y+7,18,7,0,0,Math.PI*2);ctx.stroke();}
  function drawFog(){ctx.save();ctx.fillStyle='rgba(3,12,10,.66)';ctx.fillRect(C.width*2/3,0,C.width/3,C.height);ctx.globalCompositeOperation='destination-out';match.units.filter(u=>u.active&&u.side==='player'&&u.x>C.width*2/3-150).forEach(u=>{const g=ctx.createRadialGradient(u.x,u.y,40,u.x,u.y,165);g.addColorStop(0,'rgba(0,0,0,1)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(u.x,u.y,165,0,Math.PI*2);ctx.fill();});ctx.restore();}
  function draw(){ctx.clearRect(0,0,C.width,C.height);drawBackground();match.nodes.forEach(n=>{ctx.strokeStyle=n.owner==='player'?'#65bfff':n.owner==='enemy'?'#ff6c5f':'#f5d979';ctx.lineWidth=4;ctx.globalAlpha=.75+.2*Math.sin(performance.now()/300);ctx.beginPath();ctx.arc(n.x,n.y,24,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;});match.structures.forEach(drawStructure);match.units.forEach(drawUnit);Object.entries(match.workers).forEach(([side,w])=>drawWorker(side,w));if(placement){const check=match.validateBuild('player',selected,placement.x,lane);ctx.fillStyle=check.ok?'rgba(91,255,162,.3)':'rgba(255,82,70,.35)';ctx.strokeStyle=check.ok?'#72ffad':'#ff675d';ctx.lineWidth=3;ctx.beginPath();ctx.arc(placement.x,check.y||placement.y,34,0,Math.PI*2);ctx.fill();ctx.stroke();}drawBase(match.bases.player);drawBase(match.bases.enemy);drawFog();}
  function ui(){const mins=Math.floor(match.remaining/60),secs=Math.floor(match.remaining%60);$('versus-time').textContent=mins+':'+String(secs).padStart(2,'0');$('player-hp').textContent=Math.ceil(match.bases.player.hp);$('enemy-hp').textContent=Math.ceil(match.bases.enemy.hp);$('player-gold').textContent=Math.floor(match.gold.player);$('versus-state').textContent=match.elapsed<120?'偵察敵軍戰術中':'敵軍風格：'+match.ai.profile.name;if(match.result){$('versus-result').hidden=false;$('versus-result-title').textContent=match.result.winner==='player'?'勝利':match.result.winner==='enemy'?'戰敗':'平手';$('versus-result-copy').textContent=(match.result.reason==='base'?'主堡已被摧毀。':'12 分鐘時間到。')+' 我方 '+Math.ceil(match.result.playerHp)+' HP／敵方 '+Math.ceil(match.result.enemyHp)+' HP；敵軍採用「'+match.ai.profile.name+'」。';}}
  canvas.addEventListener('pointerdown',event=>{if(match.status!=='playing'||paused)return;const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*C.width/rect.width,y=(event.clientY-rect.top)*C.height/rect.height;if(selected){placement={x,y};const check=match.validateBuild('player',selected,x,lane);$('versus-placement').hidden=false;$('versus-placement-title').textContent=C.structures[selected].name+' · '+(lane==='upper'?'上路':'下路');$('versus-placement-copy').textContent=check.reason;$('versus-placement-confirm').disabled=!check.ok;return;}const hit=match.structures.filter(s=>s.active&&s.side==='player'&&Math.hypot(s.x-x,s.y-y)<45)[0];if(hit){selectedStructure=hit;$('versus-selection').hidden=false;$('versus-selection-name').textContent=C.structures[hit.type].name;$('versus-selection-stats').textContent='HP '+Math.ceil(hit.hp)+' / '+hit.maxHp+(C.structures[hit.type].unit?' · 自動生產 '+C.unitTypes[C.structures[hit.type].unit].name:' · 射程 '+C.structures[hit.type].range);return;}match.moveWorker('player',x,y);});
  buttons.forEach(b=>b.onclick=()=>{selected=b.dataset.build;buttons.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('versus-worker-mode').setAttribute('aria-pressed','false');});
  $('versus-worker-mode').onclick=()=>{selected=null;placement=null;$('versus-placement').hidden=true;buttons.forEach(x=>x.setAttribute('aria-pressed','false'));$('versus-worker-mode').setAttribute('aria-pressed','true');$('versus-help').textContent='點擊草地移動工人；點己方建築可查看、維修或拆除。';};
  laneButtons.forEach(b=>b.onclick=()=>{lane=b.dataset.lane;laneButtons.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});$('versus-speed').onchange=e=>{speed=Number(e.target.value)||1;};$('versus-restart').onclick=()=>{match=new ns.systems.VersusMatch();$('versus-result').hidden=true;};
  $('versus-placement-confirm').onclick=()=>{if(placement&&selected&&match.build('player',selected,placement.x,lane)){$('versus-help').textContent='建造完成；建築將自動防守或生產士兵。';placement=null;$('versus-placement').hidden=true;}};$('versus-placement-cancel').onclick=()=>{placement=null;$('versus-placement').hidden=true;};$('versus-selection-close').onclick=()=>{$('versus-selection').hidden=true;selectedStructure=null;};$('versus-repair').onclick=()=>{if(match.repair('player',selectedStructure))$('versus-help').textContent='維修完成並扣除金幣。';};$('versus-demolish').onclick=()=>{if(match.demolish('player',selectedStructure)){$('versus-selection').hidden=true;selectedStructure=null;$('versus-help').textContent='建築已拆除，返還 50% 建造金幣。';}};$('versus-build-open').onclick=()=>{$('versus-build-drawer').hidden=false;};$('versus-build-close').onclick=()=>{$('versus-build-drawer').hidden=true;};$('versus-menu-open').onclick=()=>{paused=true;$('versus-menu').hidden=false;};$('versus-menu-continue').onclick=()=>{paused=false;$('versus-menu').hidden=true;};$('versus-menu-restart').onclick=()=>{match=new ns.systems.VersusMatch();paused=false;$('versus-menu').hidden=true;};$('versus-rules').onclick=()=>{paused=true;$('versus-rules-panel').hidden=false;};$('versus-rules-close').onclick=()=>{paused=false;$('versus-rules-panel').hidden=true;};
  function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(!paused)for(let i=0;i<speed;i++)match.update(dt);draw();ui();requestAnimationFrame(loop);}requestAnimationFrame(loop);
})(globalThis.FrontierVersus);
