(function(ns){
  'use strict';const canvas=document.getElementById('versus-game'),ctx=canvas.getContext('2d'),C=ns.config;let match=new ns.systems.VersusMatch(),selected=null,lane='upper',speed=1,last=performance.now();
  const $=id=>document.getElementById(id),buttons=Array.from(document.querySelectorAll('[data-build]')),laneButtons=Array.from(document.querySelectorAll('[data-lane]'));
  function road(y){ctx.strokeStyle='#caa36a';ctx.lineWidth=72;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(70,y);ctx.bezierCurveTo(370,y-45,500,y+35,640,y);ctx.bezierCurveTo(790,y-35,930,y+45,1210,y);ctx.stroke();ctx.strokeStyle='#e1c28c';ctx.lineWidth=3;ctx.setLineDash([16,18]);ctx.stroke();ctx.setLineDash([]);}
  function base(b,color){ctx.fillStyle='#1b2522';ctx.strokeStyle=color;ctx.lineWidth=6;ctx.fillRect(b.x-48,b.y-75,96,150);ctx.strokeRect(b.x-48,b.y-75,96,150);ctx.fillStyle=color;ctx.fillRect(b.x-38,b.y-90,76,22);ctx.fillStyle='#120d09';ctx.fillRect(b.x-38,b.y+88,76,7);ctx.fillStyle=color;ctx.fillRect(b.x-38,b.y+88,76*(b.hp/b.maxHp),7);}
  function draw(){ctx.clearRect(0,0,C.width,C.height);ctx.fillStyle='#477c45';ctx.fillRect(0,0,C.width,C.height);ctx.fillStyle='#315f3d';for(let x=20;x<C.width;x+=70)for(let y=45;y<C.height;y+=75){ctx.beginPath();ctx.arc(x+(y%4)*7,y,12,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#526f59aa';ctx.fillRect(0,0,C.width/3,C.height);ctx.fillStyle='#704d4a55';ctx.fillRect(C.width*2/3,0,C.width/3,C.height);road(C.lanes.upper);road(C.lanes.lower);ctx.fillStyle='#445c50';ctx.beginPath();ctx.arc(640,378,74,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#c9b77d';ctx.lineWidth=5;ctx.stroke();match.nodes.forEach(n=>{ctx.fillStyle=n.owner==='player'?'#65bfff':n.owner==='enemy'?'#ff6c5f':'#e9cd73';ctx.beginPath();ctx.arc(n.x,n.y,18,0,Math.PI*2);ctx.fill();});base(match.bases.player,'#58baff');base(match.bases.enemy,'#ff6257');match.structures.forEach(s=>{if(s.side==='enemy'&&!match.visibleToPlayer(s))return;ctx.fillStyle=s.side==='player'?'#377bb0':'#a9443e';ctx.strokeStyle='#f1dfac';ctx.lineWidth=2;ctx.fillRect(s.x-22,s.y-25,44,50);ctx.strokeRect(s.x-22,s.y-25,44,50);ctx.fillStyle='#15110d';ctx.fillRect(s.x-22,s.y+29,44,4);ctx.fillStyle='#74dd8d';ctx.fillRect(s.x-22,s.y+29,44*(s.hp/s.maxHp),4);ctx.fillStyle='#fff3c4';ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillText(s.type==='tower'?'塔':s.type==='infantry'?'兵':s.type==='ranger'?'弓':'槌',s.x,s.y+4);});match.units.forEach(u=>{if(u.side==='enemy'&&!match.visibleToPlayer(u))return;ctx.fillStyle=u.side==='player'?'#8ed8ff':'#ff9188';ctx.beginPath();ctx.arc(u.x,u.y,u.type==='siege'?15:10,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#18221d';ctx.stroke();});Object.entries(match.workers).forEach(([side,w])=>{if(side==='enemy'&&!match.visibleToPlayer(w))return;ctx.fillStyle=side==='player'?'#fff0a8':'#ffb496';ctx.beginPath();ctx.moveTo(w.x,w.y-12);ctx.lineTo(w.x+11,w.y+10);ctx.lineTo(w.x-11,w.y+10);ctx.closePath();ctx.fill();});ctx.fillStyle='rgba(3,8,7,.72)';ctx.fillRect(C.width*2/3,0,C.width/3,C.height);match.units.filter(u=>u.side==='player'&&u.x>C.width*2/3).forEach(u=>{const g=ctx.createRadialGradient(u.x,u.y,20,u.x,u.y,155);g.addColorStop(0,'rgba(0,0,0,1)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.globalCompositeOperation='destination-out';ctx.fillStyle=g;ctx.beginPath();ctx.arc(u.x,u.y,155,0,Math.PI*2);ctx.fill();ctx.globalCompositeOperation='source-over';});}
  function ui(){const mins=Math.floor(match.remaining/60),secs=Math.floor(match.remaining%60);$('versus-time').textContent=mins+':'+String(secs).padStart(2,'0');$('player-hp').textContent=Math.ceil(match.bases.player.hp);$('enemy-hp').textContent=Math.ceil(match.bases.enemy.hp);$('player-gold').textContent=Math.floor(match.gold.player);$('versus-state').textContent=match.elapsed<120?'偵察敵軍戰術中':'敵軍風格：'+match.ai.profile.name;if(match.result){$('versus-result').hidden=false;$('versus-result-title').textContent=match.result.winner==='player'?'勝利':match.result.winner==='enemy'?'戰敗':'平手';$('versus-result-copy').textContent=(match.result.reason==='base'?'主堡已被摧毀。':'12 分鐘時間到。')+' 我方 '+Math.ceil(match.result.playerHp)+' HP／敵方 '+Math.ceil(match.result.enemyHp)+' HP；敵軍採用「'+match.ai.profile.name+'」。';}}
  canvas.addEventListener('pointerdown',event=>{if(match.status!=='playing')return;const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*C.width/rect.width,y=(event.clientY-rect.top)*C.height/rect.height;if(selected){if(match.build('player',selected,x,lane))$('versus-help').textContent='建造完成；建築將自動防守或生產士兵。';else $('versus-help').textContent='無法建造：可能位於敵方保護區、位置重疊或金幣不足。';}else match.moveWorker('player',x,y);});
  buttons.forEach(b=>b.onclick=()=>{selected=b.dataset.build;buttons.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('versus-worker-mode').setAttribute('aria-pressed','false');});$('versus-worker-mode').onclick=()=>{selected=null;buttons.forEach(x=>x.setAttribute('aria-pressed','false'));$('versus-worker-mode').setAttribute('aria-pressed','true');$('versus-help').textContent='點擊草地移動工人；工人不會死亡，也不能進入敵方保護區。';};laneButtons.forEach(b=>b.onclick=()=>{lane=b.dataset.lane;laneButtons.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});$('versus-speed').onchange=e=>{speed=Number(e.target.value)||1;};$('versus-restart').onclick=()=>{match=new ns.systems.VersusMatch();$('versus-result').hidden=true;};
  function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;for(let i=0;i<speed;i++)match.update(dt);draw();ui();requestAnimationFrame(loop);}requestAnimationFrame(loop);
})(globalThis.FrontierVersus);
