(function(ns){
  'use strict';const C=ns.config;
  class VersusMatch{
    constructor(options){options=options||{};this.random=options.random||Math.random;this.reset();}
    reset(){this.elapsed=0;this.remaining=C.duration;this.status='playing';this.result=null;this.gold={player:C.startGold,enemy:C.startGold};this.bases={player:{side:'player',x:72,y:360,hp:C.baseHp,maxHp:C.baseHp,active:true},enemy:{side:'enemy',x:1208,y:360,hp:C.baseHp,maxHp:C.baseHp,active:true}};this.workers={player:{x:170,y:360,targetX:170,targetY:360},enemy:{x:1110,y:360,targetX:1110,targetY:360}};this.units=[];this.structures=[];this.nodes=[{lane:'upper',x:640,y:330,owner:null,progress:0,payTimer:12},{lane:'lower',x:640,y:425,owner:null,progress:0,payTimer:12}];this.ai=new ns.systems.AIStrategy(this.random);this.build('player','infantry',220,'upper',true);this.build('enemy','infantry',1060,'lower',true);return this;}
    allowed(side,x){return side==='player'?x<C.width*(1-C.protectedThird):x>C.width*C.protectedThird;}
    validateBuild(side,type,x,lane,free){const cfg=C.structures[type],y=C.lanes[lane]+(side==='player'?58:-58),worker=this.workers[side];if(!cfg||!C.lanes[lane])return{ok:false,reason:'未知建築'};if(!this.allowed(side,x))return{ok:false,reason:'敵方保護區禁止施工'};if(!free&&this.gold[side]<cfg.cost)return{ok:false,reason:'金幣不足'};if(!free&&Math.hypot(worker.x-x,worker.y-y)>125)return{ok:false,reason:'工人距離太遠'};if(this.structures.some(s=>s.active&&Math.hypot(s.x-x,s.y-y)<46))return{ok:false,reason:'與既有建築重疊'};return{ok:true,reason:'可施工',y:y,cost:cfg.cost};}
    build(side,type,x,lane,free){const check=this.validateBuild(side,type,x,lane,free);if(!check.ok)return false;if(!free)this.gold[side]-=check.cost;this.structures.push(new ns.entities.Structure(side,type,x,lane));return true;}
    repair(side,structure){if(!structure||!structure.active||structure.side!==side||structure.hp>=structure.maxHp)return false;const missing=structure.maxHp-structure.hp,cost=Math.max(1,Math.ceil(missing*.12));if(this.gold[side]<cost)return false;this.gold[side]-=cost;structure.hp=Math.min(structure.maxHp,structure.hp+Math.max(80,structure.maxHp*.25));return true;}
    demolish(side,structure){if(!structure||!structure.active||structure.side!==side)return false;this.gold[side]+=Math.floor(C.structures[structure.type].cost*.5);structure.active=false;return true;}
    moveWorker(side,x,y){const min=side==='player'?20:C.width*C.protectedThird,max=side==='player'?C.width*(1-C.protectedThird):C.width-20,worker=this.workers[side];worker.targetX=Math.max(min,Math.min(max,x));worker.targetY=Math.max(80,Math.min(C.height-60,y));}
    updateWorkers(dt){Object.values(this.workers).forEach(w=>{const dx=w.targetX-w.x,dy=w.targetY-w.y,d=Math.hypot(dx,dy);if(d>2){const step=Math.min(d,115*dt);w.x+=dx/d*step;w.y+=dy/d*step;}});}
    updateNodes(dt){this.nodes.forEach(node=>{const near=this.units.filter(u=>u.active&&Math.hypot(u.x-node.x,u.y-node.y)<110),player=near.filter(u=>u.side==='player').length,enemy=near.length-player;if(player!==enemy){const side=player>enemy?'player':'enemy';if(node.owner===side)node.progress=Math.min(5,node.progress+dt);else{node.progress+=dt*(Math.abs(player-enemy));if(node.progress>=5){node.owner=side;node.progress=0;node.payTimer=12;}}}node.payTimer-=dt;if(node.owner&&node.payTimer<=0){this.gold[node.owner]+=30;node.payTimer+=12;}});}
    score(side){return this.bases[side].hp/this.bases[side].maxHp*10000+this.structures.filter(s=>s.active&&s.side===side).reduce((n,s)=>n+ns.config.structures[s.type].cost,0)+this.units.filter(u=>u.active&&u.side===side).reduce((n,u)=>n+ns.config.unitTypes[u.type].cost*.35,0);}
    finish(reason){if(this.status!=='playing')return this.result;const p=this.bases.player.hp,e=this.bases.enemy.hp,winner=p===e?(this.score('player')===this.score('enemy')?'draw':this.score('player')>this.score('enemy')?'player':'enemy'):p>e?'player':'enemy';this.status='finished';return(this.result={winner,reason,playerHp:p,enemyHp:e,playerScore:Math.round(this.score('player')),enemyScore:Math.round(this.score('enemy')),ai:this.ai.id});}
    update(dt){if(this.status!=='playing')return;dt=Math.max(0,Math.min(.1,dt));this.elapsed+=dt;this.remaining=Math.max(0,C.duration-this.elapsed);this.gold.player+=C.incomePerSecond*dt;this.gold.enemy+=C.incomePerSecond*dt;this.updateWorkers(dt);this.ai.update(dt,this);this.structures.forEach(s=>s.update(dt,this));this.units.forEach(u=>u.update(dt,this));this.units=this.units.filter(u=>u.active&&u.x>-20&&u.x<C.width+20);this.structures=this.structures.filter(s=>s.active);this.updateNodes(dt);if(this.bases.player.hp<=0||this.bases.enemy.hp<=0)this.finish('base');else if(this.remaining<=0)this.finish('time');}
    visibleToPlayer(target){return target.x<C.width*(2/3)||this.units.some(u=>u.active&&u.side==='player'&&Math.hypot(u.x-target.x,u.y-target.y)<155);}
  }
  ns.systems.VersusMatch=VersusMatch;
})(globalThis.FrontierVersus);
