(function(ns){
  'use strict';
  class ArtSystem{
    constructor(){this.enemyActions={grunt:this.load('assets/td/enemy-grunt-actions-v1.png'),runner:this.load('assets/td/enemy-runner-actions-v1.png'),brute:this.load('assets/td/enemy-brute-actions-v1.png'),shaman:this.load('assets/td/enemy-shaman-actions-v1.png'),healer:this.load('assets/td/enemy-healer-actions-v1.png'),boss:this.load('assets/td/enemy-boss-actions-v1.png')};this.factionTowers=this.load('assets/td/faction-towers-v1.png');this.factionTowersV2=this.load('assets/td/faction-towers-v2.png');this.factionStructures=this.load('assets/td/faction-structures-v1.png');this.hero=this.load('assets/td/hero-actions-v1.png');this.heroHunter=this.load('assets/td/hero-hunter-actions-v2.png');this.heroRogue=this.load('assets/td/hero-rogue-actions-v2.png');this.heroHunterUnarmed=this.load('assets/td/hero-hunter-actions-unarmed-v3.png');this.heroArcanistUnarmed=this.load('assets/td/hero-arcanist-actions-unarmed-v1.png');this.background=this.load('assets/td/human-td-battlefield-v2.png');this.combatUnits={hunter:this.load('assets/td/ranger-actions-v1.png'),arcanist:this.load('assets/td/arcanist-actions-v1.png'),rogue:this.load('assets/td/rogue-actions-v1.png'),shield:this.load('assets/td/faction-shield-v1.png'),knight:this.load('assets/td/faction-knight-v1.png'),skeleton:this.load('assets/td/faction-skeleton-v1.png'),dragon:this.load('assets/td/faction-dragon-v1.png'),treant:this.load('assets/td/faction-treant-v1.png'),golem:this.load('assets/td/faction-golem-v1.png'),orc:this.load('assets/td/enemy-orc-grunt-actions-v2.png')};this.wolf=this.load('assets/td/war-wolf-actions-v1.png');this.arcaneElemental=this.load('assets/td/arcane-elemental-actions-v1.png');this.cryptWraith=this.load('assets/td/crypt-wraith-actions-v1.png');this.graveyardRevenant=this.load('assets/td/graveyard-revenant-actions-v1.png');this.rogueUnarmed=this.load('assets/td/hero-rogue-actions-unarmed-v2.png');this.weaponAtlas=this.load('assets/td/items/class-weapons-atlas-v1.png');this.equipmentAtlas=this.load('assets/td/items/equipment-atlas-v1.png');this.towers=this.load('assets/td/towers-atlas-v1.png');this.units=this.load('assets/td/units-atlas-v1.png');this.keep=this.load('assets/td/frontier-keep-v1.png');}
    load(src){const image=new Image();image.ready=false;image.onload=function(){image.ready=true;};image.src=src;return image;}
    drawBackground(ctx){if(!this.background.ready)return false;ctx.drawImage(this.background,0,0,ns.config.width,ns.config.height);return true;}
    drawGearPieces(ctx,target,mounted){const atlas=this.equipmentAtlas;if(!atlas||!atlas.ready||!target.gear)return;const sw=atlas.width/3,sh=atlas.height/3,items=Object.values(target.gear).map(id=>ns.systems.ArmorySystem.ITEMS[id]).filter(Boolean);items.forEach(function(item,index){let x=18+index*5,y=-48-index*4,w=31,h=31;if(item.slot==='weapon'){x=20;y=-38;w=39;h=39;}if(item.slot==='armor'){x=-17;y=-43;w=34;h=38;}if(item.mount&&mounted){x=0;y=-23;w=45;h=36;}ctx.save();ctx.globalAlpha=.9;ctx.shadowColor=item.rarity==='傳說'?'#ffd76d':'#b98cff';ctx.shadowBlur=item.rarity==='傳說'?8:4;ctx.drawImage(atlas,item.column*sw,item.row*sh,sw,sh,x-w/2,y-h/2,w,h);ctx.restore();},this);}
    drawCombatUnit(ctx,unit){const image=this.combatUnits[unit.type];if(!image||!image.ready)return false;const sw=image.width/4,sh=image.height/4;const rows={idle:0,walk:1,attack:2,hit:3,death:3};const row=rows[unit.state]||0;const frame=Math.max(0,Math.min(3,unit.frame||0));const movingLift=unit.state==='walk'?Math.sin((unit.frameClock||0)*Math.PI)*2:0;const height={shield:102,knight:104,dragon:100,treant:108,golem:112,orc:106}[unit.type]||92,width=height*(sw/sh),level=unit.level||1,visual=ns.systems.ArmorySystem?ns.systems.ArmorySystem.visual(unit):null,mounted=Boolean(visual&&visual.mount==='wolf'&&unit.type==='orc'&&this.wolf.ready);ctx.save();ctx.translate(unit.x,unit.y);if(Math.cos(unit.facing)<0)ctx.scale(-1,1);if(mounted){const ww=this.wolf.width/4,wh=this.wolf.height/4,wolfHeight=76,wolfWidth=wolfHeight*ww/wh;ctx.drawImage(this.wolf,frame*ww,row*wh,ww,wh,-wolfWidth/2,-wolfHeight*.54,wolfWidth,wolfHeight);ctx.drawImage(image,frame*sw,row*sh,sw,sh,-width*.36,-height*.96-movingLift,width*.72,height*.72);}else ctx.drawImage(image,frame*sw,row*sh,sw,sh,-width/2,-height*.79-movingLift,width,height);this.drawGearPieces(ctx,unit,mounted);if(level>=2){ctx.strokeStyle=unit.config().color;ctx.shadowColor=unit.config().color;ctx.shadowBlur=level*2;ctx.lineWidth=1+level*.45;ctx.globalAlpha=.45+.08*level;ctx.beginPath();ctx.arc(0,-36,18+level*2,-2.7,-.45);ctx.stroke();ctx.shadowBlur=0;}if(level>=3){ctx.fillStyle=level>=5?'#ecd5a1':'#97aebf';ctx.strokeStyle='#413828';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-17,-46);ctx.lineTo(0,-51);ctx.lineTo(17,-46);ctx.lineTo(12,-33);ctx.lineTo(0,-36);ctx.lineTo(-12,-33);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle=unit.config().color;ctx.lineWidth=level>=5?5:3;ctx.beginPath();ctx.moveTo(23,-18);ctx.lineTo(unit.type==='hunter'?35:26,-60);ctx.stroke();}if(level>=4){ctx.fillStyle=unit.config().color;ctx.globalAlpha=.82;ctx.beginPath();ctx.moveTo(-25,-67);ctx.lineTo(-9,-60);ctx.lineTo(-25,-48);ctx.closePath();ctx.fill();}if(level>=5){ctx.globalCompositeOperation='screen';ctx.fillStyle=unit.config().color;for(let i=0;i<3;i++){const angle=(unit.frameClock||0)*2+i*Math.PI*2/3;ctx.beginPath();ctx.arc(Math.cos(angle)*28,-31+Math.sin(angle)*12,2.5,0,Math.PI*2);ctx.fill();}}ctx.restore();this.drawRank(ctx,unit.x,unit.y,level,unit.config().color,false,unit.type);return true;}
    drawSummonSprite(ctx,summon,image,baseHeight,rankColor){if(!image||!image.ready)return false;const sw=image.width/4,sh=image.height/4,row={idle:0,walk:1,attack:2,hit:3,death:3}[summon.state]||0,frame=Math.max(0,Math.min(3,summon.frame||0)),height=baseHeight+Math.min(4,(summon.level||1)-1)*4,width=height*sw/sh;ctx.save();ctx.translate(summon.x,summon.y);ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(0,4,Math.min(30,width*.28),8,0,0,Math.PI*2);ctx.fill();if(Math.cos(summon.facing)<0)ctx.scale(-1,1);ctx.drawImage(image,frame*sw,row*sh,sw,sh,-width/2,-height*.78,width,height);ctx.restore();if(summon.level>1)this.drawRank(ctx,summon.x,summon.y,summon.level,rankColor,false,summon.form);return true;}
    drawSummon(ctx,summon){if(summon.form==='hunter')return this.drawSummonSprite(ctx,summon,this.wolf,56,'#8ed49a');if(summon.form==='arcanist')return this.drawSummonSprite(ctx,summon,this.arcaneElemental,72,'#70e7ff');if(summon.form==='crypt')return this.drawSummonSprite(ctx,summon,this.cryptWraith,68,'#c884df');if(summon.form==='graveyard')return this.drawSummonSprite(ctx,summon,this.graveyardRevenant,72,'#84e879');if(summon.form==='rogue'){ctx.save();ctx.globalAlpha=.62;const result=this.drawCombatUnit(ctx,{type:'rogue',x:summon.x,y:summon.y,level:summon.level||1,state:summon.state,frame:summon.frame,facing:summon.facing,frameClock:summon.frameClock,config:function(){return{color:'#c884df'};}});ctx.restore();return result;}return false;}
    drawRogueWeapons(ctx,hero){const atlas=this.weaponAtlas,level=Math.max(0,Math.min(3,hero.equipment.spear||0));if(!level||!atlas||!atlas.ready)return false;const cellWidth=atlas.width/3,cellHeight=atlas.height/3,halfWidth=cellWidth/2,frame=Math.max(0,Math.min(3,hero.frame||0)),state=hero.state==='cast'?'attack':hero.state;
      const poses={idle:[[[-17,-34,-.18,1],[17,-34,.18,-1]],[[-18,-35,-.12,1],[18,-34,.12,-1]],[[-17,-34,-.2,1],[17,-35,.2,-1]],[[-18,-34,-.13,1],[18,-34,.13,-1]]],walk:[[[-20,-35,-.42,1],[16,-30,.25,-1]],[[-15,-31,-.15,1],[20,-37,.38,-1]],[[-20,-34,-.35,1],[15,-31,.18,-1]],[[-15,-31,-.12,1],[21,-36,.35,-1]]],attack:[[[-25,-63,-1.18,1],[13,-31,.25,-1]],[[-10,-65,-1.02,1],[18,-28,.4,-1]],[[31,-43,1.02,1],[20,-31,.58,-1]],[[32,-57,.72,1],[10,-23,.25,-1]]]}[state]||null;if(!poses)return false;const sy=atlas.height*2/3,sx=(level-1)*cellWidth,weaponHeight=level===1?30:34,weaponWidth=weaponHeight*.72;
      poses[frame].forEach(function(p,index){ctx.save();ctx.translate(p[0],p[1]);ctx.rotate(p[2]+Math.PI);ctx.scale(p[3],1);ctx.shadowColor=ns.systems.EquipmentSystem.weapon(hero).color;ctx.shadowBlur=level>=2?4:0;ctx.drawImage(atlas,sx+index*halfWidth,sy,halfWidth,cellHeight,-weaponWidth*.12,-weaponHeight*.86,weaponWidth,weaponHeight);ctx.restore();});return true;}
    drawClassWeapon(ctx,hero){const atlas=this.weaponAtlas,level=Math.max(0,Math.min(3,hero.equipment.spear||0));if(!level||!atlas||!atlas.ready)return false;if(hero.classType==='rogue')return this.drawRogueWeapons(ctx,hero);const cellWidth=atlas.width/3,cellHeight=atlas.height/3,row=hero.classType==='hunter'?0:1,frame=Math.max(0,Math.min(3,hero.frame||0)),state=hero.state==='cast'?'attack':hero.state,poses={hunter:{idle:[[18,-38,.06],[18,-37,.03],[17,-38,.08],[19,-37,.04]],walk:[[18,-36,.02],[16,-35,.08],[18,-37,.02],[17,-35,.08]],attack:[[20,-39,-.05],[21,-39,-.02],[23,-40,.02],[22,-39,-.03]]},arcanist:{idle:[[20,-42,-.72],[20,-41,-.68],[19,-42,-.74],[21,-41,-.7]],walk:[[20,-40,-.76],[19,-39,-.7],[21,-41,-.74],[19,-39,-.68]],attack:[[18,-43,-.78],[20,-44,-.72],[23,-42,-.62],[20,-42,-.7]]}}[hero.classType],pose=(poses[state]||poses.idle)[frame],weaponHeight=hero.classType==='hunter'?50:62,weaponWidth=weaponHeight*(cellWidth/cellHeight);ctx.save();ctx.translate(pose[0],pose[1]);ctx.rotate(pose[2]);ctx.shadowColor=ns.systems.EquipmentSystem.weapon(hero).color;ctx.shadowBlur=level>=2?7:3;ctx.drawImage(atlas,(level-1)*cellWidth,row*cellHeight,cellWidth,cellHeight,-weaponWidth/2,-weaponHeight/2,weaponWidth,weaponHeight);ctx.restore();return true;}
    drawHero(ctx,hero){let image=hero.classType==='hunter'?this.heroHunter:hero.classType==='rogue'?this.heroRogue:this.hero;const level=hero.equipment.spear||0,unarmed={hunter:this.heroHunterUnarmed,arcanist:this.heroArcanistUnarmed,rogue:this.rogueUnarmed}[hero.classType],layered=level>0&&unarmed&&unarmed.ready&&this.weaponAtlas&&this.weaponAtlas.ready;if(layered)image=unarmed;if(!image||!image.ready)return false;const sw=image.width/4,sh=image.height/4,row={idle:0,walk:1,attack:2,cast:hero.classType&&hero.classType!=='arcanist'?2:3}[hero.state]||0,height=112,width=height*sw/sh;ctx.save();ctx.translate(hero.x,hero.y);if(Math.cos(hero.facing)<0)ctx.scale(-1,1);ctx.drawImage(image,hero.frame*sw,row*sh,sw,sh,-width/2,-height*.8,width,height);if(layered)this.drawClassWeapon(ctx,hero);this.drawGearPieces(ctx,hero,false);ctx.restore();return true;}
    drawRank(ctx,x,y,level,color,building,type){
      if(level<2)return;ctx.save();ctx.translate(x,y);ctx.strokeStyle='#dfc67c';ctx.fillStyle=color;ctx.lineWidth=2;
      if(building){for(let side=-1;side<=1;side+=2){if(side===1&&level<3)continue;ctx.beginPath();ctx.moveTo(side*34,12);ctx.lineTo(side*34,-47-level*2);ctx.stroke();ctx.beginPath();ctx.moveTo(side*34,-47-level*2);ctx.lineTo(side*34+side*15,-40-level*2);ctx.lineTo(side*34,-27-level*2);ctx.closePath();ctx.fill();ctx.stroke();}}
      if(!building){ctx.fillStyle='#cfb875';for(let side=-1;side<=1;side+=2){ctx.beginPath();ctx.moveTo(side*12,-43);ctx.lineTo(side*(18+level),-36);ctx.lineTo(side*13,-30);ctx.closePath();ctx.fill();}ctx.fillStyle=color;}
      if(level>=3){ctx.globalAlpha=.65;ctx.beginPath();ctx.ellipse(0,16,building?42:27,building?15:10,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}
      if(level>=4){ctx.shadowColor=color;ctx.shadowBlur=9;const count=level===5?5:3;for(let i=0;i<count;i++){const px=(i-(count-1)/2)*9,py=building?-76:-67;ctx.beginPath();ctx.moveTo(px,py-5);ctx.lineTo(px+3,py);ctx.lineTo(px,py+5);ctx.lineTo(px-3,py);ctx.closePath();ctx.fill();}ctx.shadowBlur=0;}
      for(let i=0;i<level-1;i++){const px=(i-(level-2)/2)*8;ctx.fillStyle='#f4d67d';ctx.fillRect(px-2,building?24:22,4,3);}
      ctx.restore();
    }
    drawBuilding(ctx,type,x,y,level,branch){const reinforcementColumn={ballista:0,moonwell:1,plague:2}[type];if(reinforcementColumn!==undefined){const image=this.factionTowersV2;if(!image.ready)return false;const tier=level>=5?2:level>=3?1:0,sw=image.width/3,sh=image.height/3,h=114,w=h*sw/sh;ctx.drawImage(image,reinforcementColumn*sw,tier*sh,sw,sh,x-w/2,y-89,w,h);this.drawRank(ctx,x,y,level,ns.config.buildings[type].color,true,type);return true;}const structureColumn={barracks:0,grove:1,graveyard:2}[type];if(structureColumn!==undefined){const image=this.factionStructures;if(!image.ready)return false;const tier=level>=5?2:level>=3?1:0,sw=image.width/3,sh=image.height/3,h=118,w=h*sw/sh;ctx.drawImage(image,structureColumn*sw,tier*sh,sw,sh,x-w/2,y-91,w,h);this.drawRank(ctx,x,y,level,ns.config.buildings[type].color,true,type);return true;}const factionColumn={storm:0,totem:1,crypt:2,soul:2}[type];if(factionColumn!==undefined){const image=this.factionTowers;if(!image.ready)return false;const tier=level>=5?2:level>=3?1:0,rows=[0,.311,.624,1],sy=rows[tier]*image.height,sh=(rows[tier+1]-rows[tier])*image.height,sw=image.width/3,h=112,w=h*sw/sh;ctx.drawImage(image,factionColumn*sw,sy,sw,sh,x-w/2,y-87,w,h);if(type==='soul'){ctx.save();ctx.globalCompositeOperation='screen';ctx.fillStyle='#e487ff';ctx.globalAlpha=.7;ctx.beginPath();ctx.arc(x,y-56,8+level,0,Math.PI*2);ctx.fill();ctx.restore();}this.drawRank(ctx,x,y,level,ns.config.buildings[type].color,true,type);return true;}if(!this.towers.ready)return false;const column={arrow:0,frost:1,cannon:2}[type];if(column===undefined)return false;const sw=this.towers.width/3;const scale=1+Math.min(4,(level||1)-1)*.035;ctx.drawImage(this.towers,column*sw,0,sw,this.towers.height,x-53*scale,y-79*scale,106*scale,106*scale);this.drawRank(ctx,x,y,level,ns.config.buildings[type].color,true,type);return true;}
    drawMonster(ctx,monster){const base=monster.visualBase||monster.type,image=this.enemyActions[base];if(!image||!image.ready)return false;const sw=image.width/4,sh=image.height/4,frame=Math.max(0,monster.frame||0),action=monster.state==='hit'||monster.state==='attack'||monster.state==='cast',row=monster.state==='death'?3:action?2:Math.floor(frame/4),column=frame%4,h={grunt:78,runner:72,brute:98,shaman:90,healer:92,boss:126}[base],w=h*sw/sh;ctx.save();ctx.translate(monster.x,monster.y);ctx.fillStyle='rgba(0,0,0,.25)';ctx.beginPath();ctx.ellipse(0,2,monster.radius,monster.radius*.38,0,0,Math.PI*2);ctx.fill();if(Math.cos(monster.facing)<0)ctx.scale(-1,1);ctx.drawImage(image,column*sw,row*sh,sw,sh,-w/2,-h*.96,w,h);ctx.restore();if(monster.type==='warder'){ctx.save();ctx.strokeStyle='#78c8ff';ctx.globalAlpha=monster.maxBarrier?(.35+.65*monster.barrier/monster.maxBarrier):.35;ctx.lineWidth=3;ctx.beginPath();ctx.arc(monster.x,monster.y-10,monster.radius+8,-2.5,.7);ctx.stroke();ctx.restore();}else if(monster.type==='healer'){ctx.save();ctx.fillStyle='#8df0a0';ctx.strokeStyle='#183b25';ctx.lineWidth=2;ctx.fillRect(monster.x-3,monster.y-74,6,18);ctx.fillRect(monster.x-9,monster.y-68,18,6);ctx.strokeRect(monster.x-3,monster.y-74,6,18);ctx.restore();}else if(monster.type==='commander'){ctx.save();ctx.strokeStyle='#4a281a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(monster.x+13,monster.y-8);ctx.lineTo(monster.x+13,monster.y-75);ctx.stroke();ctx.fillStyle='#d86345';ctx.beginPath();ctx.moveTo(monster.x+14,monster.y-73);ctx.lineTo(monster.x+38,monster.y-64);ctx.lineTo(monster.x+14,monster.y-50);ctx.closePath();ctx.fill();ctx.restore();}return true;}
    drawUnit(ctx,type,x,y,size){if(!this.units.ready)return false;const cells={hero:[0,0],grunt:[1,0],runner:[2,0],brute:[0,1],shaman:[1,1],boss:[2,1]};const cell=cells[type];if(!cell)return false;const sw=this.units.width/3,sh=this.units.height/2;ctx.drawImage(this.units,cell[0]*sw,cell[1]*sh,sw,sh,x-size/2,y-size*.62,size,size);return true;}
    drawKeep(ctx,x,y,size){if(!this.keep.ready)return false;ctx.drawImage(this.keep,x-size/2,y-size*.58,size,size*.925);return true;}
  }
  ns.systems.ArtSystem=ArtSystem;
})(globalThis.TowerFrontier);
