(function(ns){
  'use strict';
  function segmentDistance(px,py,a,b){const dx=b.x-a.x,dy=b.y-a.y,length=dx*dx+dy*dy;if(!length)return Math.hypot(px-a.x,py-a.y);const t=Math.max(0,Math.min(1,((px-a.x)*dx+(py-a.y)*dy)/length));return Math.hypot(px-(a.x+t*dx),py-(a.y+t*dy));}
  class NavigationSystem{
    constructor(cellSize){this.cellSize=cellSize||30;this.columns=Math.ceil(ns.config.width/this.cellSize);this.rows=Math.ceil(ns.config.height/this.cellSize);this.marginTop=48;this.obstacleRadius=46;}
    clampPoint(point){return{x:ns.utils.clamp(point.x,24,ns.config.width-24),y:ns.utils.clamp(point.y,this.marginTop+12,ns.config.height-24)};}
    cell(point){return{x:Math.max(0,Math.min(this.columns-1,Math.floor(point.x/this.cellSize))),y:Math.max(0,Math.min(this.rows-1,Math.floor(point.y/this.cellSize)))};}
    center(cell){return{x:cell.x*this.cellSize+this.cellSize/2,y:cell.y*this.cellSize+this.cellSize/2};}
    key(cell){return cell.x+','+cell.y;}
    isBlocked(cell,buildings){const p=this.center(cell);if(p.x<24||p.x>ns.config.width-24||p.y<this.marginTop+12||p.y>ns.config.height-24)return true;return (buildings||[]).some(function(building){return ns.utils.distance(p,building)<this.obstacleRadius;},this);}
    nearestOpen(cell,buildings){if(!this.isBlocked(cell,buildings))return cell;for(let radius=1;radius<6;radius+=1){for(let y=-radius;y<=radius;y+=1){for(let x=-radius;x<=radius;x+=1){if(Math.abs(x)!==radius&&Math.abs(y)!==radius)continue;const candidate={x:cell.x+x,y:cell.y+y};if(candidate.x>=0&&candidate.x<this.columns&&candidate.y>=0&&candidate.y<this.rows&&!this.isBlocked(candidate,buildings))return candidate;}}}return null;}
    segmentClear(a,b,buildings){if(a.y<this.marginTop||b.y<this.marginTop)return false;return !(buildings||[]).some(function(building){return segmentDistance(building.x,building.y,a,b)<this.obstacleRadius;},this);}
    neighbors(cell,buildings){const result=[];for(let y=-1;y<=1;y+=1){for(let x=-1;x<=1;x+=1){if(!x&&!y)continue;const next={x:cell.x+x,y:cell.y+y};if(next.x<0||next.x>=this.columns||next.y<0||next.y>=this.rows||this.isBlocked(next,buildings))continue;if(x&&y&&(this.isBlocked({x:cell.x+x,y:cell.y},buildings)||this.isBlocked({x:cell.x,y:cell.y+y},buildings)))continue;result.push({cell:next,cost:x&&y?Math.SQRT2:1});}}return result;}
    simplify(points,buildings){if(points.length<3)return points;const result=[points[0]];let anchor=0;while(anchor<points.length-1){let next=points.length-1;while(next>anchor+1&&!this.segmentClear(points[anchor],points[next],buildings))next-=1;result.push(points[next]);anchor=next;}return result;}
    findPath(start,end,buildings){start=this.clampPoint(start);end=this.clampPoint(end);if(this.segmentClear(start,end,buildings))return[end];const startCell=this.nearestOpen(this.cell(start),buildings),endCell=this.nearestOpen(this.cell(end),buildings);if(!startCell||!endCell)return[];const open=[startCell],came=new Map(),g=new Map([[this.key(startCell),0]]),closed=new Set();while(open.length){open.sort(function(a,b){const ag=g.get(this.key(a))??Infinity,bg=g.get(this.key(b))??Infinity;return ag+Math.hypot(a.x-endCell.x,a.y-endCell.y)-(bg+Math.hypot(b.x-endCell.x,b.y-endCell.y));}.bind(this));const current=open.shift(),currentKey=this.key(current);if(current.x===endCell.x&&current.y===endCell.y){const cells=[current];let key=currentKey;while(came.has(key)){const previous=came.get(key);cells.unshift(previous);key=this.key(previous);}const points=[start].concat(cells.slice(1).map(this.center.bind(this)),[this.center(endCell)]);if(!this.isBlocked(this.cell(end),buildings))points[points.length-1]=end;return this.simplify(points,buildings).slice(1);}closed.add(currentKey);this.neighbors(current,buildings).forEach(function(entry){const key=this.key(entry.cell);if(closed.has(key))return;const score=(g.get(currentKey)??0)+entry.cost;if(score<(g.get(key)??Infinity)){came.set(key,current);g.set(key,score);if(!open.some(function(item){return item.x===entry.cell.x&&item.y===entry.cell.y;}))open.push(entry.cell);}},this);}return[];}
  }
  ns.systems.NavigationSystem=NavigationSystem;
})(globalThis.TowerFrontier);
