(function(ns){
  'use strict';
  const KEY='chapter1-border-onboarding-v3',MISSION_ID='chapter1-border';
  const COPY={
    route:{eyebrow:'第一章 · 新手引導 1／14',title:'先看懂防線',body:'敵軍會沿紅色道路前進；別讓他們抵達金色城門。',next:'了解道路'},
    resources:{eyebrow:'第一章 · 新手引導 2／14',title:'先認識你的資源',body:'金幣用於部署與升級，木材是進階守軍與建築的材料；每波守成會補給資源。先看懂用途，不需要現在計算數值。',next:'知道資源用途',focus:'.td-header .resource'},
    deploy:{eyebrow:'第一章 · 新手引導 3／14',title:'部署第一名守軍',body:'請直接按下方亮起的「王國獵手」卡；接著點草地上的發光圓心完成部署。',focus:'#td-build-drawer [data-build-kind="unit"][data-build-type="hunter"]'},
    shop:{eyebrow:'第一章 · 新手引導 4／14',title:'先準備一項武器強化',body:'新兵補給已讓你有足夠金幣。按亮起的商城入口；開啟商城時戰鬥會暫停。',focus:'#td-shop-open'},
    shopBuy:{eyebrow:'第一章 · 新手引導 5／14',title:'實際購買一次武器',body:'請按亮起的「職業武器鍛造」。它會立刻強化英雄的普攻與傷害技能；這次操作不需要猜該買哪一項。',focus:'#td-shop-screen [data-shop-item="spear"]'},
    ready:{eyebrow:'第一章 · 新手引導 6／14',title:'由你決定開戰時機',body:'每一波開始前都有倒數，倒數結束會自動開戰；準備好時，按這個按鈕可立即提前開戰。',focus:'#td-wave-button'},
    combat:{eyebrow:'第一章 · 新手引導 6／14',title:'觀察第一場擊倒',body:'首批是輕裝斥候，獵手的箭能明確擊倒他們。下一波才會出現較耐打的長戟衛。'},
    selectUnit:{eyebrow:'第一章 · 新手引導 7／14',title:'先選取王國獵手',body:'點擊戰場上被光圈框住、保持原亮度的王國獵手。選到士兵後，才會出現升級、裝備和能力資訊；這一步暫時不能回收他。'},
    upgrade:{eyebrow:'第一章 · 新手引導 8／14',title:'選取守軍後可升級',body:'現在亮起的是升級。也可從選取資訊查看攻擊、射程、攻速與用途；回收仍暫時鎖住。想保留金幣可按下方按鈕繼續。',next:'暫不升級，查看下一波',focus:'#td-upgrade'},
    threat:{eyebrow:'第一章 · 新手引導 9／14',title:'下一波先看敵軍情報',body:'預告會告訴你敵人類型與威脅。快速斥候要提早攔截；長戟衛較耐打，適合讓射程覆蓋更長的彎道。',next:'準備第二波',focus:'#td-wave-hud .wave-forecast'},
    skill:{eyebrow:'第一章 · 新手引導 10／14',title:'試用一次英雄技能',body:'交戰時可按亮起的「召喚援軍」，它不需指定目標，會立即派出援軍協助守線並進入冷卻。你也可直接開始下一波，其他技能不會被鎖住。',focus:'#td-summon'},
    loot:{eyebrow:'第一章 · 新手引導 11／14',title:'第 3 波後會暫停選擇戰利品',body:'軍械波守成會暫停，等待你選一件獎勵；精英敵軍也可能掉落。現在請領取亮起的「獅心王弓」，它會先收入軍械庫。完成或跳過引導後，下一波會恢復倒數。',focus:'#td-loot-options [data-loot-id="gear-lion-bow"]'},
    equip:{eyebrow:'第一章 · 新手引導 12／14',title:'把裝備交給王國獵手',body:'獅心王弓已在軍械庫。獵手已為你選取好，請按亮起的「裝備」開啟他的可用裝備。',focus:'#td-unit-equip'},
    equipPick:{eyebrow:'第一章 · 新手引導 13／14',title:'實際穿上獅心王弓',body:'請按亮起的「裝上」。每名士兵只能穿一件；穿上後會立即提高攻擊、射程與目標數。',focus:'#td-equip-items [data-equip-gear^="lion-bow"]'},
    recycle:{eyebrow:'第一章 · 新手引導 14／14',title:'回收是調整工具，不是必要操作',body:'選取士兵後可看到「回收」，能取回部分金幣以重整防線。本教學暫時鎖住它，避免賣掉唯一守軍；引導結束後才會解鎖。',next:'解除回收鎖定，繼續作戰'}
  };
  class TutorialSystem{
    constructor(game){this.game=game;this.active=false;this.step='';this.storage=null;this.mission=null;this.root=null;this.focused=[];this.lifted=[];this.portals=[];this.awaitingLoot=false;this.lockRecycle=false;}
    activate(mission,storage,{replay=false}={}){this.deactivate();if(!mission||mission.id!==MISSION_ID||(!replay&&storage&&storage.getItem(KEY)))return false;this.active=true;this.mission=mission;this.storage=storage||null;const targetGold=mission.tutorial?.startingGold||0,economy=this.game.economy;if(economy&&targetGold>economy.gold&&typeof economy.addGold==='function'){const grant=economy.addGold(targetGold-economy.gold);this.game.flash?.('新兵補給 +'+grant+'G','#ffe08a');this.game.updateUi?.();}this.game.waves.holdPreparation(true);this.show('route');return true;}
    dismissTutorialModal(){const game=this.game,loot=game?.ui?.lootScreen,picker=typeof document!=='undefined'?document.getElementById('td-equip-screen'):null;if(loot&&!loot.hidden)loot.hidden=true;if(picker&&!picker.hidden){picker.hidden=true;game.equipTarget=null;}if(game){game.paused=false;if(game.ui?.pause){game.ui.pause.textContent='Ⅱ';game.ui.pause.setAttribute('aria-label','暫停遊戲');}}}
    deactivate(){this.active=false;this.step='';this.awaitingLoot=false;this.lockRecycle=false;this.dismissTutorialModal();this.restoreDeployDrawer();this.clearFocus();if(this.game&&this.game.waves)this.game.waves.holdPreparation(false);if(this.root){this.root.element.remove();this.root.dim.remove();this.root.unitFocus.remove();this.root=null;}if(typeof document!=='undefined')delete document.body.dataset.tutorialStep;}
    rootElement(){
      if(this.root||typeof document==='undefined')return this.root;
      const dim=document.createElement('div'),root=document.createElement('aside'),unitFocus=document.createElement('div');dim.id='td-tutorial-dim';dim.hidden=true;root.id='td-tutorial';root.hidden=true;root.setAttribute('aria-live','polite');root.setAttribute('aria-label','新手引導');unitFocus.id='td-tutorial-unit-focus';unitFocus.hidden=true;unitFocus.setAttribute('aria-hidden','true');
      const eyebrow=document.createElement('small'),title=document.createElement('h2'),body=document.createElement('p'),actions=document.createElement('div'),next=document.createElement('button'),skip=document.createElement('button');
      next.type='button';next.className='tutorial-next';skip.type='button';skip.className='tutorial-skip';skip.textContent='跳過引導';next.onclick=()=>this.advance();skip.onclick=()=>this.complete('skipped');actions.append(next,skip);root.append(eyebrow,title,body,actions);document.body.append(dim,unitFocus,root);this.root={element:root,dim,unitFocus,eyebrow,title,body,next,skip};return this.root;
    }
    show(step){
      if(!this.active||!COPY[step])return false;
      this.step=step;if(step==='deploy')this.restoreDeployDrawer();
      const view=this.rootElement(),copy=COPY[step];
      if(view){view.eyebrow.textContent=copy.eyebrow;view.title.textContent=copy.title;view.body.textContent=copy.body;view.next.textContent=copy.next||'';view.next.hidden=!copy.next;view.element.hidden=false;}
      if(typeof document!=='undefined')document.body.dataset.tutorialStep=step;
      this.clearFocus();const target=copy.focus?this.focus(copy.focus):null;if(view&&copy.dim)view.dim.hidden=false;if(view){this.positionUnitFocus();this.positionCard(target);}return true;
    }
    hideCard(){if(this.root)this.root.element.hidden=true;this.clearFocus();if(typeof document!=='undefined')delete document.body.dataset.tutorialStep;}
    focus(selector){if(typeof document==='undefined')return null;const elements=Array.from(document.querySelectorAll(selector));elements.forEach(element=>{element.dataset.tutorialFocus='true';this.focused.push(element);this.portal(element);});if(this.root)this.root.dim.hidden=!elements.length;return elements[0]||null;}
    portal(element){const rect=element.getBoundingClientRect?.();if(!rect||rect.width<1||rect.height<1||!element.parentNode)return;const placeholder=document.createElement('span'),style=element.getAttribute('style'),computed=globalThis.getComputedStyle?.(element),visual=['display','align-items','justify-content','grid-template-columns','grid-template-rows','gap','padding','border','border-radius','background','color','font','font-size','font-weight','line-height','text-align','white-space','box-shadow'];placeholder.setAttribute('aria-hidden','true');placeholder.style.cssText='display:block;visibility:hidden;flex:0 0 '+rect.width+'px;width:'+rect.width+'px;height:'+rect.height+'px;';visual.forEach(property=>{const value=computed?.getPropertyValue(property);if(value)element.style.setProperty(property,value,'important');});const buildCard=Boolean(element.dataset.buildType);if(buildCard)element.classList.add('tutorial-portal-build-card');element.parentNode.replaceChild(placeholder,element);element.dataset.tutorialPortal='true';element.style.setProperty('position','fixed','important');element.style.setProperty('z-index','101','important');element.style.setProperty('left',rect.left+'px','important');element.style.setProperty('top',rect.top+'px','important');element.style.setProperty('width',rect.width+'px','important');element.style.setProperty('height',rect.height+'px','important');element.style.setProperty('margin','0','important');element.style.setProperty('transform','none','important');document.body.append(element);this.portals.push({element,placeholder,style,buildCard});}
    clearFocus(){this.portals.splice(0).reverse().forEach(({element,placeholder,style,buildCard})=>{delete element.dataset.tutorialPortal;if(buildCard)element.classList.remove('tutorial-portal-build-card');if(style===null)element.removeAttribute('style');else element.setAttribute('style',style);if(placeholder.parentNode)placeholder.replaceWith(element);});this.focused.splice(0).forEach(element=>delete element.dataset.tutorialFocus);this.lifted.splice(0).forEach(element=>delete element.dataset.tutorialLifted);if(this.root){this.root.dim.hidden=true;this.root.unitFocus.hidden=true;this.root.element.style.left='50%';this.root.element.style.top='24px';this.root.element.style.transform='translateX(-50%)';}}
    positionUnitFocus(){if(!this.root||this.step!=='selectUnit')return;const unit=this.game.build?.items?.find(item=>item.kind==='unit'&&item.type==='hunter'),canvas=this.game.canvas;if(!unit||!canvas)return;const rect=canvas.getBoundingClientRect(),camera=this.game.camera,point=camera?.enabled?camera.worldToScreen(unit.x,unit.y):{x:unit.x/(ns.config.width||1)*rect.width,y:unit.y/(ns.config.height||1)*rect.height},radius=Math.max(42,Math.min(58,rect.width*.04));this.root.unitFocus.hidden=false;this.root.unitFocus.style.width=radius*2+'px';this.root.unitFocus.style.height=radius*2+'px';this.root.unitFocus.style.left=rect.left+point.x-radius+'px';this.root.unitFocus.style.top=rect.top+point.y-radius+'px';}
    positionCard(target){if(!this.root||typeof window==='undefined')return;const card=this.root.element,edgeStep=['route','deploy','ready','combat'].includes(this.step);if(edgeStep){card.style.width='min(310px,calc(100vw - 24px))';card.style.left='12px';card.style.top=this.step==='combat'?Math.max(112,window.innerHeight-(card.offsetHeight||150)-16)+'px':'112px';card.style.transform='none';return;}card.style.width='min(460px,calc(100vw - 32px))';if(!target){card.style.left='16px';card.style.top='112px';card.style.transform='none';return;}const rect=target.getBoundingClientRect(),width=Math.min(460,window.innerWidth-32),height=card.offsetHeight||164,top=rect.bottom+16+height<=window.innerHeight-16?rect.bottom+16:Math.max(16,rect.top-height-16),left=Math.max(16,Math.min(window.innerWidth-width-16,rect.left+rect.width/2-width/2));card.style.left=left+'px';card.style.top=top+'px';card.style.transform='none';}
    releasePreparation(){this.lockRecycle=false;this.game.waves.holdPreparation(false);this.hideCard();this.game.updateUi();}
    advance(){if(!this.active)return false;if(this.step==='route'){this.show('resources');return true;}if(this.step==='resources'){this.show('deploy');return true;}if(this.step==='upgrade'){this.show('threat');return true;}if(this.step==='threat'){this.releasePreparation();return true;}if(this.step==='recycle')return this.complete('completed');return false;}
    restoreDeployDrawer(){const drawer=this.game?.ui?.buildDrawer;if(drawer)drawer.style.removeProperty('display');}
    onDeployQueued(type,kind){if(!this.active||this.step!=='deploy'||type!=='hunter'||kind!=='unit')return false;this.hideCard();return true;}
    onDeploy(){if(!this.active||!['route','deploy'].includes(this.step))return false;this.restoreDeployDrawer();this.show('shop');return true;}
    onShopOpened(){if(!this.active||this.step!=='shop')return false;this.show('shopBuy');return true;}
    onShopPurchase(id){if(!this.active||this.step!=='shopBuy'||id!=='spear')return false;this.game.closeShop?.();this.show('ready');return true;}
    requestStart(){if(!this.active)return true;if(this.step==='ready'){this.game.waves.holdPreparation(false);this.show('combat');return true;}if(this.step==='deploy'||this.step==='route'){this.show('deploy');return false;}if(this.step==='skill'){this.step='skillDone';this.hideCard();return true;}return this.step==='combat'||this.step==='skillDone';}
    onWaveStart(wave){if(!this.active)return;if(wave===1&&this.step==='ready')this.show('combat');else if(wave===2&&this.step==='threat')this.show('skill');else if(wave>=3&&this.step==='skill'){this.step='skillDone';this.hideCard();}}
    onFirstKill(){if(this.active&&this.step==='combat')this.hideCard();}
    onWaveClear(wave){if(!this.active)return;if(wave===1){this.lockRecycle=true;this.game.waves.holdPreparation(true);this.show('selectUnit');}else if(wave===3){this.game.waves.holdPreparation(true);this.awaitingLoot=true;if(!this.game.openLoot||!this.game.openLoot(3))this.onLootClaim('gear-lion-bow');else this.show('loot');}}
    onUnitSelected(unit){if(!this.active||this.step!=='selectUnit'||unit?.kind!=='unit'||unit.type!=='hunter')return false;this.show('upgrade');return true;}
    onUpgrade(){if(this.active&&this.step==='upgrade')this.show('threat');}
    onHeroSkill(){if(!this.active||this.step!=='skill')return false;this.step='skillDone';this.hideCard();return true;}
    onLootClaim(id){if(!this.active||!this.awaitingLoot||id!=='gear-lion-bow')return false;this.awaitingLoot=false;this.lockRecycle=true;const hunter=this.game.build?.items?.find(item=>item.kind==='unit'&&item.type==='hunter');if(hunter){this.game.build.selected=hunter;if(this.game.hero)this.game.hero.selected=false;this.game.updateUi?.();}this.game.waves.holdPreparation(true);this.show('equip');return true;}
    onEquipmentPickerOpened(){if(!this.active||this.step!=='equip')return false;this.show('equipPick');return true;}
    onEquipmentEquipped(id,target){const gearId=String(id||'').replace(/#\d+$/,'');if(!this.active||this.step!=='equipPick'||gearId!=='lion-bow'||target?.type!=='hunter')return false;this.show('recycle');return true;}
    complete(reason){if(!this.active)return false;try{this.storage?.setItem(KEY,reason||'completed');}catch(error){this.game.flash('引導進度尚未儲存，仍可繼續遊玩','#ffb578');}this.deactivate();this.game.updateUi();return true;}
    draw(ctx){this.drawWithTransform(ctx,point=>point);}
    drawScreen(ctx){const camera=this.game.camera;if(!camera||!camera.enabled)return this.draw(ctx);const canvas=this.game.canvas,toScreen=point=>camera.worldToScreen(point.x,point.y);ctx.save();ctx.scale(canvas.width/camera.width,canvas.height/camera.height);this.drawWithTransform(ctx,toScreen);ctx.restore();}
    drawWithTransform(ctx,toScreen){if(!this.active)return;this.positionUnitFocus();const path=ns.config.path||[];if(this.step==='route'&&path.length>1){const start=toScreen(path[0]);ctx.save();ctx.strokeStyle='#ff5d4f';ctx.shadowColor='#ff493b';ctx.shadowBlur=22;ctx.lineWidth=13;ctx.globalAlpha=.45;ctx.beginPath();ctx.moveTo(start.x,start.y);path.slice(1).forEach(point=>{const screen=toScreen(point);ctx.lineTo(screen.x,screen.y);});ctx.stroke();ctx.globalAlpha=1;ctx.lineWidth=3;ctx.setLineDash([13,10]);ctx.strokeStyle='#ffe1ab';ctx.stroke();ctx.setLineDash([]);const gate=toScreen(path[path.length-1]);ctx.fillStyle='#ffe4a0';ctx.beginPath();ctx.arc(gate.x,gate.y,30,0,Math.PI*2);ctx.fill();ctx.restore();}if(this.step==='deploy'){const points=this.mission?.tutorial?.recommendedPositions||[];ctx.save();points.forEach(point=>{const screen=toScreen(point),radius=point.radius||18;ctx.strokeStyle='#91ffd1';ctx.fillStyle='#54e4ad55';ctx.shadowColor='#74f7c1';ctx.shadowBlur=18;ctx.lineWidth=4;ctx.beginPath();ctx.arc(screen.x,screen.y,radius,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#dfffe9';ctx.beginPath();ctx.arc(screen.x,screen.y,4,0,Math.PI*2);ctx.fill();});ctx.restore();}}
    static reset(storage){if(storage)storage.removeItem(KEY);}
  }
  TutorialSystem.KEY=KEY;TutorialSystem.MISSION_ID=MISSION_ID;ns.systems.TutorialSystem=TutorialSystem;
})(globalThis.TowerFrontier);
