(function(ns){
  'use strict';
  const mission={id:'chapter1-border',chapter:1,name:'烽火初燃',map:'beginner',hero:'hunter',faction:'hunter',difficulty:'story',objective:'守住谷地城門，完成 5 波王國叛軍的新兵演練。',rewards:{maps:['twinpass','silverleaf']},discovered:['kingdom-rebellion'],tutorial:{startingGold:400,recommendedPositions:[{x:680,y:415,radius:34}]},cinematic:['邊境的烽火，比信使先抵達王城。','昔日守衛商路的長戟衛，如今將兵鋒指向谷地。雷恩奉命守住城門，查清叛亂的源頭。','部署王國士兵守住道路，使用陷阱拖慢重甲叛軍。城門還在，希望就還在。']};
  mission.storyCards=[
    {title:'烽火初燃',label:'谷地 · 戰前',line:'邊境烽火亮起。信使還沒抵達。',image:'assets/td/story/kingdom-border-at-dusk-v2.png',focus:'center'},
    {title:'同一面旗',label:'雷恩',line:'「對面也是王國士兵。為何刀要指向自己人？」',image:'assets/td/story/rhen-oathkeeper-v2.png',focus:'center'},
    {title:'守住城門',label:'此刻的選擇',line:'先守住谷地，才有機會查清命令從何而來。',image:'assets/td/story/kingdom-checkpoint-order-v2.png',focus:'center'}
  ];
  mission.aftermath='守住谷地後，殘缺的命令名冊留下更多空白。叛軍不是答案；有人正在利用王國的混亂。';
  const waves=[{name:'谷地斥候',hint:'首批輕裝斥候會讓你看見王國獵手確實能擊倒敵軍',groups:[{type:'grunt',count:4}],spawnPace:4},{name:'叛軍試探',hint:'快速斥候與重甲衛混編，確認守軍射程能覆蓋彎道',groups:[{type:'runner',count:5},{type:'halberdier',count:3}]},{name:'軍械補給',hint:'守成後會取得第一件可裝備軍械，選獵手查看相容裝備',groups:[{type:'halberdier',count:6},{type:'fallenKnight',count:2}]},{name:'彎道壓力',hint:'敵人數量增加；從選取資訊比較升級、增兵與防禦塔',groups:[{type:'runner',count:7},{type:'halberdier',count:5}]},{name:'谷地守望',hint:'最後一波綜合演練，先看預告再補足城門前火力',groups:[{type:'fallenKnight',count:4},{type:'halberdier',count:7}]}];
  const silverleaf={id:'chapter1-silverleaf',chapter:1,name:'溪谷餘音',map:'silverleaf',hero:'hunter',faction:'hunter',difficulty:'story',requires:mission.id,objective:'沿溪谷守住 6 波追兵，讓調查隊取得銀葉保留的舊日記錄。',rewards:{maps:['shadowfall']},discovered:['silverleaf-record'],cinematic:['溪水仍清澈，昔日盟約卻開始動搖。','王國調查隊進入銀葉溪谷，尋找能解釋衝突的記錄。這些線索尚不足以判定兇手。','守住橋樑，讓記錄安全離開溪谷。'],waves:[{name:'橋前斥候',hint:'先守第一座橋，讓基礎火力覆蓋入口',groups:[{type:'grunt',count:5}]},{name:'溪谷包抄',hint:'中央草地可照顧兩段道路',groups:[{type:'runner',count:5},{type:'halberdier',count:3}]},{name:'橋頭重隊',hint:'重甲衛增加，補上能處理重甲的火力',groups:[{type:'grunt',count:6},{type:'halberdier',count:4}]},{name:'疾行追兵',hint:'高速敵人會穿過空檔，別只守單一彎道',groups:[{type:'runner',count:6},{type:'fallenKnight',count:3}]},{name:'術士掩護',hint:'優先處理後排術士，避免前線被持續消耗',groups:[{type:'runner',count:4},{type:'halberdier',count:5},{type:'shaman',count:3}]},{name:'溪谷撤離',hint:'最後一波混編重甲騎士；在城門前留下補漏火力',groups:[{type:'fallenKnight',count:4},{type:'halberdier',count:6}]}]};
  silverleaf.storyCards=[
    {title:'溪谷餘音',label:'銀葉溪谷 · 抵達',line:'溪谷仍守著舊日的安靜，卻再也無法把戰火隔在外面。',image:'assets/td/story/silverleaf-valley-arrival-v2.png',focus:'center'},
    {title:'被保存的記憶',label:'調查記錄',line:'這份舊盟約證明曾有合作；它仍沒有告訴我們，誰毀了和平。',image:'assets/td/story/silverleaf-record-study-v2.png',focus:'center'},
    {title:'橋上的撤離',label:'護送',line:'記錄必須安全離開溪谷，調查才有下一步。',image:'assets/td/story/silverleaf-bridge-escort-v2.png',focus:'center'}
  ];
  silverleaf.aftermath='舊記錄提到銀葉與暮影曾共同封存危險的技術。那只是恐懼的歷史，仍不足以判定王子之死。';
  const shadowfall={id:'chapter1-shadowfall',chapter:1,name:'舊城疑雲',map:'shadowfall',hero:'hunter',faction:'hunter',difficulty:'story',requires:silverleaf.id,objective:'在暮影舊城守住 7 波撤離道路，尋找與禁忌歷史相關的證言。',rewards:{maps:['frostborn']},discovered:['shadowfall-ruins'],cinematic:['暮影舊城的廢墟，仍留著人們急於遺忘的聲音。','調查隊來到舊城尋找證言；現場痕跡不能直接證明任何族群有罪。','在中央廣場設防，守住唯一的撤離道路。'],waves:[{name:'舊城追兵',hint:'前段與中央廣場擇一先佈防',groups:[{type:'grunt',count:7},{type:'runner',count:4}]},{name:'暗巷威脅',hint:'中央廣場可覆蓋彎道，但別忘記後段',groups:[{type:'runner',count:6},{type:'shaman',count:2}]},{name:'失誓巡隊',hint:'騎士帶著步兵壓境，別讓重甲擠過彎道',groups:[{type:'grunt',count:5},{type:'fallenKnight',count:3}]},{name:'怨靈穿行',hint:'秘法敵人會逼近防線，留意輸出死角',groups:[{type:'revenant',count:4},{type:'runner',count:5}]},{name:'術士與巨獸',hint:'先處理術士，再用集中火力擊倒岩甲巨獸',groups:[{type:'halberdier',count:4},{type:'shaman',count:3},{type:'brute',count:2}]},{name:'舊城崩口',hint:'巨獸和騎士同時推進，城門前必須有第二層防線',groups:[{type:'fallenKnight',count:4},{type:'brute',count:3}]},{name:'證言撤離',hint:'最終混編會同時考驗群攻、單點與城門補漏',groups:[{type:'revenant',count:5},{type:'shaman',count:3},{type:'brute',count:2}]}]};
  shadowfall.storyCards=[
    {title:'舊城疑雲',label:'暮影舊城 · 證言',line:'被懷疑的人們也在等答案。調查不是審判。',image:'assets/td/story/shadowfall-testimony-v2.png',focus:'center'},
    {title:'封存的遺物',label:'禁忌歷史',line:'遺物來自被遺忘的年代；它的來源與用途，仍無法定論。',image:'assets/td/story/shadowfall-archive-reliquary-v2.png',focus:'center'},
    {title:'留住證人',label:'撤離道路',line:'先護送證言離開。真相不能再被下一場戰火吞沒。',image:'assets/td/story/shadowfall-evacuation-v2.png',focus:'center'}
  ];
  shadowfall.aftermath='證言與遺物都指向一段被封存的歷史，卻沒有證明現代暮影重啟了禁忌。有人希望調查停在這裡。';
  const frostborn={id:'chapter1-frostborn',chapter:1,name:'裂谷守望',map:'frostborn',hero:'hunter',faction:'hunter',difficulty:'story',requires:shadowfall.id,objective:'守住冰原雙入口匯合後的 8 波長橋，護送線索穿越裂谷。',rewards:{maps:[]},discovered:['frostborn-chasm'],cinematic:['冰原裂谷封住前路，兩處入口都可能出現追兵。','兩路敵軍交替抵達，最終都會走向同一段冰橋。','集中主力守住共用道路，把線索帶出裂谷。'],waves:[{name:'裂谷先鋒',hint:'先在匯流後佈塔，不需要兩邊各蓋一套',groups:[{type:'grunt',count:6},{type:'runner',count:3}]},{name:'雙路追兵',hint:'兩入口交替出兵，匯流後共用同一防線',groups:[{type:'runner',count:5},{type:'halberdier',count:4}]},{name:'冰橋夾擊',hint:'檢查匯流處與城門前的補漏位置',groups:[{type:'fallenKnight',count:3},{type:'grunt',count:7}]},{name:'匯流壓力',hint:'兩路怪會在橋前合流，群攻與減速要提前放好',groups:[{type:'runner',count:6},{type:'halberdier',count:4},{type:'shaman',count:3}]},{name:'裂谷巨獸',hint:'巨獸接近城門時傷害很高，保留技能處理關鍵目標',groups:[{type:'revenant',count:5},{type:'brute',count:3}]},{name:'長橋重隊',hint:'騎士與長戟衛的重甲隊伍，需要集中火力逐個擊破',groups:[{type:'fallenKnight',count:5},{type:'halberdier',count:6}]},{name:'寒風術團',hint:'術士、巨獸與疾行敵人混編，確認兩側入口都被照顧',groups:[{type:'runner',count:5},{type:'shaman',count:4},{type:'brute',count:4}]},{name:'裂谷守望',hint:'最後一波全線壓力；守住匯流後的長橋與城門前防線',groups:[{type:'revenant',count:6},{type:'fallenKnight',count:5},{type:'brute',count:3}]}]};
  frostborn.storyCards=[
    {title:'裂谷守望',label:'冰原裂谷 · 路線',line:'兩條雪路，最後都匯向同一座橋；線索沒有第二條退路。',image:'assets/td/story/frostborn-chasm-route-v2.png',focus:'center'},
    {title:'寒風中的訊號',label:'調查隊',line:'燈火亮起，護送隊跨過冰橋。每一步都在和時間競賽。',image:'assets/td/story/frostborn-bridge-signal-v2.png',focus:'center'},
    {title:'最後的橋頭',label:'守住線索',line:'讓證據先抵達安全處；剩下的人，守住這一段橋。',image:'assets/td/story/frostborn-last-bridge-v2.png',focus:'center'}
  ];
  frostborn.aftermath='線索被帶出裂谷。殘存的調度紀錄顯示，王城裡還有一套不受禁衛軍管轄的命令系統；調查才剛開始。';
  const westernsignal={id:'chapter2-western-signal',chapter:2,name:'西境風號',map:'westernsignal',hero:'hunter',faction:'hunter',difficulty:'story',requires:frostborn.id,objective:'守住 6 波西行古道，護送信使與辨識用的舊印穿過西境舊哨。',rewards:{maps:[]},discovered:['western-signal'],cinematic:['殘缺的調度碼越過了王國邊界，古老路名把調查帶往西方。','荒野斥候認出舊印，卻拒絕在武裝隊伍面前說明；先讓信使安全通過。','守住西境古道，讓對話能在下一段路上繼續。'],waves:[{name:'西境斥候',hint:'古道入口狹長；先讓火力覆蓋第一個彎道。第 2 波起中段會出現荒風隘道。',groups:[{type:'grunt',count:6}]},{name:'荒風追兵',hint:'中段隘道順風 +10%；冰緩、暈眩與陷阱可將其壓低，但不能完全取消。',groups:[{type:'runner',count:6},{type:'halberdier',count:3}]},{name:'舊哨重隊',hint:'古碑旁不能部署；利用兩側平地集中處理重甲',groups:[{type:'grunt',count:7},{type:'fallenKnight',count:3}]},{name:'轉角煙塵',hint:'術士會躲在步兵後方，保留技能處理關鍵窗口',groups:[{type:'runner',count:6},{type:'shaman',count:3},{type:'halberdier',count:4}]},{name:'訊號石壓力',hint:'巨獸進入最後長直道前，補足城門前的第二層火力',groups:[{type:'revenant',count:4},{type:'brute',count:3},{type:'fallenKnight',count:3}]},{name:'護送風號',hint:'最終混編會考驗群攻、單點與補漏；讓信使帶著舊印離開',groups:[{type:'runner',count:7},{type:'shaman',count:4},{type:'brute',count:3},{type:'fallenKnight',count:4}]}]};
  westernsignal.storyCards=[
    {title:'西境風號',label:'西境舊哨 · 線索',line:'殘缺的調度碼越過了王國的邊界。它要帶我們去哪裡？',image:'assets/td/story/chapter2-western-signal-v1.png',focus:'center'},
    {title:'不急著相信',label:'第一次對話',line:'戈爾認得這枚舊印，卻不欠我們答案。先聽完他的條件。',image:'assets/td/story/chapter2-western-parley-v1.png',focus:'center'},
    {title:'護送這條路',label:'西行選擇',line:'讓信使與記錄安全通過，對話才有下一步。',image:'assets/td/story/chapter2-western-passage-v1.png',focus:'center'}
  ];
  westernsignal.aftermath='舊印被辨識為一條更早的中繼路名。荒野斥候同意帶來一位見證者；這是對話的開始，不是對任何勢力的定罪。';
  const emberroad={id:'chapter2-ember-road',chapter:2,name:'燼道相逢',map:'emberroad',hero:'hunter',faction:'hunter',difficulty:'story',requires:westernsignal.id,objective:'守住 7 波燼火商道，救出被追兵截斷的荒野小隊與補給車。',rewards:{maps:[]},discovered:['ember-road'],cinematic:['燒毀的補給車堵在商道旁，倖存者的求救訊號穿過煙塵。','荒野小隊沒有要求被拯救；他們要求先讓受傷者與車隊安全離開。','守住燼火商道。以行動換取第一次能被信任的對話。'],waves:[{name:'煙前斥候',hint:'先守住商道第一個彎；不要把所有火力壓在補給車旁。',groups:[{type:'grunt',count:7}]},{name:'車隊追兵',hint:'快速敵人會趁護送隊整隊逼近，預留一個能照顧中段的防點。',groups:[{type:'runner',count:6},{type:'halberdier',count:4}]},{name:'燼火煙障',hint:'燒毀補給車旁的煙障啟動：敵軍 +2 護甲；緩速、冰凍或定身可壓至 +1。',groups:[{type:'grunt',count:5},{type:'shaman',count:4}]},{name:'高台壓迫',hint:'盾衛與疾行敵人會擠過煙障；以控制拉開處理窗口，別只靠單點輸出。',groups:[{type:'fallenKnight',count:5},{type:'runner',count:4},{type:'warder',count:2}]},{name:'補給車急救',hint:'術士在後方施壓，巨獸則會穿過中段；群攻與單體都要有位置。',groups:[{type:'shaman',count:5},{type:'brute',count:3},{type:'halberdier',count:4}]},{name:'灰燼封路',hint:'重甲、怨靈與巨獸混編；煙障過後仍要在城門前保留補漏。',groups:[{type:'revenant',count:4},{type:'fallenKnight',count:4},{type:'brute',count:4}]},{name:'燼道相逢',hint:'最終護送：高速、秘法與重甲同時抵達。先用控制壓低煙障，再守住最後關口。',groups:[{type:'runner',count:7},{type:'shaman',count:4},{type:'brute',count:4},{type:'fallenKnight',count:4}]}]};
  emberroad.storyCards=[
    {title:'燼道相逢',label:'燼火商道 · 求救',line:'煙塵裡傳來短促的求救訊號；先讓人活下來。',image:'assets/td/ember-road-encounter-v1.png',focus:'48% 38%'},
    {title:'先護送，再交談',label:'荒野小隊',line:'他們不需要被收編；他們需要一條能安全離開的路。',image:'assets/td/ember-road-encounter-v1.png',focus:'54% 48%'},
    {title:'守住商道',label:'此刻的選擇',line:'補給車與受傷者過關後，才有第一次不靠武器的對話。',image:'assets/td/ember-road-encounter-v1.png',focus:'79% 67%'}
  ];
  emberroad.aftermath='小隊同意交換一段被燒毀的路名：他們的祖輩來自南方，但那段遷徙的理由仍不願由陌生人替他們下結論。';
  const stonecircle={id:'chapter2-stone-circle',chapter:2,name:'石環見證',map:'stonecircle',hero:'hunter',faction:'hunter',difficulty:'story',requires:emberroad.id,objective:'守住 8 波石環盆地，讓荒野見證者在古老石陣前說完被掩埋的遷徙記憶。',rewards:{maps:['stonecircle']},discovered:['stone-circle-testimony'],cinematic:['石環不是王國的遺跡，也不是荒野的戰利品；它比今日的邊界更古老。','見證者願意開口，前提是護送隊不再把問題帶進石陣。先守住外環古道。','守住石環，讓記憶成為可以被傾聽的證言，而不是下一場衝突的武器。'],waves:[{name:'石環外哨',hint:'古道繞著石陣外側前進；不要把火力蓋進見證區。',groups:[{type:'grunt',count:8}]},{name:'盆地疾影',hint:'快速敵人會沿外環拉開距離，在兩段彎道各留一個射程。',groups:[{type:'runner',count:7},{type:'halberdier',count:4}]},{name:'立石重列',hint:'長戟衛與騎士前壓，集中火力先打穿重甲隊。',groups:[{type:'halberdier',count:5},{type:'fallenKnight',count:4}]},{name:'火堆背風',hint:'術士躲在前線後方；用英雄技能製造短暫處理窗口。',groups:[{type:'runner',count:6},{type:'shaman',count:4},{type:'grunt',count:5}]},{name:'環道巨影',hint:'巨獸進入外環出口前就要開始承受傷害，別把所有火力留到城門。',groups:[{type:'brute',count:4},{type:'fallenKnight',count:4},{type:'revenant',count:3}]},{name:'斷碑追隊',hint:'盾衛與術士同時出現，先處理能拖長戰線的後排。',groups:[{type:'warder',count:3},{type:'shaman',count:4},{type:'halberdier',count:5}]},{name:'見證者的路',hint:'混編隊伍會拉長外環壓力；以控場保住集中火力區。',groups:[{type:'runner',count:8},{type:'brute',count:4},{type:'revenant',count:4}]},{name:'石環見證',hint:'最後一波守住通往城門的長直道，讓見證者與紀錄安全離開。',groups:[{type:'runner',count:8},{type:'shaman',count:5},{type:'fallenKnight',count:5},{type:'brute',count:4}]}]};
  stonecircle.storyCards=[
    {title:'石環見證',label:'石環盆地 · 抵達',line:'古老石環不替任何一方作證；它只留下願意被傾聽的人。',image:'assets/td/stone-ring-basin-v1.png',focus:'43% 42%'},
    {title:'先放下旗幟',label:'見證者',line:'「我們會說出記得的事，但不讓任何人替我們把它寫成罪名。」',image:'assets/td/story/chapter2-stone-circle-witness-v1.png',focus:'center'},
    {title:'守住外環',label:'護送選擇',line:'讓紀錄穿過盆地；被聽見的記憶，才有機會改變下一步。',image:'assets/td/story/chapter2-stone-circle-witness-v1.png',focus:'70% 52%'}
  ];
  stonecircle.aftermath='見證者確認：南方遷徙不是侵略，而是一場被迫離開故土的求生。被焚毀的中繼站仍留有最後一段可驗證的路名。';
  const redmesa={id:'chapter2-red-mesa',chapter:2,name:'赤土終站',map:'redmesa',hero:'hunter',faction:'hunter',difficulty:'story',requires:stonecircle.id,objective:'守住 9 波赤岩峽橋，護送見證、傷者與紀錄抵達終站關口。',rewards:{maps:['redmesa'],factions:['wild']},discovered:['red-mesa-accord'],cinematic:['赤岩峽橋是最後的中繼站；若護送隊抵達，南方的秘密才有機會被共同查證。','荒野部族不要求王國替他們說話。他們只要求能決定自己的路，並讓傷者活著通過關口。','守住赤土終站。這不是結盟的終點，而是第一次能並肩守住的一段路。'],waves:[{name:'終站前哨',hint:'折返古道很長，先讓第一個高台與中段都能輸出。',groups:[{type:'grunt',count:9}]},{name:'赤岩疾行',hint:'高速敵人會穿越折返空檔，別只投資橋頭。',groups:[{type:'runner',count:8},{type:'halberdier',count:4}]},{name:'遺站殘軍',hint:'重甲隊沿遺站下坡推進，利用彎角完成第一次集火。',groups:[{type:'fallenKnight',count:5},{type:'grunt',count:7}]},{name:'峽橋煙影',hint:'怨靈與術士會拉開處理需求；保留技能擊破後排。',groups:[{type:'revenant',count:5},{type:'shaman',count:4},{type:'runner',count:5}]},{name:'橋頭守望',hint:'盾衛會拖住傷害，先做出穿甲或控制的組合。',groups:[{type:'warder',count:4},{type:'halberdier',count:5},{type:'fallenKnight',count:4}]},{name:'斷崖巨獸',hint:'巨獸跨過峽橋後接近關口很快；第二層防線現在就要成形。',groups:[{type:'brute',count:5},{type:'runner',count:7},{type:'shaman',count:4}]},{name:'最後中繼',hint:'連續混編測試每種火力的角色，避免把資源全壓在單一塔。',groups:[{type:'revenant',count:5},{type:'fallenKnight',count:5},{type:'brute',count:4},{type:'halberdier',count:5}]},{name:'關口之前',hint:'快速敵人與重甲同時進橋，控制技能留給最密集的窗口。',groups:[{type:'runner',count:9},{type:'warder',count:4},{type:'shaman',count:5},{type:'brute',count:4}]},{name:'赤土終站',hint:'最終護送：守住峽橋出口與關口前長直道，讓隊伍一起抵達。',groups:[{type:'runner',count:9},{type:'revenant',count:6},{type:'fallenKnight',count:6},{type:'brute',count:5},{type:'shaman',count:5}]}]};
  redmesa.storyCards=[
    {title:'赤土終站',label:'赤岩峽橋 · 最後一段路',line:'這座橋不該只通往關口；它也該通往能共同查證的明天。',image:'assets/td/red-mesa-terminus-v1.png',focus:'51% 43%'},
    {title:'各自決定自己的路',label:'終站關口',line:'沒有誰替誰宣告答案。先讓傷者、見證與紀錄安全抵達。',image:'assets/td/story/chapter2-red-mesa-dawn-v1.png',focus:'center'},
    {title:'並肩守住黎明',label:'荒野的回聲',line:'這不是終戰；但從今天開始，下一段路不必只靠武器決定。',image:'assets/td/story/chapter2-red-mesa-dawn-v1.png',focus:'68% 46%'}
  ];
  redmesa.aftermath='護送隊抵達終站。荒野部族選擇以自己的名義加入調查，也取得自由遠征資格；南方歷史的真相仍需要更多證據。';
  // Chapter III is deliberately a convergence of perspectives, not an origin
  // story for either faction. Every answer is observable in the mission, while
  // the cause and the distant caller remain open questions for later chapters.
  const whitetrace={id:'chapter3-white-trace',chapter:3,name:'霜線未明',map:'whitetrace',hero:'hunter',faction:'hunter',difficulty:'story',requires:redmesa.id,objective:'守住 8 波白痕隘口，保護凜的追跡隊完成裂石旁的霜痕採樣。',rewards:{maps:['whitetrace']},discovered:['white-trace'],cinematic:['赤土終站的紀錄剛被封存，北路就傳來一段不合時節的白霜。','霜牙・凜不說那是誰留下的。他只說：痕跡逆著風，卻一路指向同一個方向。','守住白痕隘口。先讓採樣與人都能離開，猜測才不會先於證據。'],waves:[{name:'逆風足音',hint:'第一個折返彎能反覆覆蓋敵軍；先穩住追跡隊身後。',groups:[{type:'grunt',count:8}]},{name:'白霜疾影',hint:'高速敵人會拉開防線，在兩段彎道安排不同射程。',groups:[{type:'runner',count:7},{type:'halberdier',count:4}]},{name:'裂石重列',hint:'重甲隊接近裂石前先集火，避免讓出口火力同時承受兩種壓力。',groups:[{type:'fallenKnight',count:5},{type:'grunt',count:7}]},{name:'採樣窗口',hint:'術士在後排延長戰線；保留技能處理最危險的一波。',groups:[{type:'runner',count:6},{type:'shaman',count:4},{type:'halberdier',count:4}]},{name:'訊號門前',hint:'巨獸穿過中段後會直逼關口；現在就建立第二層火力。',groups:[{type:'brute',count:4},{type:'revenant',count:4},{type:'fallenKnight',count:4}]},{name:'風向之外',hint:'盾衛會拖慢擊破節奏，控制與穿甲都要有位置。',groups:[{type:'warder',count:3},{type:'shaman',count:4},{type:'brute',count:3},{type:'runner',count:6}]},{name:'無主的痕跡',hint:'混編敵軍分段到達；別把資源只壓在最前方的雪地。',groups:[{type:'runner',count:8},{type:'fallenKnight',count:5},{type:'revenant',count:4}]},{name:'霜線未明',hint:'最後守住訊號門前長直道，讓凜帶走完整的霜痕標本。',groups:[{type:'runner',count:8},{type:'shaman',count:5},{type:'brute',count:4},{type:'fallenKnight',count:5}]}]};
  whitetrace.storyCards=[
    {title:'霜線未明',label:'白痕隘口 · 來客',line:'霜不是從雪地走來；它逆著風，沿著一條沒有人走過的路延伸。',image:'assets/td/chapter3-white-trace-pass-v1.png',focus:'54% 43%'},
    {title:'獵人不替痕跡說話',label:'霜牙・凜',line:'「我只報告看見的：足跡很深，周圍卻沒有任何重量壓過雪。」',image:'assets/td/chapter3-white-trace-pass-v1.png',focus:'67% 31%'},
    {title:'先帶走證據',label:'此刻的選擇',line:'凜願意同行，但先決條件是：不能讓一份猜測取代一條活著的路。',image:'assets/td/chapter3-white-trace-pass-v1.png',focus:'76% 55%'}
  ];
  whitetrace.aftermath='採樣瓶裡的霜在離開裂石後沒有融化，卻也沒有繼續擴散。凜接受同行，因為他看不懂這種痕跡；更令他在意的是，地精送來的讀值出現了同一段方向。';
  const echoyard={id:'chapter3-echo-yard',chapter:3,name:'齒輪的回聲',map:'echoyard',hero:'hunter',faction:'hunter',difficulty:'story',requires:whitetrace.id,objective:'守住 9 波回聲機座，護住奇克與工程團修復校準機並保存原始讀值。',rewards:{maps:['echoyard']},discovered:['echo-engine'],cinematic:['地精工程團的校準機收到一段回聲；奇克懷疑不是故障，卻拒絕先給它一個名字。','機器的第一筆「回覆」比訊號送出早了十七秒。奇克說，這不可能；凜說，霜痕也不可能。','守住回聲機座。若讀值被毀，剩下的只會是最容易被相信的說法。'],waves:[{name:'維修前哨',hint:'入口高台與中段彎道都能覆蓋道路，先替工程團留出工作時間。',groups:[{type:'grunt',count:9}]},{name:'斷線疾行',hint:'高速敵人會越過第一段平台；中段需要獨立的補漏。',groups:[{type:'runner',count:8},{type:'halberdier',count:4}]},{name:'機座壓力',hint:'重甲隊靠近機座時，以集中火力創造維修窗口。',groups:[{type:'fallenKnight',count:5},{type:'grunt',count:8}]},{name:'錯秒回響',hint:'術士躲在隊伍後方；使用英雄技能縮短處理重甲的時間。',groups:[{type:'shaman',count:5},{type:'runner',count:7},{type:'halberdier',count:4}]},{name:'瀑潭重隊',hint:'巨獸進入最後長路前就要受傷，別等到閘門才開始防守。',groups:[{type:'brute',count:4},{type:'revenant',count:4},{type:'fallenKnight',count:4}]},{name:'讀值保全',hint:'盾衛會壓縮火力窗口；安排能打穿前排或控住敵軍的組合。',groups:[{type:'warder',count:4},{type:'shaman',count:4},{type:'brute',count:4}]},{name:'纜線盡頭',hint:'快速、秘法與重甲混編，前後平台必須彼此照應。',groups:[{type:'runner',count:9},{type:'revenant',count:5},{type:'fallenKnight',count:5}]},{name:'不可能的回覆',hint:'最後一波先阻止敵軍穿過機座彎，再守住出口橋頭。',groups:[{type:'runner',count:9},{type:'shaman',count:5},{type:'brute',count:5},{type:'fallenKnight',count:5}]},{name:'齒輪的回聲',hint:'全線混編會考驗分段火力；讓原始讀值安全寫入記錄筒。',groups:[{type:'runner',count:10},{type:'warder',count:4},{type:'revenant',count:5},{type:'brute',count:5},{type:'shaman',count:5}]}]};
  echoyard.storyCards=[
    {title:'齒輪的回聲',label:'回聲機座 · 異常',line:'一台不該記得未來的機器，留下了一筆比提問更早的回覆。',image:'assets/td/chapter3-echo-engine-yard-v1.png',focus:'58% 38%'},
    {title:'先別替機器撒謊',label:'銅齒・奇克',line:'「不是壞掉；壞掉的機器不會每次都剛好早十七秒。」',image:'assets/td/chapter3-echo-engine-yard-v1.png',focus:'57% 48%'},
    {title:'保住原始讀值',label:'工程團的條件',line:'奇克不加入任何人的結論。他只答應把可以重測的東西留下來。',image:'assets/td/chapter3-echo-engine-yard-v1.png',focus:'79% 43%'}
  ];
  echoyard.aftermath='機座被保住了。奇克把「早十七秒」寫進原始紀錄，拒絕刪除；讀值的方位與凜的霜痕相交，卻沒有落在任何已知路名上。';
  const crossmark={id:'chapter3-crossmark',chapter:3,name:'兩種讀法',map:'crossmark',hero:'hunter',faction:'hunter',difficulty:'story',requires:echoyard.id,objective:'守住 10 波交痕溪谷，讓霜原與地精在匯流採樣點完成彼此可重複驗證的比對。',rewards:{maps:['crossmark']},discovered:['crossmark-hollow'],cinematic:['霜痕與讀值在同一條溪谷相交。這不是答案，只是一個更難忽略的問題。','凜認為溪泥留下了某種「經過」；奇克的量架卻顯示，那一刻沒有重量穿過。兩個人都不肯退讓。','守住交痕溪谷。若他們只能聽見自己，就永遠不會發現對方剛好看見了缺的那一半。'],waves:[{name:'上路與下路',hint:'雙入口會在橋頭匯流；先為兩條路各留一個防點。',groups:[{type:'grunt',count:10}]},{name:'溪谷疾行',hint:'高速敵人從兩路推進，別把全部火力放到匯流後。',groups:[{type:'runner',count:8},{type:'halberdier',count:5}]},{name:'採樣點重壓',hint:'重甲隊抵達橋頭前先集中處理，保住中央的比對時間。',groups:[{type:'fallenKnight',count:6},{type:'grunt',count:8}]},{name:'兩種讀法',hint:'術士會讓兩線壓力重疊；英雄技能留給匯流的密集窗口。',groups:[{type:'runner',count:8},{type:'shaman',count:5},{type:'halberdier',count:5}]},{name:'橋頭巨影',hint:'巨獸跨過橋頭後留給出口的時間很少，提前建立共用火力。',groups:[{type:'brute',count:5},{type:'revenant',count:4},{type:'fallenKnight',count:5}]},{name:'泥印未動',hint:'盾衛與術士會拖長處理；使用控制讓兩側火力能同時命中。',groups:[{type:'warder',count:4},{type:'shaman',count:5},{type:'runner',count:8}]},{name:'交叉校驗',hint:'兩條路的重甲間距不同，保留資源應對第二批而非只打第一批。',groups:[{type:'fallenKnight',count:6},{type:'brute',count:5},{type:'revenant',count:5}]},{name:'沒有重量的足跡',hint:'雙線混編考驗補漏；橋頭是共用防線，不是唯一防線。',groups:[{type:'runner',count:10},{type:'warder',count:4},{type:'shaman',count:5},{type:'brute',count:5}]},{name:'兩種讀法',hint:'最後一波守住橋後長路，讓兩份獨立紀錄一起離開溪谷。',groups:[{type:'runner',count:10},{type:'revenant',count:6},{type:'fallenKnight',count:6},{type:'brute',count:5},{type:'shaman',count:5}]}]};
  crossmark.storyCards=[
    {title:'兩種讀法',label:'交痕溪谷 · 匯流',line:'一邊是被壓出的泥印；另一邊是「沒有任何重量通過」的讀值。',image:'assets/td/chapter3-crossmark-hollow-v1.png',focus:'50% 43%'},
    {title:'不一致，才值得留下',label:'凜與奇克',line:'凜不肯刪掉足跡；奇克不肯改掉數字。兩人第一次同意保留彼此的反對。',image:'assets/td/chapter3-crossmark-hollow-v1.png',focus:'57% 40%'},
    {title:'讓兩份記錄都走出去',label:'共同校驗',line:'如果真相只容得下一種讀法，那它大概還不是能被信任的真相。',image:'assets/td/chapter3-crossmark-hollow-v1.png',focus:'75% 52%'}
  ];
  crossmark.aftermath='比對完成：泥印、霜痕與早十七秒的回覆都曾出現在同一瞬間。它們可以同時成立，卻無法由同一個已知事物解釋；奇克提出最後一次校準。';
  const nightwatch={id:'chapter3-nightwatch',chapter:3,name:'夜守校準',map:'nightwatch',hero:'hunter',faction:'hunter',difficulty:'story',requires:crossmark.id,objective:'守住 11 波夜守校準站，保護霜原與地精共同完成最後一次交叉觀測。',rewards:{maps:['nightwatch'],heroes:['frostland','goblin'],factions:['frostland','goblin']},discovered:['nightwatch-calibration'],cinematic:['最後一次校準不需要誰先相信誰；它只需要兩人都願意把錯誤的可能留在自己的紀錄裡。','訊標亮起時，三條指向不同地點的線收束成同一個空白。它沒有指向南方，也沒有指向一個可以命名的敵人。','守住夜守校準站。今晚能確認的只有一件事：有人，或有什麼，正在回應我們尚未送出的問題。'],waves:[{name:'月下前哨',hint:'折返古道適合多段火力，先處理第一個彎道的壓力。',groups:[{type:'grunt',count:11}]},{name:'夜谷疾行',hint:'高速敵人穿越折返會拖開戰線；中段與橋頭都要能補漏。',groups:[{type:'runner',count:9},{type:'halberdier',count:5}]},{name:'訊標重列',hint:'重甲隊走向校準橋前就要承受集中火力。',groups:[{type:'fallenKnight',count:6},{type:'grunt',count:9}]},{name:'三線微光',hint:'術士與快速敵人同時壓線；保留技能給靠近橋頭的密集波。',groups:[{type:'runner',count:9},{type:'shaman',count:5},{type:'halberdier',count:5}]},{name:'橋前巨獸',hint:'巨獸進橋後距離出口很短，先讓第二層防線開始輸出。',groups:[{type:'brute',count:5},{type:'revenant',count:5},{type:'fallenKnight',count:5}]},{name:'失真的回聲',hint:'盾衛會延長敵軍停留，善用控制讓交叉火力取得時間。',groups:[{type:'warder',count:5},{type:'shaman',count:5},{type:'runner',count:9}]},{name:'各自的誤差',hint:'兩批重甲錯開到達；別一次投入所有資源。',groups:[{type:'fallenKnight',count:7},{type:'brute',count:5},{type:'revenant',count:5}]},{name:'橋上空白',hint:'混編敵軍會測試每段防線，校準台本身不可作為塔位。',groups:[{type:'runner',count:10},{type:'warder',count:5},{type:'shaman',count:5},{type:'brute',count:5}]},{name:'不屬於任何一方',hint:'前段折返能拖延高速敵人；後段關口必須留有最後火力。',groups:[{type:'runner',count:10},{type:'revenant',count:6},{type:'fallenKnight',count:6},{type:'brute',count:5}]},{name:'夜守校準',hint:'最終混編衝擊全線；守住橋與關口，讓兩份紀錄完成封存。',groups:[{type:'runner',count:11},{type:'warder',count:5},{type:'shaman',count:6},{type:'fallenKnight',count:6},{type:'brute',count:6}]},{name:'尚未送出的問題',hint:'最後一波沒有捷徑：分段控場、穿甲與出口補漏都必須完成。',groups:[{type:'runner',count:11},{type:'revenant',count:6},{type:'fallenKnight',count:7},{type:'brute',count:6},{type:'shaman',count:6}]}]};
  nightwatch.storyCards=[
    {title:'夜守校準',label:'夜谷 · 最後一次觀測',line:'兩個人都把「我可能錯了」寫進紀錄，才讓這次合作真正開始。',image:'assets/td/chapter3-nightwatch-calibration-v1.png',focus:'57% 47%'},
    {title:'三條線，一個空白',label:'校準結果',line:'訊標同時指向三個方向，卻沒有一條指向能被命名的來源。',image:'assets/td/chapter3-nightwatch-calibration-v1.png',focus:'66% 35%'},
    {title:'不急著追答案',label:'霜原與地精',line:'凜負責追跡，奇克負責重測。他們以自己的名義加入調查，而不是加入任何人的結論。',image:'assets/td/chapter3-nightwatch-calibration-v1.png',focus:'65% 54%'}
  ];
  nightwatch.aftermath='校準完成。霜原獵群與地精工程團各自保留原始紀錄，也選擇以共同調查夥伴身分加入自由遠征。訊標最後一次閃爍；它回應了尚未送出的問題，卻沒有留下能辨認來源的名字。';
  // Chapter IV makes the already-playable Naga expedition visible in the
  // main investigation. It records a repeatable tidal response only; it does
  // not name a source, an ancient people, or an answer to the anomaly.
  const tidegateoutfall={id:'chapter4-tidegate-outfall',chapter:4,name:'潮門外流',map:'tidegateoutfall',hero:'naga',faction:'naga',difficulty:'story',requires:nightwatch.id,objective:'守住 8 波潮門外流，協助破潮者・賽洛完成第一輪潮流讀值並護送觀測記錄離開礁岸。',rewards:{maps:['tidegateoutfall']},discovered:['tidegate-outfall'],cinematic:['夜守站封存的方位沒有名字，卻在沿岸潮門附近重複出現。','破潮者・賽洛沒有替那道回應下結論；他只辨認出潮流正在以不該有的節奏折返。','守住潮門外流。先讓可以再測一次的讀值與觀測者一起離開。'],waves:[{name:'潮門前哨',hint:'先用入口高地穩住沿岸古道。',groups:[{type:'grunt',count:9}]},{name:'逆潮疾行',hint:'快速敵人會穿過折返段，中段需要獨立補漏。',groups:[{type:'runner',count:7},{type:'halberdier',count:4}]},{name:'鹽霧重列',hint:'重甲隊靠近潮門前先集火處理。',groups:[{type:'fallenKnight',count:5},{type:'grunt',count:7}]},{name:'讀值窗口',hint:'術士在後排延長戰線，技能留給密集窗口。',groups:[{type:'runner',count:6},{type:'shaman',count:4},{type:'halberdier',count:4}]},{name:'礁岸巨影',hint:'巨獸通過中段後會直逼出口，提早建立第二層火力。',groups:[{type:'brute',count:4},{type:'revenant',count:4},{type:'fallenKnight',count:4}]},{name:'折返潮聲',hint:'盾衛拖慢擊破節奏，控制與穿甲要同時到位。',groups:[{type:'warder',count:3},{type:'shaman',count:4},{type:'brute',count:3},{type:'runner',count:6}]},{name:'外流記錄',hint:'混編敵軍分段到達，別把資源只放在第一個彎。',groups:[{type:'runner',count:8},{type:'fallenKnight',count:5},{type:'revenant',count:4}]},{name:'潮門外流',hint:'最後守住潮門前長路，讓第一份讀值安全封存。',groups:[{type:'runner',count:8},{type:'shaman',count:5},{type:'brute',count:4},{type:'fallenKnight',count:5}]}]};
  tidegateoutfall.storyCards=[{title:'潮門外流',label:'礁岸潮門 · 第一輪讀值',line:'潮流在退去時回頭，像是在等一個尚未被提出的問題。',image:'assets/td/chapter4-tidegate-outfall-v1.png',focus:'55% 48%'},{title:'潮汐不替人說話',label:'破潮者・賽洛',line:'「我能說的是它回折了；不能說它為什麼回折。」',image:'assets/td/chapter4-tidegate-outfall-v1.png',focus:'68% 43%'},{title:'把讀值帶出去',label:'觀測原則',line:'第一輪記錄不是答案。能被下一次檢查，才值得守住。',image:'assets/td/chapter4-tidegate-outfall-v1.png',focus:'78% 61%'}];
  tidegateoutfall.aftermath='潮門的回折被完整記下。賽洛確認這不是普通潮汐，卻拒絕為它補上一個來源；下一段異常出現在鹽脊航道。';
  const brineway={id:'chapter4-brineway',chapter:4,name:'鹽潮航道',map:'brineway',hero:'naga',faction:'naga',difficulty:'story',requires:tidegateoutfall.id,objective:'守住 9 波鹽潮航道，護住娜迦潮衛與工程團沿著風暴堤道完成第二次重測。',rewards:{maps:['brineway']},discovered:['brineway-surge'],cinematic:['第一輪讀值換了時間仍然出現；潮衛帶著量具沿鹽脊航道重測。','工程團記錄壓力，賽洛記錄潮向。兩份資料相符，卻都沒有告訴他們誰在另一端。','守住堤道。讓兩種測法能在同一個夜晚安全抵達。'],waves:[{name:'鹽脊守望',hint:'堤道入口寬，先建立第一段穩定火力。',groups:[{type:'grunt',count:10}]},{name:'風暴疾影',hint:'高速敵人跨過堤道很快，中段平台要能補漏。',groups:[{type:'runner',count:8},{type:'halberdier',count:4}]},{name:'堤道重壓',hint:'重甲隊轉入彎道前先集中輸出。',groups:[{type:'fallenKnight',count:5},{type:'grunt',count:8}]},{name:'雙重測法',hint:'術士與快速敵人同時壓線，保留技能給交會點。',groups:[{type:'runner',count:7},{type:'shaman',count:5},{type:'halberdier',count:4}]},{name:'風眼巨獸',hint:'巨獸靠近潮閘後距離出口很短，提前準備第二層防線。',groups:[{type:'brute',count:4},{type:'revenant',count:4},{type:'fallenKnight',count:5}]},{name:'反向壓力',hint:'盾衛會壓縮火力窗口，用控制替後排爭取時間。',groups:[{type:'warder',count:4},{type:'shaman',count:4},{type:'runner',count:8}]},{name:'未署名的回覆',hint:'重甲分批抵達，別把資源全投給第一批。',groups:[{type:'fallenKnight',count:6},{type:'brute',count:4},{type:'revenant',count:4}]},{name:'鹽潮航道',hint:'混編敵軍會考驗前後平台的接力。',groups:[{type:'runner',count:9},{type:'warder',count:4},{type:'shaman',count:5},{type:'brute',count:4}]},{name:'再測一次',hint:'最後守住潮閘出口，讓原始紀錄離開風暴堤道。',groups:[{type:'runner',count:9},{type:'revenant',count:5},{type:'fallenKnight',count:5},{type:'brute',count:5},{type:'shaman',count:5}]}]};
  brineway.storyCards=[{title:'鹽潮航道',label:'風暴堤道 · 第二次重測',line:'壓力與潮向同時偏離，卻沒有一筆資料能替另一筆資料說明原因。',image:'assets/td/chapter4-brineway-v1.png',focus:'52% 46%'},{title:'兩種量具，一個問題',label:'潮衛與工程團',line:'他們同意保留相符的結果，也保留還無法解釋的空白。',image:'assets/td/chapter4-brineway-v1.png',focus:'65% 45%'},{title:'不把空白叫成答案',label:'賽洛的判斷',line:'「潮汐能帶路，但不能替我們挑一個想相信的終點。」',image:'assets/td/chapter4-brineway-v1.png',focus:'77% 60%'}];
  brineway.aftermath='第二次重測成功。潮向與壓力變化可被重複觀察，但仍無法推回來源；兩條礁岸路線在同一個交會點出現相同節奏。';
  const reefconfluence={id:'chapter4-reef-confluence',chapter:4,name:'礁環交會',map:'reefconfluence',hero:'naga',faction:'naga',difficulty:'story',requires:brineway.id,objective:'守住 10 波礁環交會，讓上下兩路的潮位觀測在橋頭完成交叉比對。',rewards:{maps:['reefconfluence']},discovered:['reef-confluence'],cinematic:['兩隊從不同礁岸出發，在同一座橋前記下相同的回折。','賽洛沒有把巧合叫成證明；他要兩份各自獨立的記錄先在同一刻比對。','守住礁環交會。橋頭不是答案，它只是讓觀測能彼此看見的地方。'],waves:[{name:'上路與下路',hint:'雙入口會在橋頭匯流，兩條路都要先有防點。',groups:[{type:'grunt',count:10}]},{name:'礁岸疾行',hint:'高速敵人從雙線推進，不要把火力全壓在匯流後。',groups:[{type:'runner',count:9},{type:'halberdier',count:5}]},{name:'潮位重列',hint:'重甲隊抵達橋頭前先集中處理。',groups:[{type:'fallenKnight',count:6},{type:'grunt',count:8}]},{name:'交叉比對',hint:'術士會讓兩線壓力重疊，英雄技能留給匯流窗口。',groups:[{type:'runner',count:8},{type:'shaman',count:5},{type:'halberdier',count:5}]},{name:'雙路巨影',hint:'巨獸跨過橋頭後留給出口的時間很少，提前建立共用火力。',groups:[{type:'brute',count:5},{type:'revenant',count:4},{type:'fallenKnight',count:5}]},{name:'潮位未動',hint:'盾衛與術士會拖長處理，讓兩側火力同時命中。',groups:[{type:'warder',count:4},{type:'shaman',count:5},{type:'runner',count:8}]},{name:'兩岸誤差',hint:'兩路重甲間距不同，保留資源應對第二批。',groups:[{type:'fallenKnight',count:6},{type:'brute',count:5},{type:'revenant',count:5}]},{name:'同一個節奏',hint:'雙線混編考驗補漏，橋頭是共用防線而非唯一防線。',groups:[{type:'runner',count:10},{type:'warder',count:4},{type:'shaman',count:5},{type:'brute',count:5}]},{name:'礁環交會',hint:'最後守住橋後長路，讓兩份獨立記錄一起離開。',groups:[{type:'runner',count:10},{type:'revenant',count:6},{type:'fallenKnight',count:6},{type:'brute',count:5},{type:'shaman',count:5}]},{name:'橋頭的空白',hint:'分段控場與出口補漏都要完成，才能保存交叉比對。',groups:[{type:'runner',count:11},{type:'warder',count:5},{type:'shaman',count:5},{type:'fallenKnight',count:6},{type:'brute',count:5}]}]};
  reefconfluence.storyCards=[{title:'礁環交會',label:'雙線礁岸 · 交叉比對',line:'兩條路帶來同一個節奏，卻都沒有帶來它從哪裡開始的答案。',image:'assets/td/chapter4-reef-confluence-v1.png',focus:'51% 46%'},{title:'讓兩份紀錄相遇',label:'橋頭觀測',line:'賽洛要的是可以彼此反駁的資料，不是一支替他背書的隊伍。',image:'assets/td/chapter4-reef-confluence-v1.png',focus:'60% 43%'},{title:'交會不是終點',label:'保留疑問',line:'同步的潮汐值得追查；來源仍舊沒有名字。',image:'assets/td/chapter4-reef-confluence-v1.png',focus:'78% 55%'}];
  reefconfluence.aftermath='橋頭比對完成。兩路資料在同一瞬間同步，卻沒有任何觀測者看見能被辨認的來者；最後一次長時觀測必須在潮儀台進行。';
  const tideobservatory={id:'chapter4-tide-observatory',chapter:4,name:'潮儀守夜',map:'tideobservatory',hero:'naga',faction:'naga',difficulty:'story',requires:reefconfluence.id,objective:'守住 11 波潮儀守夜，保護娜迦潮衛完成長時觀測並將全部原始記錄封存。',rewards:{maps:['tideobservatory']},discovered:['tide-observatory'],cinematic:['最後一次觀測不要求誰先相信誰；它只要求每一份讀值都能被留下。','潮儀台亮起時，回折的水紋比先前更清楚，卻仍沒有指向一個可以命名的來源。','守住潮儀守夜。今晚能證實的只有：這段回應仍在重複，而且值得被繼續觀察。'],waves:[{name:'守夜前哨',hint:'折返古道適合多段火力，先穩住第一個轉折。',groups:[{type:'grunt',count:11}]},{name:'潮谷疾行',hint:'高速敵人會拉開戰線，中段與橋頭都要能補漏。',groups:[{type:'runner',count:9},{type:'halberdier',count:5}]},{name:'潮儀重列',hint:'重甲隊走向觀測台前就要承受集中火力。',groups:[{type:'fallenKnight',count:6},{type:'grunt',count:9}]},{name:'長時讀值',hint:'術士與快速敵人同時壓線，保留技能給密集波。',groups:[{type:'runner',count:9},{type:'shaman',count:5},{type:'halberdier',count:5}]},{name:'橋前巨獸',hint:'巨獸進橋後距離出口很短，先讓第二層防線開始輸出。',groups:[{type:'brute',count:5},{type:'revenant',count:5},{type:'fallenKnight',count:5}]},{name:'失真的潮聲',hint:'盾衛會延長敵軍停留，善用控制取得時間。',groups:[{type:'warder',count:5},{type:'shaman',count:5},{type:'runner',count:9}]},{name:'各自的量測',hint:'兩批重甲錯開到達，別一次投入所有資源。',groups:[{type:'fallenKnight',count:7},{type:'brute',count:5},{type:'revenant',count:5}]},{name:'潮儀空白',hint:'混編敵軍測試每段防線，觀測台本身不可作為塔位。',groups:[{type:'runner',count:10},{type:'warder',count:5},{type:'shaman',count:5},{type:'brute',count:5}]},{name:'不急著命名',hint:'前段折返能拖延高速敵人，後段關口要留最後火力。',groups:[{type:'runner',count:10},{type:'revenant',count:6},{type:'fallenKnight',count:6},{type:'brute',count:5}]},{name:'潮儀守夜',hint:'最終混編衝擊全線，守住橋與關口，讓記錄完成封存。',groups:[{type:'runner',count:11},{type:'warder',count:5},{type:'shaman',count:6},{type:'fallenKnight',count:6},{type:'brute',count:6}]},{name:'仍在回應',hint:'最後一波沒有捷徑：分段控場、穿甲與出口補漏都必須完成。',groups:[{type:'runner',count:11},{type:'revenant',count:6},{type:'fallenKnight',count:7},{type:'brute',count:6},{type:'shaman',count:6}]}]};
  tideobservatory.storyCards=[{title:'潮儀守夜',label:'潮儀台 · 長時觀測',line:'水紋的回折比以往清楚，卻仍不肯給出一個可以被確認的名字。',image:'assets/td/chapter4-tide-observatory-v1.png',focus:'58% 43%'},{title:'先留下所有原始讀值',label:'破潮者・賽洛',line:'「我能守住這座台，但不能把未知替你們變成已知。」',image:'assets/td/chapter4-tide-observatory-v1.png',focus:'67% 37%'},{title:'讓調查繼續',label:'潮衛的選擇',line:'潮衛會把紀錄交給下一位觀測者，也保留自己的疑問。',image:'assets/td/chapter4-tide-observatory-v1.png',focus:'73% 55%'}];
  tideobservatory.aftermath='潮儀守夜完成。娜迦潮衛封存所有原始讀值，並選擇以觀測夥伴的身分持續同行；回應仍在重複，來源仍然未知。';
  const chapter2Preview={id:'chapter2-western-signal-preview',chapter:2,previewOnly:true,name:'荒野的回聲',storyCards:[
    {title:'西境風號',label:'西境舊哨 · 線索',line:'殘缺的調度碼越過了王國的邊界。它要帶我們去哪裡？',image:'assets/td/story/chapter2-western-signal-v1.png',focus:'center'},
    {title:'不急著相信',label:'第一次對話',line:'戈爾認得這枚舊印，卻不欠我們答案。先聽完他的條件。',image:'assets/td/story/chapter2-western-parley-v1.png',focus:'center'},
    {title:'護送這條路',label:'西行選擇',line:'讓信使與記錄安全通過，對話才有下一步。',image:'assets/td/story/chapter2-western-passage-v1.png',focus:'center'}
  ],aftermath:'西方的記憶不會替任何人定罪；它只證明，調查必須跨過舊有的疆界。'};
  // Story cards use only two visual modes.  A cast-bound card must resolve every
  // person to the actual playable hero reference; a scene-only card must not
  // pretend an unapproved face is a named person.  This is deliberately data,
  // rather than a prompt convention, so a future chapter cannot silently swap
  // a character's appearance while adding art.
  const storyBeatPlans={
    'chapter1-border':{cast:['hunter'],goal:'守住谷地城門，讓殘缺命令能被帶回查驗。',outcome:'城門守住後，調查才有一個可以追查的起點。'},
    'chapter1-silverleaf':{cast:['hunter','arcanist'],goal:'守住橋樑，讓舊盟約與調查隊一起離開溪谷。',outcome:'記錄被保存，但它只證明曾有合作，沒有替任何人定罪。'},
    'chapter1-shadowfall':{cast:['hunter','rogue'],goal:'保住證人與遺物，讓調查不在舊城斷掉。',outcome:'證言留下了，卻也顯示有人希望調查在這裡停止。'},
    'chapter1-frostborn':{cast:['hunter'],goal:'穿過雙路裂谷，護送調度紀錄抵達安全處。',outcome:'紀錄指出王城另有命令系統；下一步必須離開既有疆界。'},
    'chapter2-western-signal':{cast:['hunter','chief'],goal:'護送信使與舊印穿過西境，換取戈爾繼續對話的條件。',outcome:'戈爾同意帶來見證者；這是對話的開始，不是結論。'},
    'chapter2-ember-road':{cast:['hunter','chief'],cardImages:['assets/td/story/chapter2-ember-road-escort-v2.png',null,'assets/td/story/chapter2-ember-road-escort-v2.png',null,'assets/td/story/chapter2-ember-road-escort-v2.png'],lines:['補給車被燒毀，傷者困在火線中央；蘭恩與戈爾必須先把人帶離商道。','戈爾說得很清楚：先救人，再談部落為什麼離開南方。','敵人正沿著商道逼近；護送隊不能在煙障裡停下。'],goal:'救出荒野小隊、傷者與補給車，先用行動建立信任。',outcome:'小隊交出被燒毀的路名；下一個能查證的地點是石環。'},
    'chapter2-stone-circle':{cast:['hunter','chief'],cardImages:['assets/td/story/chapter2-stone-circle-parley-v2.png',null,'assets/td/story/chapter2-stone-circle-parley-v2.png',null,'assets/td/story/chapter2-stone-circle-parley-v2.png'],lines:['護送隊抵達石環。見證者願意開口，但要先安全離開這裡。','戈爾不替見證者說話；蘭恩也不能替任何人決定答案。','敵人封鎖石環外路，紀錄和見證者只能一起穿過包圍。'],goal:'守住石環外路，讓見證者與遷徙紀錄安全離開。',outcome:'見證者確認部落是被迫遷徙；下一段可驗證的路名指向赤岩峽橋。'},
    'chapter2-red-mesa':{cast:['hunter','chief'],cardImages:['assets/td/story/chapter2-red-mesa-escort-v2.png',null,'assets/td/story/chapter2-red-mesa-escort-v2.png',null,'assets/td/story/chapter2-bull-parting-v1.png'],lines:['傷者、見證者和紀錄都在車上；隊伍必須通過赤岩峽橋。','關口不是結盟儀式。這一戰只決定護送隊能不能活著抵達。','封鎖者已經守住橋頭；車隊一停下，所有證據都會被奪走。'],goal:'護送見證、傷者與紀錄通過最後中繼站。',outcome:'護送隊打開關口。荒野部族選擇以自己的身分繼續調查，而不是向任何旗幟效忠。',epilogue:{title:'奧魯姆的選擇',label:'戰牛・奧魯姆',line:'奧魯姆早已離開獸人部落。他不是來救部落，也不是來幫王國；封鎖擋住了他自己的路，所以他出手。',image:'assets/td/story/chapter2-bull-parting-v1.png',focus:'center',cast:['bull','chief'],visualPolicy:'cast-bound',beat:'orum'}},
    'chapter3-white-trace':{cast:['hunter','frostland','goblin'],cardImages:['assets/td/story/chapter3-white-trace-investigation-v2.png',null,'assets/td/story/chapter3-white-trace-investigation-v2.png',null,'assets/td/story/chapter3-white-trace-investigation-v2.png'],lines:['白痕隘口出現逆風延伸的霜痕。凜認為這不是自然天候。','凜負責追蹤霜痕；奇克帶著儀器記錄它的方向。兩人看到同一個異常。','敵軍正逼近採樣點；樣本和原始讀值必須同時帶走。'],goal:'讓凜的霜痕樣本與奇克的讀值離開現場，保留兩份原始記錄。',outcome:'霜痕沒有融化，讀值也指向同一個方向；兩人暫時無法解釋原因。'},
    'chapter3-echo-yard':{cast:['hunter','frostland','goblin'],cardImages:['assets/td/story/chapter3-echo-yard-study-v2.png',null,'assets/td/story/chapter3-echo-yard-study-v2.png',null,'assets/td/story/chapter3-echo-yard-study-v2.png'],lines:['奇克的校準機收到回聲，而且回聲比訊號更早抵達。','凜把霜痕方向交給奇克比對；兩份資料都指向同一個位置。','工程團必須修好機器並保存原始讀值，否則沒有人能重做測試。'],goal:'保住回聲裝置與腳印樣本，讓兩種方法都能被重測。',outcome:'裝置確實先收到回覆；凜與奇克保留彼此的證據，前往交會點比對。'},
    'chapter3-crossmark':{cast:['hunter','frostland','goblin'],cardImages:['assets/td/story/chapter3-crossmark-compare-v2.png',null,'assets/td/story/chapter3-crossmark-compare-v2.png',null,'assets/td/story/chapter3-crossmark-compare-v2.png'],lines:['霜痕與儀器讀值在交會點重疊，但兩者描述的時間不同。','凜與奇克同意不挑選對自己有利的結果；兩份記錄都要送到橋頭。','橋頭被截斷，資料一旦分開，就再也無法確認它們是否來自同一件事。'],goal:'護送兩份彼此矛盾的資料到交會點，完成第一次共同校驗。',outcome:'矛盾被完整保留，反而成為下一次校準不可缺少的線索。'},
    'chapter3-nightwatch':{cast:['hunter','frostland','goblin'],cardImages:['assets/td/story/chapter3-nightwatch-calibration-v2.png',null,'assets/td/story/chapter3-nightwatch-calibration-v2.png',null,'assets/td/story/chapter3-nightwatch-calibration-v2.png'],lines:['夜守站只剩最後一次校準機會；凜看守霜痕，奇克看守儀器。','兩人的觀測方式不同，但都同意先封存資料，再討論結論。','敵軍正在衝向校準台；這次測試失敗，就得從頭再來。'],goal:'守住校準台，讓凜與奇克完成最後一次交叉觀測。',outcome:'校準完成。凜與奇克以調查夥伴身分加入遠征，但回應的來源仍未知。'},
    'chapter4-tidegate-outfall':{cast:['naga'],cardImages:['assets/td/story/chapter4-tidegate-outfall-v2.png',null,'assets/td/story/chapter4-tidegate-outfall-v2.png',null,'assets/td/story/chapter4-tidegate-outfall-v2.png'],lines:['潮門外的海水正在逆流。賽洛要先測出它回折的時間。','賽洛不猜來源；他只記錄潮位、方向與每一次回折。','敵人沿礁岸逼近，觀測本和量具必須一起離開潮門。'],goal:'協助賽洛完成第一輪讀值，並把觀測記錄帶離礁岸。',outcome:'回折被完整記下。賽洛確認它不是普通潮汐，但拒絕把未知寫成答案。'},
    'chapter4-brineway':{cast:['naga'],cardImages:['assets/td/story/chapter4-brineway-rescue-v2.png',null,'assets/td/story/chapter4-brineway-rescue-v2.png',null,'assets/td/story/chapter4-brineway-rescue-v2.png'],lines:['風暴壓住海堤，潮衛和工程團要在堤道上做第二次重測。','工程團測壓力，賽洛測潮向；兩組數字再次同時偏離。','堤道一旦失守，量具會被海水捲走，第二次測試也無法完成。'],goal:'護住潮衛與工程團，讓壓力與潮向的第二次重測能完成。',outcome:'兩種量測相符，卻仍不能說明另一端是誰；賽洛帶著紀錄前往暗礁交會處。'},
    'chapter4-reef-confluence':{cast:['naga'],cardImages:['assets/td/story/chapter4-reef-confluence-v2.png',null,'assets/td/story/chapter4-reef-confluence-v2.png',null,'assets/td/story/chapter4-reef-confluence-v2.png'],lines:['兩岸測得的潮流在暗礁交會處碰撞，賽洛要比對兩份獨立紀錄。','兩個潮位計顯示同一個節奏；這證明異常會重複，還不能證明原因。','橋頭被切斷前，兩份資料必須在同一處完成交叉比對。'],goal:'讓兩岸獨立取得的讀值在橋頭完成交叉比對。',outcome:'同步被確認。來源依然沒有名字，下一步只能延長觀測時間。'},
    'chapter4-tide-observatory':{cast:['naga'],cardImages:['assets/td/story/chapter4-tide-observatory-v2.png',null,'assets/td/story/chapter4-tide-observatory-v2.png',null,'assets/td/story/chapter4-tide-observatory-v2.png'],lines:['潮儀台在夜裡重現相同回折。賽洛要封存所有原始讀值。','他把時間、潮位與方位分開記錄，讓下一個人也能重新驗算。','敵軍已經接近觀測站；紀錄若在今晚遺失，整條線索就必須重查。'],goal:'守住潮儀台，封存所有原始讀值，讓下一位觀測者能重查。',outcome:'潮衛持續同行。可以證實的是回應仍在重複；不能證實的來源，仍不能被編成結論。'}
  };
  // Every beat owns a distinct visual. The earlier cardImages fallback silently
  // reused one key art for up to five cards; an incomplete new mission now fails
  // loudly during development instead of shipping a repeated slideshow.
  const storyBeatShots={
    'chapter1-border':['assets/td/story/kingdom-border-at-dusk-v2.png','assets/td/story/rhen-oathkeeper-v2.png','assets/td/beginner-valley-v2.png','assets/td/story/kingdom-checkpoint-order-v2.png','assets/td/opening/hero-hunter-selection-v1.png'],
    'chapter1-silverleaf':['assets/td/story/silverleaf-valley-arrival-v2.png','assets/td/story/silverleaf-record-study-v2.png','assets/td/silverleaf-valley-v4.png','assets/td/story/silverleaf-bridge-escort-v2.png','assets/td/opening/hero-arcanist-selection-v1.png'],
    'chapter1-shadowfall':['assets/td/story/shadowfall-testimony-v2.png','assets/td/story/shadowfall-archive-reliquary-v2.png','assets/td/shadowfall-ruins-v3.png','assets/td/story/shadowfall-evacuation-v2.png','assets/td/opening/hero-rogue-selection-v1.png'],
    'chapter1-frostborn':['assets/td/story/frostborn-chasm-route-v2.png','assets/td/story/frostborn-bridge-signal-v2.png','assets/td/frostborn-chasm-v3.png','assets/td/story/frostborn-last-bridge-v2.png','assets/td/opening/hero-hunter-selection-v1.png'],
    'chapter2-western-signal':['assets/td/story/chapter2-western-signal-v1.png','assets/td/story/chapter2-western-parley-v1.png','assets/td/western-signal-v1.png','assets/td/story/chapter2-western-passage-v1.png','assets/td/opening/hero-chief-selection-v2.png'],
    'chapter2-ember-road':['assets/td/ember-road-encounter-v1.png','assets/td/story/chapter2-ember-road-escort-v2.png','assets/td/story/chapter2-ember-road-rescue-v1.png','assets/td/opening/hero-chief-selection-v2.png','assets/td/opening/hero-hunter-selection-v1.png'],
    'chapter2-stone-circle':['assets/td/stone-ring-basin-v1.png','assets/td/story/chapter2-stone-circle-parley-v2.png','assets/td/story/chapter2-stone-circle-escort-v1.png','assets/td/opening/hero-chief-selection-v2.png','assets/td/opening/hero-hunter-selection-v1.png'],
    'chapter2-red-mesa':['assets/td/red-mesa-terminus-v1.png','assets/td/story/chapter2-red-mesa-escort-v2.png','assets/td/opening/hero-hunter-selection-v1.png','assets/td/opening/hero-chief-selection-v2.png','assets/td/story/chapter2-bull-parting-v1.png','assets/td/story/chapter2-red-mesa-convoy-v1.png'],
    'chapter3-white-trace':['assets/td/chapter3-white-trace-pass-v1.png','assets/td/frostland/hero-selection-v2.png','assets/td/story/chapter3-white-trace-sample-v1.png','assets/td/goblin-chief-engineer-v1.png','assets/td/story/chapter3-white-trace-investigation-v2.png'],
    'chapter3-echo-yard':['assets/td/chapter3-echo-engine-yard-v1.png','assets/td/goblin-chief-engineer-v1.png','assets/td/story/chapter3-echo-yard-receiver-v1.png','assets/td/story/chapter3-echo-yard-study-v2.png','assets/td/story/chapter3-white-trace-investigation-v2.png'],
    'chapter3-crossmark':['assets/td/chapter3-crossmark-hollow-v1.png','assets/td/frostland/hero-selection-v2.png','assets/td/story/chapter3-crossmark-records-v1.png','assets/td/story/chapter3-crossmark-compare-v2.png','assets/td/story/chapter3-echo-yard-study-v2.png'],
    'chapter3-nightwatch':['assets/td/chapter3-nightwatch-calibration-v1.png','assets/td/story/chapter3-white-trace-investigation-v2.png','assets/td/story/chapter3-nightwatch-defense-v1.png','assets/td/story/chapter3-crossmark-compare-v2.png','assets/td/story/chapter3-nightwatch-calibration-v2.png'],
    'chapter4-tidegate-outfall':['assets/td/chapter4-tidegate-outfall-v1.png','assets/td/naga/tidebreaker-selection-v1.png','assets/td/story/chapter4-tidegate-readings-v1.png','assets/td/story/chapter4-tidegate-outfall-v2.png','assets/td/naga/faction-selection-v1.png'],
    'chapter4-brineway':['assets/td/chapter4-brineway-v1.png','assets/td/naga/tidebreaker-selection-v1.png','assets/td/story/chapter4-brineway-measurements-v1.png','assets/td/story/chapter4-brineway-rescue-v2.png','assets/td/naga/faction-selection-v1.png'],
    'chapter4-reef-confluence':['assets/td/chapter4-reef-confluence-v1.png','assets/td/naga/tidebreaker-selection-v1.png','assets/td/story/chapter4-reef-records-v1.png','assets/td/story/chapter4-reef-confluence-v2.png','assets/td/naga/faction-selection-v1.png'],
    'chapter4-tide-observatory':['assets/td/chapter4-tide-observatory-v1.png','assets/td/naga/tidebreaker-selection-v1.png','assets/td/story/chapter4-observatory-archive-v1.png','assets/td/story/chapter4-tide-observatory-v2.png','assets/td/naga/faction-selection-v1.png'],
    'chapter2-western-signal-preview':['assets/td/story/chapter2-western-signal-v1.png','assets/td/story/chapter2-western-parley-v1.png','assets/td/western-signal-v1.png','assets/td/story/chapter2-western-passage-v1.png','assets/td/opening/hero-chief-selection-v2.png']
  };
  // Score each beat by its dramatic purpose, not only by chapter or faction.
  // Themes are short original motifs in StoryMusic; no remote/copyrighted tracks.
  const storyBeatScores={
    'chapter1-border':['unease','resolve','tension','heroic','hope'],
    'chapter1-silverleaf':['wonder','mystery','tension','resolve','hope'],
    'chapter1-shadowfall':['mystery','sorrow','tension','resolve','hope'],
    'chapter1-frostborn':['unease','sorrow','tension','heroic','hope'],
    'chapter2-western-signal':['wonder','resolve','tension','heroic','joy'],
    'chapter2-ember-road':['unease','sorrow','tension','heroic','hope'],
    'chapter2-stone-circle':['mystery','resolve','tension','heroic','hope'],
    'chapter2-red-mesa':['wonder','resolve','tension','heroic','sorrow','hope'],
    'chapter3-white-trace':['mystery','sorrow','tension','resolve','hope'],
    'chapter3-echo-yard':['mystery','wonder','tension','resolve','joy'],
    'chapter3-crossmark':['unease','mystery','tension','resolve','hope'],
    'chapter3-nightwatch':['unease','sorrow','tension','heroic','hope'],
    'chapter4-tidegate-outfall':['wonder','mystery','tension','resolve','hope'],
    'chapter4-brineway':['unease','sorrow','tension','heroic','hope'],
    'chapter4-reef-confluence':['mystery','wonder','tension','resolve','hope'],
    'chapter4-tide-observatory':['mystery','sorrow','tension','heroic','hope'],
    'chapter2-western-signal-preview':['wonder','resolve','tension','heroic','joy']
  };
  const decorateStoryCards=mission=>{
    const plan=storyBeatPlans[mission.id];
    if(!plan)return;
    const shots=storyBeatShots[mission.id],expected=plan.epilogue?6:5;
    if(!shots||shots.length!==expected||new Set(shots).size!==expected)throw Error('Story beat art incomplete: '+mission.id);
    const scores=storyBeatScores[mission.id];
    if(!scores||scores.length!==expected)throw Error('Story beat score incomplete: '+mission.id);
    const original=mission.storyCards.map((card,index)=>{const beat=index===2?3:index;return {...card,line:plan.lines?.[index]||card.line,image:shots[beat],musicMood:scores[beat],cast:[...plan.cast],visualPolicy:'cast-bound'};});
    const concreteGoal={title:'本關目標',label:'現在要做什麼',line:plan.goal,image:shots[2],musicMood:scores[2],focus:'center',cast:[...plan.cast],visualPolicy:'cast-bound',beat:'objective'};
    const outcome={title:'守住之後',label:'這一戰改變了什麼',line:plan.outcome,image:shots[expected-1],musicMood:scores[expected-1],focus:'center',cast:[...plan.cast],visualPolicy:'cast-bound',beat:'outcome'};
    // Five beats make every battle understandable without revealing later truth:
    // arrival → people/position → concrete objective → immediate choice → result.
    mission.storyCards=[original[0],original[1],concreteGoal,original[2],...(plan.epilogue?[{...plan.epilogue,image:shots[4],musicMood:scores[4]}]:[]),outcome];
  };
  storyBeatPlans[chapter2Preview.id]={cast:['hunter','chief'],goal:'護送信使與舊印穿過西境，換取戈爾繼續對話的條件。',outcome:'戈爾同意帶來見證者；這是對話的開始，不是結論。'};
  decorateStoryCards(chapter2Preview);
  const missions=[mission,silverleaf,shadowfall,frostborn,westernsignal,emberroad,stonecircle,redmesa,whitetrace,echoyard,crossmark,nightwatch,tidegateoutfall,brineway,reefconfluence,tideobservatory];
  missions.forEach(decorateStoryCards);
  mission.waves=waves;
  class StoryWaves{constructor(selected=mission){this.mission=selected;}total(){return this.mission.waves.length;}get(wave){const source=this.mission.waves[wave-1];return source?{wave,name:source.name,hint:source.hint,threat:wave,spawnPace:source.spawnPace||1,groups:source.groups.map(g=>({...g})),reward:{gold:65+wave*15,lumber:2}}:null;}}
  ns.systems.StoryCatalog={mission,missions,chapter2Preview,getMission:id=>[...missions,chapter2Preview].find(m=>m.id===id)||null,StoryWaves,chapters:[{id:1,cinematicOnChapterStart:'prologue_before_shattered_peace',name:'破碎的和平',note:'四個故事任務逐步開放三張戰場；不宣告第一章真相已揭曉。'},{id:2,name:'荒野的回聲',note:'四個任務從西境古道走到赤岩終站；完成終章解鎖既有荒野部族，並保留南方歷史仍待查證的界線。'},{id:3,name:'霜線與齒輪',note:'四個任務從逆風霜痕走向共同校準；霜原與地精提供不同觀點，答案仍需被驗證。'},{id:4,name:'潮門回聲',note:'四個任務讓娜迦潮衛以觀測夥伴身分加入調查；潮流回應可被重測，但來源仍未命名。'}]};
})(globalThis.TowerFrontier);
