(function(ns){
  'use strict';
  const mission={id:'chapter1-border',chapter:1,name:'烽火初燃',map:'beginner',hero:'hunter',faction:'hunter',difficulty:'story',objective:'守住谷地城門，擊退 3 波王國叛軍。',rewards:{maps:['twinpass','silverleaf']},discovered:['kingdom-rebellion'],cinematic:['邊境的烽火，比信使先抵達王城。','昔日守衛商路的長戟衛，如今將兵鋒指向谷地。雷恩奉命守住城門，查清叛亂的源頭。','部署王國士兵守住道路，使用陷阱拖慢重甲叛軍。城門還在，希望就還在。']};
  mission.storyCards=[
    {title:'烽火初燃',label:'谷地 · 戰前',line:'邊境烽火亮起。信使還沒抵達。',image:'assets/td/beginner-valley-v2.png',focus:'center'},
    {title:'同一面旗',label:'雷恩',line:'「對面也是王國士兵。為何刀要指向自己人？」',image:'assets/td/opening/hero-hunter-selection-v1.png',focus:'center 28%'},
    {title:'守住城門',label:'此刻的選擇',line:'先守住谷地，才有機會查清命令從何而來。',image:'assets/td/opening/faction-kingdom-selection-v1.png',focus:'center'}
  ];
  const waves=[{name:'谷地哨兵',hint:'長戟衛護甲較高，先部署守軍再開戰',groups:[{type:'halberdier',count:4}]},{name:'叛軍集結',hint:'在彎道集中火力，利用陷阱延長輸出時間',groups:[{type:'halberdier',count:6}]},{name:'失誓騎士',hint:'失誓騎士帶隊壓境，召喚戰狼支援前線',groups:[{type:'halberdier',count:5},{type:'fallenKnight',count:2}]}];
  const silverleaf={id:'chapter1-silverleaf',chapter:1,name:'溪谷餘音',map:'silverleaf',hero:'hunter',faction:'hunter',difficulty:'story',requires:mission.id,objective:'沿溪谷守住橋樑，讓調查隊取得銀葉保留的舊日記錄。',rewards:{maps:['shadowfall']},discovered:['silverleaf-record'],cinematic:['溪水仍清澈，昔日盟約卻開始動搖。','王國調查隊進入銀葉溪谷，尋找能解釋衝突的記錄。這些線索尚不足以判定兇手。','守住橋樑，讓記錄安全離開溪谷。'],waves:[{name:'橋前追兵',hint:'先守第一座橋，保留金錢給後段',groups:[{type:'halberdier',count:4}]},{name:'溪谷包抄',hint:'中央草地可照顧兩段道路',groups:[{type:'runner',count:5},{type:'halberdier',count:3}]},{name:'撤離掩護',hint:'城門前留一層補漏防線',groups:[{type:'fallenKnight',count:2},{type:'halberdier',count:5}]}]};
  const shadowfall={id:'chapter1-shadowfall',chapter:1,name:'舊城疑雲',map:'shadowfall',hero:'hunter',faction:'hunter',difficulty:'story',requires:silverleaf.id,objective:'在暮影舊城守住撤離道路，尋找與禁忌歷史相關的證言。',rewards:{maps:['frostborn']},discovered:['shadowfall-ruins'],cinematic:['暮影舊城的廢墟，仍留著人們急於遺忘的聲音。','調查隊來到舊城尋找證言；現場痕跡不能直接證明任何族群有罪。','在中央廣場設防，守住唯一的撤離道路。'],waves:[{name:'舊城追兵',hint:'前段與中央廣場擇一先佈防',groups:[{type:'grunt',count:7}]},{name:'暗巷威脅',hint:'中央廣場可覆蓋彎道，但別忘記後段',groups:[{type:'runner',count:5},{type:'shaman',count:2}]},{name:'撤離時刻',hint:'出彎後仍需最後一道火力',groups:[{type:'revenant',count:3},{type:'brute',count:2}]}]};
  const frostborn={id:'chapter1-frostborn',chapter:1,name:'裂谷守望',map:'frostborn',hero:'hunter',faction:'hunter',difficulty:'story',requires:shadowfall.id,objective:'守住冰原雙入口匯合後的長橋，護送線索穿越裂谷。',rewards:{maps:[]},discovered:['frostborn-chasm'],cinematic:['冰原裂谷封住前路，兩處入口都可能出現追兵。','兩路敵軍交替抵達，最終都會走向同一段冰橋。','集中主力守住共用道路，把線索帶出裂谷。'],waves:[{name:'裂谷先鋒',hint:'先在匯流後佈塔，不需要兩邊各蓋一套',groups:[{type:'grunt',count:5}]},{name:'雙路追兵',hint:'兩入口交替出兵，匯流後共用同一防線',groups:[{type:'runner',count:4},{type:'halberdier',count:3}]},{name:'冰橋夾擊',hint:'檢查匯流處與城門前的補漏位置',groups:[{type:'fallenKnight',count:2},{type:'grunt',count:6}]}]};
  const missions=[mission,silverleaf,shadowfall,frostborn];
  mission.waves=waves;
  class StoryWaves{constructor(selected=mission){this.mission=selected;}total(){return this.mission.waves.length;}get(wave){const source=this.mission.waves[wave-1];return source?{wave,name:source.name,hint:source.hint,threat:wave,groups:source.groups.map(g=>({...g})),reward:{gold:65+wave*15,lumber:2}}:null;}}
  ns.systems.StoryCatalog={mission,missions,getMission:id=>missions.find(m=>m.id===id)||null,StoryWaves,chapters:[{id:1,cinematicOnChapterStart:'prologue_before_shattered_peace',name:'破碎的和平',note:'四個故事任務逐步開放三張戰場；不宣告第一章真相已揭曉。'},{id:2,name:'荒野的回聲',note:'後續版本開放；對應劇情完成後解鎖荒野部族。'}]};
})(globalThis.TowerFrontier);
